[Android] wallet settings
brave/brave-core pull request #11034
Opened 2021-11-12 03:38 UTC by wchen342

Resolves brave/brave-browser/issues/18896.

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2021-11-12 14:58 UTC, SergeyZhukovsky commented on android/java/org/chromium/chrome/browser/crypto_wallet/activities/BraveWalletResetActivity.java
> +        mKeyringController = null;
I also find out that mojo calls required a call `mKeyringController.close()` it says that there is a leak possible if you don't call. So please call it here and also `onDestroy` for that Activity.

2021-11-17 18:05 UTC, SergeyZhukovsky requested changes

2021-11-17 18:05 UTC, SergeyZhukovsky commented on android/java/org/chromium/chrome/browser/settings/BraveWalletAutoLockPreferences.java
> +        mKeyringController = null;
`mKeyringController.close();`

2021-11-17 18:05 UTC, SergeyZhukovsky commented on android/java/org/chromium/chrome/browser/settings/BraveWalletPreferences.java
> +        mKeyringController = null;
`mKeyringController.close();`

2021-11-17 18:05 UTC, SergeyZhukovsky commented on android/java/org/chromium/chrome/browser/settings/BraveWalletResetPreference.java
> +                        if (TextUtils.equals(inputText, "Yes")) {
what about non English locales?

2021-11-17 18:05 UTC, SergeyZhukovsky commented on android/java/org/chromium/chrome/browser/settings/BraveWalletResetPreference.java
> +        mKeyringController = null;
`mKeyringController.close();`

2021-11-18 01:20 UTC, wchen342 commented on android/java/org/chromium/chrome/browser/settings/BraveWalletResetPreference.java
> +        mKeyringController = null;
Fixed.

2021-11-18 01:20 UTC, wchen342 commented on android/java/org/chromium/chrome/browser/settings/BraveWalletPreferences.java
> +        mKeyringController = null;
Fixed.

2021-11-18 01:20 UTC, wchen342 commented on android/java/org/chromium/chrome/browser/settings/BraveWalletAutoLockPreferences.java
> +        mKeyringController = null;
Fixed.

2021-11-18 01:52 UTC, SergeyZhukovsky commented on browser/ui/android/strings/android_brave_strings.grd
> +      Are you sure you want to reset your wallet? If your wallet is not backed up, resetting will cause you to lose all account data (including any associated funds). Type "<ph name="CONFIRMATION_PHR
I guess you meant `%1$s` instead of `$1`

2021-11-18 01:55 UTC, SergeyZhukovsky commented on android/java/res/layout/brave_wallet_reset_content.xml
> +        android:text="@string/brave_wallet_reset_settings_confirmation" />
that TextView should be set dynamically to replace `Yes` placeholder like that `String.format(
                        getResources().getString(R.string.brave_wallet_reset_settings_confirmation), getResources().getString(R.string.brave_wallet_reset_settings_confirmation_phrase))`

2021-11-18 02:23 UTC, SergeyZhukovsky approved these changes
++

2021-11-18 03:35 UTC, wchen342 commented
Lint error unrelated to this PR.

2021-11-18 03:35 UTC, merged