19490
brave/brave-core pull request #11139
Opened 2021-11-17 18:41 UTC by spylogsster

Resolves https://github.com/brave/brave-browser/issues/19490

- Return CommandInProgress/BridgeNotReady error codes from transport layer
- Skip CommandInProgress error in Panel

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

- Import signing

2021-11-17 20:37 UTC, onyb requested changes

2021-11-17 20:37 UTC, onyb commented on components/brave_wallet_ui/common/trezor/trezor_bridge_keyring.ts
> +      const code = response.payload && response.payload.code ? response.payload.code : ''
```suggestion
      const error = response.payload ?? getLocale('braveWalletUnlockError')
      const code = response.payload?.code ?? ''
```

2021-11-17 20:52 UTC, spylogsster commented on components/brave_wallet_ui/common/hardware_operations.ts
> +  success: Boolean
it alerts in another places where  `boolean` is used, changed it to be same in all places

2021-11-18 05:36 UTC, spylogsster commented on components/brave_wallet_ui/common/trezor/trezor_bridge_keyring.ts
> +      const code = response.payload && response.payload.code ? response.payload.code : ''
done

2021-11-18 05:36 UTC, spylogsster commented on components/brave_wallet_ui/common/trezor/trezor_bridge_keyring.ts
>    }
done

2021-11-18 05:36 UTC, spylogsster commented on components/brave_wallet_ui/common/trezor/trezor_bridge_keyring.ts
> +import { GetAccountsHardwareOperationResult, HardwareOperationResult, SignHardwareMessageOperationResult, SignHardwareTransactionOperationResult } from '../../common/hardware_operations'
done

2021-11-18 05:36 UTC, spylogsster commented on components/brave_wallet_ui/common/trezor/trezor-bridge-transport.ts
> +  private readonly hasBridgeCreated = (): Boolean => {
done

2021-11-18 05:36 UTC, spylogsster commented on components/brave_wallet_ui/common/trezor/trezor-bridge-transport.ts
> +    return document.getElementById(this.frameId) != null
done

2021-11-18 05:36 UTC, spylogsster commented on components/brave_wallet_ui/common/hardware_operations.ts
> +  success: Boolean
done

2021-11-18 05:36 UTC, spylogsster commented on components/brave_wallet_ui/common/async/hardware.ts
> +    if (code === TrezorErrorsCodes.CommandInProgress) {
done

2021-11-18 12:32 UTC, onyb approved these changes
LGTM!

2021-11-19 04:17 UTC, merged

2021-11-29 04:08 UTC, srirambv commented
Verification passed on 

Brave | 1.34.41 Chromium: 96.0.4664.45 (Official Build) nightly (arm64)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | macOS Version 12.0.1 (Build 21A559)

- Verified able to successfully connect hardware wallets (both Ledger and Trezor)
- Verified hardware wallet accounts are added to the Secondary accounts list
- Verified multiple clicks on confirm/sign button doesn't close the wallet panel and allows to sign messages or complete the transaction