Separated Balances and Prices Calls
brave/brave-core pull request #11244
Opened 2021-11-23 19:13 UTC by Douglashdaniel

## Description 
Separated Balances and Prices Calls

Before we would call for `Prices` and `Balances` in the same method and the `Balances` was dependent on `Prices` response.
They are now separated into 2 different methods `refreshBalances` and `refreshPrices`.
This will now allow `Balances` to be displayed to the user even if the `Prices` haven't been returned yet.

(note: In the video I intentionally delayed prices from being fetched for `10` seconds to give an example.)

Resolves <https://github.com/brave/brave-browser/issues/19407>

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

https://user-images.githubusercontent.com/40611140/143087786-b9570a60-88db-40fe-b2d2-9d24c102ed74.mov

2021-11-24 02:43 UTC, onyb requested changes

2021-11-24 02:43 UTC, onyb commented on components/brave_wallet_ui/page/container.tsx
> +        fiatBalance = found.fiatBalance !== '' ? Number(found.fiatBalance) : undefined
Maybe you could do something like this:

```ts
if (found && found.fiatBalance !== '') {
  fiatBalance = Number(found.fiatBalance)
}
```

2021-11-24 02:43 UTC, onyb commented on components/brave_wallet_ui/common/reducers/wallet_reducer.ts
> +        : ''
Does it make sense to use the cached `usdPrice` from the state? Also, what do you think about `payload.usdPrice !== undefined` here? Unless the `usdPrice` is supposed to be rendered as an empty string somewhere, I think it's better to keep the `''` concept specific to unknown balances.

2021-11-24 03:47 UTC, Douglashdaniel commented on components/brave_wallet_ui/page/container.tsx
> +        fiatBalance = found.fiatBalance !== '' ? Number(found.fiatBalance) : undefined
Updated!

2021-11-24 04:24 UTC, onyb commented on components/brave_wallet_ui/common/reducers/wallet_reducer.ts
> +        : ''
Discussed internally - it's a non-issue.

2021-11-24 04:24 UTC, onyb approved these changes

2021-11-24 15:46 UTC, merged

2021-11-30 08:17 UTC, srirambv commented
Verification passed on 

Brave | 1.34.46 Chromium: 96.0.4664.45 (Official Build) nightly (x86_64 translated)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | macOS Version 12.0.1 (Build 21A559)

- Verified balance is shown when price value fetch is delayed
- Verified balance and price calls are independent of each other

https://user-images.githubusercontent.com/17010094/144010126-97e65ceb-84e4-44ac-8d23-4054cd66716a.mov