Use Contract Address for Ethereum Chain Prices
brave/brave-core pull request #11557
Opened 2021-12-10 20:43 UTC by Douglashdaniel

## Description 
We now will pass a tokens `contractAddress` as a param in the `getPrice` and `getPriceHistory` methods if the `chainId` is `0x1` (Ethereum Main Net) else we will pass the tokens `symbol` since `CoinGecko` api does not support lookup by contract address for other networks.

Resolves <https://github.com/brave/brave-browser/issues/19574>

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

2021-12-14 14:27 UTC, onyb requested changes

2021-12-14 15:28 UTC, Douglashdaniel commented on components/brave_wallet_ui/utils/api-utils.ts
> +  return isEthereumNetwork ? token.symbol === ETH.asset.symbol ? token.symbol.toLowerCase() : token.contractAddress : token.symbol.toLowerCase()
Updated!

2021-12-14 18:01 UTC, onyb approved these changes

2021-12-15 00:44 UTC, merged

2022-01-04 03:11 UTC, srirambv commented
Verification passed on 

Brave | 1.36.11 Chromium: 97.0.4692.56 (Official Build) nightly (64-bit)
-- | --
Revision | `04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}`
OS | Windows 11 Version Dev (Build 22523.1000)

- Verified test plan from PR
- Verified changing token name and symbol for the custom token retains the details from contract address


https://user-images.githubusercontent.com/17010094/148004640-89128f84-6c9b-49e9-881b-92f61f49402f.mov