chore(wallet): remove fiatBalance from Redux and use base amount units
brave/brave-core pull request #11773
Opened 2022-01-07 10:47 UTC by onyb

**Summary of changes:**
- Add native asset price to `transactionSpotPrices` field, and remove `fiatPrice`.
- Do not update balances when refreshing prices, and vice-versa.
- Do not store computed `fiatBalance` in Redux, and instead compute it from `assetBalance` and `transactionSpotPrices` using the `usePricing` custom hook.
- Do not perform amount-based computations on floating point numbers. Always use `BigNumber` for addition, multiplication, etc.
- Always represent amounts/balances in Redux using base units (ex, wei for Ethereum).

Related to https://github.com/brave/brave-browser/issues/20264.

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Demo

TBA

2022-01-07 12:22 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/exp/wallet/balances/368dc030c7e4080b637098e081e567956ae34d83-69a2d278de42b166acee52260ab757649289f87f/storybook/index.html)

2022-01-07 14:46 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/exp/wallet/balances/a6431f2b81fc9ac28e3d27c86e27ee28854aa606-69a2d278de42b166acee52260ab757649289f87f/storybook/index.html)

2022-01-07 18:23 UTC, Douglashdaniel requested changes
Nice refactor!
Left a few comments.

Additionally while testing this locally, it looks like something has re-introduced showing `0.00` balances before the actual value is returned. 

https://user-images.githubusercontent.com/40611140/148588909-a6f7bf14-c8f3-4743-aaa9-12a8043f99cc.mov

2022-01-07 18:23 UTC, Douglashdaniel commented on components/brave_wallet_ui/utils/bn-utils.ts
> +}
Should we have some tests for these?

2022-01-07 18:23 UTC, Douglashdaniel commented on components/brave_wallet_ui/common/hooks/pricing.ts
>  export default function usePricing (spotPrices: BraveWallet.AssetPrice[]) {
Should we add a test for this hook?

2022-01-10 05:55 UTC, onyb commented
@Douglashdaniel Good catch on unknown balances being displayed as `0.00`. I noticed we had the same bug with transaction/gas-fee values too, so I fixed that as well. Here's a screen recording.

https://user-images.githubusercontent.com/3684187/148723514-8845ba45-d302-4531-a388-1effb2f49790.mov

2022-01-10 06:19 UTC, onyb commented on components/brave_wallet_ui/common/hooks/pricing.ts
>  export default function usePricing (spotPrices: BraveWallet.AssetPrice[]) {
Done!

2022-01-10 06:19 UTC, onyb commented on components/brave_wallet_ui/utils/bn-utils.ts
> +}
Done

2022-01-10 10:46 UTC, onyb commented on components/brave_wallet_ui/common/hooks/swap.ts
> +        : toHex(fromAssetBalance)
If we're unable to fetch the balance (ex, if asset is in swap options list, but not in visible options list), we set the allowance to the value of the swap transaction.

2022-01-10 14:17 UTC, Douglashdaniel approved these changes
Looks good!
Nice work!

2022-01-11 02:46 UTC, merged