Avoid unnecessary re-linking on Linux
brave/brave-core pull request #11970
Opened 2022-01-24 16:26 UTC by mherrmann

Resolves https://github.com/brave/brave-browser/issues/20316

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

Only the build process is affected so no testing of the browser is necessary. The success of the fix can be tested via the steps outlined in https://github.com/brave/brave-browser/issues/20316. Specifically, by seeing whether the following commands lead to a re-linking:

`git pull && npm install && npm run sync && npm run build -- Release --channel=nightly`

2022-01-25 01:06 UTC, bridiver commented on build/commands/lib/util.js
> +    if (fs.existsSync(path.join(config.rootDir, '.gclient_entries'))) {
Looking at the origin issue I don't think this is the right fix. There is no reason why sync should update a lot of those files (web-discovery-project in particular) and we should fix the root of the problem, not treat the symptoms. `'action': ['vpython3', 'script/web_discovery_project.py', '--install', '--build'],` appears to update those files even if nothing is changed

2022-01-25 01:10 UTC, bridiver requested changes
see comments inline and https://gist.github.com/wknapik/64cda0b64f425a586635a6d3a603d1f3#gistcomment-4040525

2022-01-25 14:32 UTC, mherrmann commented
Copying here what I wrote in Slack:

I'm not sure WDP is the main culprit. The top-most comment in the original issue says

> Sync causes some objects to be rebuilt on all platforms. Ideally it shouldn't, but for now those few are acceptable.

I think this makes the point that 0 rebuilt objects is not yet realistic. Instead, the primary goal as I understand it is to reduce the rebuild time.

The main driver of rebuild time is re-linking. I've identified `gclient reset --sync` as causing it. My PR prevents it.

So my hypothesis is that fixing WDP will not avoid re-linking.

Your other proposal - removing the `--reset` flag - could be a good alternative solution. I didn't investigate it because I think this once failed for me with no local changes of mine. So I don't know whether it will be viable. But from my more limited experience than yours, it sounds like it could also be an interesting path to investigate.

2022-01-25 18:51 UTC, bridiver approved these changes

2022-01-25 18:54 UTC, bridiver commented
> So my hypothesis is that fixing WDP will not avoid re-linking.

It solves part of the problem in terms of unnecessary rebuilds

> Your other proposal - removing the `--reset` flag - could be a good alternative solution. I didn't investigate it because I think this once failed for me with no local changes of mine. So I don't know whether it will be viable. But from my more limited experience than yours, it sounds like it could also be an interesting path to investigate.

It should fail with any unstaged changes to a dep of either chromium or brave-core. If at some point we start patching deps in chromium then we'll have to revisit this (potentially committing the patch changes and letting gclient auto-rebase).

2022-01-25 18:55 UTC, bridiver commented
The final problem (afaik) is the generate_license.py script which causes a very small rebuild for `about_credits`. @fmarier is working on a fix for that.

2022-01-25 18:58 UTC, merged

2022-02-01 22:17 UTC, fmarier commented
> generate_license.py script which causes a very small rebuild for `about_credits`.

That's being addressed in <https://github.com/brave/brave-core/pull/12061>.