WIP
brave/brave-core pull request #12140
Opened 2022-02-04 13:22 UTC by spylogsster

Resolves 

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2022-02-04 16:59 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/issue-20676/f0bc88e9b3016dc39ac4e58b77f5aca096b363b7-5b8f6d710b6e22cbf63963a92ff676c3b83e4978/storybook/index.html)

2022-02-04 18:06 UTC, onyb commented on components/brave_wallet_ui/common/hooks/send.ts
> +    }
I think we need to group address checks into 3 different categories now:
- ethereum specific => ex, check for `braveWalletContractAddressError`, call `findUnstoppableDomainAddress`, `findENSAddress`, etc.
- filecoin specific => ex, check for `braveWalletNotValidFilAddress`
- generic => ex, check for `braveWalletSameAddressError`.

Feel free to create separate functions for each like this (just a suggestion):

```ts
const processEthereumAddress = React.useCallback((address: string) => {
  // ENS stuff
  //
  // Unstoppable domain stuff
  //
  // check for braveWalletContractAddressError
}, [selectedAccount])

const processFilecoinAddress = React.useCallback((address: string) => {
  // check if FIL address is valid
}, [selectedAccount])

const processAddress = React.useCallback((address: string) => {
  // check for braveWalletSameAddressError
}, [selectedAccount])

React.useEffect(() => {
  const valueToLowerCase = toAddressOrUrl.toLowerCase()

  processAddress(valueToLowerCase)
  processEthereumAddress(valueToLowerCase)
  processFilecoinAddress(valueToLowerCase)
}, [toAddressOrUrl])
```

2022-02-04 18:10 UTC, onyb commented on components/brave_wallet_ui/utils/address-utils.ts
> +  return (value.length === 41 || value.length === 86)
Can you please add some comments about these magic numbers? Ex, which one corresponds to secp256k1 address, vs BLS.

2022-02-04 18:31 UTC, darkdh requested changes

2022-02-04 18:31 UTC, darkdh commented on components/brave_wallet/browser/brave_wallet_utils.cc
> +const brave_wallet::mojom::EthereumChain kFilecoinNetworks[] = {
don't use EthereumChain for Filecoin
do it like this introducing a new `FilecoinNetwork`
https://github.com/brave/brave-browser/issues/20831

2022-02-04 18:41 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/issue-20676/f0bc88e9b3016dc39ac4e58b77f5aca096b363b7-d8d33178d3049cb367351d87a94af1f9f945a1f9/storybook/index.html)

2022-02-07 13:33 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/issue-20676/a8290945958a23b9649925e3694189872f0e3bfb-5d027805ca67cd6d315b78507f89a5b45c2cb3e7/storybook/index.html)

2022-02-07 16:59 UTC, closed without merging