Removed sidebar features and deprecated show on click option
brave/brave-core pull request #12161
Opened 2022-02-07 01:57 UTC by simonhong

fix https://github.com/brave/brave-browser/issues/20876

With this change, sidebar will be available on all platform.
and sidebar show option is "never" by default.

Resolves 

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2022-02-07 03:59 UTC, simonhong commented
Changed to Draft as some tests are failed.

2022-02-07 06:37 UTC, bsclifton commented on browser/ui/brave_browser_window.cc
> +
Can we have a comment here that these are provided for testing purposes? Maybe something like:
```
// Provide a base implementation (important for `TestBrowserWindow ` in tests)
// For real implementation, see `BraveBrowserView`
```

2022-02-07 06:51 UTC, bsclifton commented on components/sidebar/sidebar_service.cc
> +void SidebarService::MigrateSidearShowOptions() {
```suggestion
void SidebarService::MigrateSidebarShowOptions() {
```

2022-02-07 06:51 UTC, bsclifton commented on components/sidebar/sidebar_service.h
> +  void MigrateSidearShowOptions();
```suggestion
  void MigrateSidebarShowOptions();
```

2022-02-07 06:51 UTC, bsclifton commented on components/sidebar/sidebar_service.cc
> +  MigrateSidearShowOptions();
```suggestion
  MigrateSidebarShowOptions();
```

2022-02-07 06:57 UTC, bsclifton approved these changes
Left comments for a typo - but otherwise looks great 😄👍

2022-02-07 06:59 UTC, bsclifton commented on components/sidebar/sidebar_service.cc
> +      kSidebarShowOption, static_cast<int>(ShowSidebarOption::kShowNever));
@rebron @petemill should we show sidebar by default?

2022-02-07 07:02 UTC, bsclifton requested changes
Left one comment for @rebron and @petemill - we have a chat on Slack. We may consider having Sidebar show by default 😄 

We can always change the decision later. If the user never modifies this setting, we can change the default again by setting a different value with `RegisterIntegerPref`. This will update the default properly for existing users as well as new users

2022-02-07 07:20 UTC, simonhong commented on components/sidebar/sidebar_service.cc
> +void SidebarService::MigrateSidearShowOptions() {
Fixed

2022-02-07 07:20 UTC, simonhong commented on components/sidebar/sidebar_service.h
> +  void MigrateSidearShowOptions();
Fixed.

2022-02-07 20:28 UTC, mkarolin approved these changes
`chromium_src` changes LGTM

2022-02-11 00:12 UTC, simonhong commented
Kindly ping to @iefremov :)

2022-02-15 23:57 UTC, bsclifton approved these changes

2022-02-15 23:59 UTC, merged