Fixed monthly/weekly wallet usage stat functionality for P3A and usage ping
brave/brave-core pull request #12172
Opened 2022-02-07 21:38 UTC by DJAndries

Resolves brave/brave-browser#20956

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

See issue for test plan.

2022-02-08 16:18 UTC, bbondy requested changes
This looks right but there's a problem that will lead to under-reported wallet stats. 
We only send 1 ping at most during a day. So if wallet was enabled after that ping is set, then we wouldn't report a daily ping for the wallet. The wallet param would have already reported not used, even though the wallet is later used.

2022-02-09 04:04 UTC, DJAndries commented
> This looks right but there's a problem that will lead to under-reported wallet stats. We only send 1 ping at most during a day. So if wallet was enabled after that ping is set, then we wouldn't report a daily ping for the wallet. The wallet param would have already reported not used, even though the wallet is later used.

Changed to send a second usage ping if wallet is opened after the first usage ping. Browser monthly/weekly/daily usage flags will be set to false in second ping.

Also moved the "last wallet unlock" timestamp to the local state so that we can observe wallet usages in all browser profiles.

@bbondy I know that you requested using "time travel" style unit tests, but I found it hard to apply to wallet usage stats specifically. We derive monthly/weekly/daily wallet usage flags by comparing the "last unlock time" to the "last reported unlock time". We do not use the current date to perform any assessment.

2022-02-09 04:07 UTC, DJAndries commented
I will add a new test plan in the OP comment.

2022-02-11 22:03 UTC, DJAndries commented
As per internal discussion, we will be focusing on improving P3A reporting. A new PR has been created: brave/brave-core#12233

Will leave this PR open in case we decide to improve upon the usage ping functionality by adding a second usage ping when the user unlocks the wallet.

2022-02-22 17:24 UTC, bbondy commented on components/brave_wallet/browser/brave_wallet_service.cc
> +#include "chrome/browser/browser_process.h"
This is a layer violation, you can't have `chrome/*` includes in `components/brave_wallet`.

2022-02-22 17:25 UTC, bbondy commented on components/brave_wallet/browser/brave_wallet_utils.cc
> +#include "chrome/browser/browser_process.h"
Same

2022-02-22 17:50 UTC, DJAndries commented
Closing, since brave/brave-core#12310 and brave/brave-core#12277 are replacements

2022-02-22 17:50 UTC, closed without merging