feat(wallet): suggest unlimited allowance as default for swaps
brave/brave-core pull request #12337
Opened 2022-02-18 16:51 UTC by onyb

Resolves https://github.com/brave/brave-browser/issues/21198

⚠️ In future, we should add a "Learn more" button in the warning (needs some UI adjustments too), and link to a page under brave.com where we explain the security risks of unlimited token approvals.

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Demo

https://user-images.githubusercontent.com/3684187/154726422-8be147e8-346c-4bdb-9a09-9598a61577d9.mov

2022-02-18 18:18 UTC, Douglashdaniel requested changes

2022-02-18 18:18 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/extension/confirm-transaction-panel/index.tsx
> +                  Unlimited approval requested
Needs localization.

2022-02-22 12:25 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/f/wallet/unlimited-allowance/21ebdb96953099c79bdb32f7087df0b087751fa2-bf87131e331901f644a587c6c834ce7e277dab13/storybook/index.html)

2022-02-22 15:20 UTC, Douglashdaniel approved these changes
Looks good!

2022-02-22 18:34 UTC, merged

2022-02-25 04:11 UTC, srirambv commented
Verification passed on 

Brave | 1.38.1 Chromium: 99.0.4844.45 (Official Build) nightly (64-bit)
-- | --
Revision | `edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}`
OS | Windows 11 Version Dev (Build 22543.1000)

- Verified steps from PR description
- Verified when initiating swap shows `Unlimited allowance requested` warning message
- Verified able to change to custom allowance value 
- Verified once custom allowance value is set it never shows `Unlimited allowance requested` message again
- Verified able to set to different custom value and approve transaction


https://user-images.githubusercontent.com/17010094/155652028-6dbd76c9-53fe-4233-ba9e-967057c50d41.mov