fix(wallet): reset swap input fields after swap
brave/brave-core pull request #12509
Opened 2022-03-07 18:55 UTC by josheleonard

Resolves https://github.com/brave/brave-browser/issues/21429

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2022-03-08 21:19 UTC, josheleonard commented
Expect storybook logic to perform differently until all of buy/send/swap is refactored

2022-03-16 16:34 UTC, onyb requested changes

2022-03-16 16:41 UTC, josheleonard commented on components/brave_wallet_ui/common/hooks/assets.ts
> +      if (isMounted.current) {
we check it once before sending the request, then check it again once the request finishes

2022-03-16 16:46 UTC, josheleonard commented on components/brave_wallet_ui/panel/reducers/panel_reducer.ts
> +export const panelReducer = reducer
i want my IDE to know how to import the reducer by name

2022-03-16 16:55 UTC, josheleonard commented on components/brave_wallet_ui/common/hooks/assets.ts
> +import { useIsMounted } from './useIsMounted'
https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad

2022-03-16 18:54 UTC, josheleonard commented on components/brave_wallet_ui/components/buy-send-swap/tabs/swap-tab.tsx
> +            {...swap}
extra/superfluous props will not cause an editor error, but missing props will

2022-03-16 19:00 UTC, josheleonard commented on components/brave_wallet_ui/common/hooks/useIsMounted.ts
> +    return () => {
added

2022-03-16 19:02 UTC, josheleonard commented on components/brave_wallet_ui/common/hooks/select-preset.ts
> +import { useSelector } from 'react-redux'
moved to top

2022-03-16 19:03 UTC, josheleonard commented on components/brave_wallet_ui/common/hooks/assets.ts
> +  const isMounted = useIsMounted()
I'll try and see

2022-03-16 19:08 UTC, josheleonard commented on components/brave_wallet_ui/common/hooks/select-preset.test.tsx
> +import usePreset from './select-preset'
rearranged

2022-03-16 19:14 UTC, josheleonard commented on components/brave_wallet_ui/common/hooks/assets.ts
> +import { getBuyAssets } from '../async/lib'
Seems to still work for me:
<img width="304" alt="Screen Shot 2022-03-16 at 1 13 57 PM" src="https://user-images.githubusercontent.com/30185185/158669162-c867aee0-1f92-480a-894c-2a917bf9a6bc.png">
<img width="335" alt="Screen Shot 2022-03-16 at 1 14 15 PM" src="https://user-images.githubusercontent.com/30185185/158669173-db893a1b-bd5f-46e2-bcf7-2bbe3612cefd.png">

2022-03-16 19:23 UTC, josheleonard commented on components/brave_wallet_ui/common/hooks/assets.ts
> +  const isMounted = useIsMounted()
return value changed to `isMounted.current`

2022-03-16 19:29 UTC, josheleonard commented on components/brave_wallet_ui/components/buy-send-swap/tabs/swap-tab.tsx
> +            {...swap}
removed the spread since the extra args would cause unneeded re-renders

2022-03-18 22:14 UTC, josheleonard commented on components/brave_wallet_ui/common/hooks/select-preset.test.tsx
> +import * as React from 'react'
This now renders React components `<Provider />` The provider is used to give the hook access to the mocked redux store

2022-03-22 00:41 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/fix-reset-swap-inputs-after-swap-complete/62e294027d3a0568ad1a7137d22609fa95af59be-97fa5e2f919ad23f6444e9ae6108c9198bd847f0/storybook/index.html)

2022-03-22 04:07 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/fix-reset-swap-inputs-after-swap-complete/62e294027d3a0568ad1a7137d22609fa95af59be-cc003b41c6a1f57a8ff60637bfe3f9fc410f50e1/storybook/index.html)

2022-03-22 23:58 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/fix-reset-swap-inputs-after-swap-complete/cd6bdb2e2514c77976f5a8a50870908d7029520a-698705e3c9db5202824028434837a7241e2b55de/storybook/index.html)

2022-03-23 21:38 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/fix-reset-swap-inputs-after-swap-complete/6135270529427d3956dd2e79ac6911a0a3353d25-79903a522be041b2fb66d120537706af7b0a4d30/storybook/index.html)

2022-03-24 20:37 UTC, onyb approved these changes
++

Looks great! Nice refactoring with the context for async lib functions.

2022-03-24 20:39 UTC, onyb commented on components/brave_wallet_ui/common/hooks/swap.ts
> +    const { swapService, ethTxManagerProxy } = getAPIProxy()
This could be made available via a context, just like the async libs. For a later PR.

2022-03-24 22:57 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/fix-reset-swap-inputs-after-swap-complete/3969b2ea28ae0c588cea557a91488f278e8c9dd8-f2b4174f779556e58131be2508b639eb1e6afc4b/storybook/index.html)

2022-03-24 23:05 UTC, Douglashdaniel approved these changes
Looks good!

2022-03-25 00:17 UTC, merged