Fix phantom de-amp toggle
brave/brave-core pull request #12694
Opened 2022-03-22 08:39 UTC by ShivanKaul

Resolves https://github.com/brave/brave-browser/issues/21788

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2022-03-22 20:21 UTC, petemill requested changes
As discussed, we can avoid this template patch / modification entirely by instead placing the amp settings-toggle-button at https://github.com/brave/brave-core/blob/master/browser/resources/settings/brave_privacy_page/brave_personalization_options.html#L56

2022-03-23 01:43 UTC, ShivanKaul commented
There's an open issue for the one test failure on Windows: https://github.com/brave/brave-browser/issues/21809, [Slack discussion](https://bravesoftware.slack.com/archives/CA5FPHWLF/p1647877241214499).

2022-03-23 16:09 UTC, kjozwiak commented
Removing the `1.38.x` milestone as this hasn't been completed/merged. At this point, `master` is on `1.39.x` so this will be going into `1.39.x`. As per https://github.com/brave/brave-browser/issues/21788#issuecomment-1076519009, we'll need to get an uplifted created for `1.38.x`.

2022-03-23 23:18 UTC, petemill approved these changes
Great cleanup! Please squash away the other commit before merge.

2022-03-23 23:18 UTC, petemill commented on browser/resources/settings/brave_overrides/privacy_page.js
> +
remove extra whitespace

2022-03-24 01:57 UTC, merged

2022-03-24 19:04 UTC, kjozwiak commented
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.39.2 Chromium: 100.0.4896.46 (Official Build) nightly (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.556)
```

Verified the STR/Cases outline via https://github.com/brave/brave-browser/issues/21788#issue-1175088211%20&%20https://github.com/brave/brave-browser/issues/21788#issuecomment-1074781639. Also ensured that:

* enabling/disabling `Auto-redirect AMP pages` doesn't display any rogue toggles.

**`Example`** | **`Example`** | **`Example`** | **`Example`** 
---------------|-----------------|----------------|----------------
![amp1](https://user-images.githubusercontent.com/2602313/159991098-8a61f41f-d806-4692-911d-ce86f913a4a5.png) | ![amp2](https://user-images.githubusercontent.com/2602313/159991110-2525a11f-0b75-45fd-9e26-4e522aa46c5d.png) | ![amp3](https://user-images.githubusercontent.com/2602313/159991119-8f8fbcb1-3c32-42d4-b4a0-68fb0ee9f639.png) | ![amp4](https://user-images.githubusercontent.com/2602313/159991124-a7740d29-1b93-4ed7-b183-79311c1d512e.png)