Account Discovery
brave/brave-core pull request #12733
Opened 2022-03-24 11:55 UTC by supermassive

Resolves https://github.com/brave/brave-browser/issues/18104

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2022-03-24 22:06 UTC, yrliou commented
Build error on unit tests currently btw.

2022-03-28 10:48 UTC, supermassive commented
> Build error on unit tests currently btw.
There was gmock include missing. Fixed now.

2022-03-28 10:48 UTC, supermassive commented on components/brave_wallet/browser/keyring_service.cc
> +void KeyringService::OnGetTransactionCount(int discovery_account_index,
Fixed.

2022-03-28 10:48 UTC, supermassive commented on components/brave_wallet/browser/keyring_service.cc
> +void KeyringService::AddDiscoveryAccountsForKeyring(int discovery_account_index,
Fixed.

2022-03-28 10:48 UTC, supermassive commented on components/brave_wallet/browser/keyring_service.cc
> +void KeyringService::AddDiscoveryAccountsForKeyring(int discovery_account_index,
Added comment to `KeyringService::RestoreWallet` method

2022-03-28 11:27 UTC, yrliou approved these changes
++ if CI is green, nice work.
Please update the test plan in the PR description for QA manual test steps and apply QA/Test-Plan-Specified label in the associated issue, thanks.

2022-03-28 20:32 UTC, kylehickinson requested changes

2022-03-28 20:32 UTC, kylehickinson commented on components/brave_wallet/browser/keyring_service.h
> +  KeyringService(JsonRpcService* json_rpc_service, PrefService* prefs);
Will require an update on iOS to pass in the rpc service like desktops factory: https://github.com/brave/brave-core/blob/5d6e4577ebe948efc17dec768265b59b2c3f443c/ios/browser/brave_wallet/keyring_service_factory.cc#L49

2022-04-04 16:42 UTC, kylehickinson approved these changes
iOS++

2022-04-05 10:46 UTC, merged