Auto-add swap taker asset to visible asset list
brave/brave-core pull request #12745
Opened 2022-03-25 01:50 UTC by onyb

Also includes the following changes to `useAssetManagement` hook:
* Refactor to reduce some logic duplication.
* Remove props-drilling, inspired by https://github.com/brave/brave-core/pull/12509.
* Re-write unit-tests and improve reliability.

Resolves https://github.com/brave/brave-browser/issues/21428

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Demo

https://user-images.githubusercontent.com/3684187/160037276-2417f253-4fca-43b0-badb-7375f6994994.mov

2022-03-25 03:04 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/f/wallet-asset-mgmt-refactor/a4178fbc86ae85040ecfa3c17d3ad5de63738c24-86d1a2ef67941046182ad55bbbbfcf882578c496/storybook/index.html)

2022-03-25 13:02 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/f/wallet-asset-mgmt-refactor/2b60c8d8b540839dade5cd470d677b113ed7c7f2-7cee45efebd12dbee4a75727b31a48222eccdaf5/storybook/index.html)

2022-03-26 04:15 UTC, Douglashdaniel approved these changes
This is awesome! nice work!

2022-03-28 18:09 UTC, josheleonard requested changes

2022-03-28 18:09 UTC, josheleonard commented on components/brave_wallet_ui/common/hooks/swap.ts
>    }, [swapAssetOptions])
FromAsset and toAsset missing from hook dependancies

2022-03-28 18:11 UTC, onyb commented on components/brave_wallet_ui/common/hooks/balance.ts
> -        token.contractAddress === '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee'
We still are, but here's how we're doing it now: https://github.com/brave/brave-core/pull/12745/files#diff-45697d7d6d02ec25665d4b2222d3fdaa2db9317b03c65e311d6f1fe73020ba5eR136-R137.

2022-03-29 15:52 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/f/wallet-asset-mgmt-refactor/e8aa9b69c03349420a34e92934befcda9a48742f-192bdc0f315daee44bf54033fadf1533adce1d05/storybook/index.html)

2022-03-29 17:02 UTC, josheleonard approved these changes

2022-03-29 19:35 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/f/wallet-asset-mgmt-refactor/5bbbc3842e45dff74fa4bd6dee8f740f0c74cae0-192bdc0f315daee44bf54033fadf1533adce1d05/storybook/index.html)

2022-03-29 20:12 UTC, merged

2022-03-29 22:37 UTC, darkdh commented
why are we merging this PR into master when tests were all failed on CI?

2022-03-29 22:40 UTC, darkdh commented
https://ci.brave.com/job/pr-brave-browser-f-wallet-asset-mgmt-refactor-linux/5/execution/node/226/log/
https://ci.brave.com/job/pr-brave-browser-f-wallet-asset-mgmt-refactor-macos/3/execution/node/214/log/
https://ci.brave.com/job/pr-brave-browser-f-wallet-asset-mgmt-refactor-windows/3/execution/node/233/log/