chore: refactor portfolio components to use redux
brave/brave-core pull request #12937
Opened 2022-04-07 17:27 UTC by josheleonard

Resolves https://github.com/brave/brave-browser/issues/22110

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
Expect no regressions within the portfolio view

2022-04-07 18:51 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/chore-use-redux-in-portfolio-refactor/e04be5e857b8bcbf58463523b352599be67c6f54-02ebf7e662301cdffb1b9719bfd16ba2ca2bed92/storybook/index.html)

2022-04-11 19:46 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/chore-use-redux-in-portfolio-refactor/dc832a6232ad9a718a4d40843dd9b0f15c474f72-e9eedea783b48f810da370be4b11ce01c1805926/storybook/index.html)

2022-04-12 18:02 UTC, Douglashdaniel requested changes

2022-04-12 18:28 UTC, Douglashdaniel commented
`SelectedAssets` price is persisting the last `hover` value.
It should change back to the `SelectedAssets` current price value on `mouseLeave`

https://user-images.githubusercontent.com/40611140/163029221-b2981299-1d1f-43d3-a1de-1429bcac612a.mov

2022-04-12 18:31 UTC, Douglashdaniel commented
![Screen Shot 2022-04-12 at 12 29 57 PM](https://user-images.githubusercontent.com/40611140/163029589-77c21b17-e862-4b2f-95d6-7b3ffd87782c.png)

`CustomReferenceDot` is not rendering for a `SelectedAsset`

2022-04-12 18:53 UTC, josheleonard commented on components/brave_wallet_ui/components/desktop/portfolio-transaction-item/index.tsx
> +  const onClickCancelTransaction = React.useCallback(() => onCancelTransaction(transaction), [transaction])
re-organized declarations

2022-04-12 18:53 UTC, josheleonard commented on components/brave_wallet_ui/components/desktop/portfolio-transaction-item/index.tsx
> +      onSelectAsset(asset)
re-organized declarations

2022-04-12 18:53 UTC, josheleonard commented on components/brave_wallet_ui/components/desktop/portfolio-transaction-item/index.tsx
> +    const asset = findToken(symbol)
re-organized declarations

2022-04-12 18:53 UTC, josheleonard commented on components/brave_wallet_ui/components/desktop/portfolio-transaction-item/index.tsx
> +  }
re-organized declarations

2022-04-12 19:40 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/chore-use-redux-in-portfolio-refactor/346e150476353ce0c41b1c703acadd2e5f4ddca7-722ea1c38b817ce0edd0ef1b3e4bc3e7fc3e9d4a/storybook/index.html)

2022-04-12 20:47 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/chore-use-redux-in-portfolio-refactor/346e150476353ce0c41b1c703acadd2e5f4ddca7-0a7f242a8ec73a34502cfa79dbe892b0b48239e2/storybook/index.html)

2022-04-13 00:34 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/chore-use-redux-in-portfolio-refactor/60fbd0e9399f2c3e1e80ab642a5f0d0b02f1d697-16415734cd4a595fc3f6e49f0b026e4f06cb485e/storybook/index.html)

2022-04-13 14:26 UTC, Douglashdaniel approved these changes
LGTM!

2022-04-13 18:19 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/chore-use-redux-in-portfolio-refactor/feebf82abe69600a3b491931b62fe55035d725ec-16415734cd4a595fc3f6e49f0b026e4f06cb485e/storybook/index.html)

2022-04-13 19:35 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/chore-use-redux-in-portfolio-refactor/7c847208aa9da22210de62d161957e1c1b102f34-16415734cd4a595fc3f6e49f0b026e4f06cb485e/storybook/index.html)

2022-04-13 20:42 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/chore-use-redux-in-portfolio-refactor/7c847208aa9da22210de62d161957e1c1b102f34-b0b57112673d499996739906aebb97664b0f46c1/storybook/index.html)

2022-04-14 02:02 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/chore-use-redux-in-portfolio-refactor/d9ed399694ed8d084aacf619769a7ab76b962c66-b0b57112673d499996739906aebb97664b0f46c1/storybook/index.html)

2022-04-14 17:23 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/chore-use-redux-in-portfolio-refactor/3e58bfceb4254df7a4b15d0d13711002fabe3828-b0b57112673d499996739906aebb97664b0f46c1/storybook/index.html)

2022-04-14 18:19 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/chore-use-redux-in-portfolio-refactor/3e58bfceb4254df7a4b15d0d13711002fabe3828-cbb6b7b795612878616d574838071327f1e32cc5/storybook/index.html)

2022-04-15 03:55 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/chore-use-redux-in-portfolio-refactor/4f7bad4bbba636a958d1818abe1dd7d8d05339d5-30a7b53b8a65fafcc111899a90d85be8db2b3020/storybook/index.html)

2022-04-18 17:53 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/chore-use-redux-in-portfolio-refactor/ceec5ff56a7bc9c0c11928276900d37d36d20a70/storybook/index.html)

2022-04-18 19:58 UTC, merged