feat(wallet): Wired Up SelectedCoin in UI
brave/brave-core pull request #13344
Opened 2022-05-16 18:24 UTC by Douglashdaniel

## Description 
Wires up `getSelectedCoin` and `setSelectedCoin` in the Wallet UI
This also allowed to fix a bug where the `SelectedAccount` and `SelectedNetwork` were not updating between the `Panel` and the `Page.

Resolves <https://github.com/brave/brave-browser/issues/22820>
Resolves <https://github.com/brave/brave-browser/issues/22564>

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

https://user-images.githubusercontent.com/40611140/168657359-2373ecb0-b19d-4bb6-85a1-4067d59b0253.mov

2022-05-16 19:28 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/wired-up-selectedCoin-in-ui/40fd575012889f6a1d41554d33940e8fec20bd3c/storybook/index.html)

2022-05-16 21:58 UTC, josheleonard requested changes

2022-05-16 21:58 UTC, josheleonard commented on components/brave_wallet_ui/common/async/handlers.ts
> +  const { accounts, networkList } = state
can be combined with line above

2022-05-16 21:58 UTC, josheleonard commented on components/brave_wallet_ui/common/async/handlers.ts
> +  const { braveWalletService, keyringService, jsonRpcService } = apiProxy
can be combined with line above

2022-05-16 21:58 UTC, josheleonard commented on components/brave_wallet_ui/common/async/handlers.ts
> +  const jsonRpcService = getAPIProxy().jsonRpcService
de-structuring preferred

2022-05-16 21:58 UTC, josheleonard commented on components/brave_wallet_ui/common/wallet_api_proxy.ts
> +      selectedAccountChanged: function (coin) {
add arg type?

2022-05-16 22:41 UTC, Douglashdaniel commented on components/brave_wallet_ui/common/async/handlers.ts
> +  const { accounts, networkList } = state
Combined!

2022-05-16 22:41 UTC, Douglashdaniel commented on components/brave_wallet_ui/common/async/handlers.ts
> +  const { braveWalletService, keyringService, jsonRpcService } = apiProxy
Combined!

2022-05-16 22:42 UTC, Douglashdaniel commented on components/brave_wallet_ui/common/async/handlers.ts
> +  const jsonRpcService = getAPIProxy().jsonRpcService
Deconstructed!

2022-05-16 22:42 UTC, Douglashdaniel commented on components/brave_wallet_ui/common/wallet_api_proxy.ts
> +      selectedAccountChanged: function (coin) {
Added type!

2022-05-16 22:59 UTC, josheleonard approved these changes

2022-05-16 23:10 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/wired-up-selectedCoin-in-ui/477532a866cfae8d5e166820ee25be8c9f62d152/storybook/index.html)

2022-05-17 01:20 UTC, merged

2022-05-18 04:51 UTC, srirambv commented
Verification passed on <html><head></head>
<body>
<!--StartFragment-->

Brave | 1.40.64 Chromium: 102.0.5005.50 (Official Build) nightly (64-bit)
-- | --
Revision | `f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}`
OS | Windows 11 Version 22H2 (Build 22621.1)

<!--EndFragment-->
</body>
</html>

- Verified steps from PR 
- Verified selecting account from panel automatically updates the account on the widget

https://user-images.githubusercontent.com/17010094/168959313-f74d9c90-d904-41ee-9b3c-18f8fdef9931.mov