feat(wallet): Solana Address Validation in UI
brave/brave-core pull request #13349
Opened 2022-05-16 20:38 UTC by Douglashdaniel

## Description 
Adds `Solana` address validation in the UI

- Checks if the address is a Base58 Encoded Solana Public key
- Check if the address is not a Tokens Contract Address
- Checks if the address is not the same as the sending address

Resolves <https://github.com/brave/brave-browser/issues/22879>

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

https://user-images.githubusercontent.com/40611140/168678114-373ed6bb-d67c-406f-8d90-eb6a4a7a54cb.mov

2022-05-16 21:40 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/wired-up-solana-address-validation-in-ui/21bd858c9b3d343732b4be4fb55deb31581ed6cd/storybook/index.html)

2022-05-16 21:49 UTC, josheleonard requested changes

2022-05-16 21:49 UTC, josheleonard commented on components/brave_wallet_ui/common/async/lib.ts
> +  return (await braveWalletService.isBase58EncodedSolanaPubkey(value))
await can be removed here

2022-05-16 21:49 UTC, josheleonard commented on components/brave_wallet_ui/common/hooks/send.ts
> +    // Do nothing is value is an empty string
typo

2022-05-16 22:53 UTC, Douglashdaniel commented on components/brave_wallet_ui/common/async/lib.ts
> +  return (await braveWalletService.isBase58EncodedSolanaPubkey(value))
Good catch, updated!

2022-05-16 22:53 UTC, Douglashdaniel commented on components/brave_wallet_ui/common/hooks/send.ts
> +    // Do nothing is value is an empty string
Fixed!

2022-05-16 22:58 UTC, josheleonard requested changes

2022-05-16 22:58 UTC, josheleonard commented on components/brave_wallet_ui/common/hooks/send.ts
>      setAddressWarning('')
these probably should go in a `.finally` of `isBase58EncodedSolanaPubkey` to prevent race conditions

2022-05-16 23:21 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/wired-up-solana-address-validation-in-ui/5723e27b566bf2ec676f603c9cb1257158d56467/storybook/index.html)

2022-05-17 15:56 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/wired-up-solana-address-validation-in-ui/084c4fbd4447274400faa17a0b5febab292808f8/storybook/index.html)

2022-05-17 16:58 UTC, josheleonard approved these changes

2022-05-17 22:21 UTC, Douglashdaniel commented
Failed IOS build is not related to this PR

2022-05-17 22:22 UTC, merged

2022-05-18 05:00 UTC, srirambv commented
Verification passed on <html><head></head>
<body>
<!--StartFragment-->

Brave | 1.40.64 Chromium: 102.0.5005.50 (Official Build) nightly (64-bit)
-- | --
Revision | `f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}`
OS | Windows 11 Version 22H2 (Build 22621.1)

<!--EndFragment-->
</body>
</html>

- Verified steps from PR
- Verified address validation is done against Contract address, same address and invalid address

https://user-images.githubusercontent.com/17010094/168960649-0b04f829-a0f0-4cab-934d-42c36eb25347.mov