feat(wallet): Update Send Placeholder Multichain
brave/brave-core pull request #13363
Opened 2022-05-17 21:30 UTC by Douglashdaniel

## Description 
Updates the `Send` input placeholder text to support `Multichain`

- `ETH` networks will show `Wallet address or URL`
- `SOL` and `FIL` networks will show `Wallet address`

Resolves <https://github.com/brave/brave-browser/issues/22755>

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

https://user-images.githubusercontent.com/40611140/168913030-f7864c24-b588-4135-b7fa-927e3b9d001b.mov

2022-05-17 21:48 UTC, josheleonard requested changes

2022-05-17 21:48 UTC, josheleonard commented on components/resources/wallet_strings.grdp
> +  <message name="IDS_BRAVE_WALLET_SEND_NO_URL_PLACEHOLDER" desc="BuySendSwap send placeholder with out URL">Wallet address</message>
typo: "without"

2022-05-17 21:57 UTC, Douglashdaniel commented on components/resources/wallet_strings.grdp
> +  <message name="IDS_BRAVE_WALLET_SEND_NO_URL_PLACEHOLDER" desc="BuySendSwap send placeholder with out URL">Wallet address</message>
🤦 fixed!

2022-05-17 22:27 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/update-send-placeholder-for-multichain/413a5276b0ec024e9b1ac04e1070e0858c389a49/storybook/index.html)

2022-05-18 14:09 UTC, muliswilliam approved these changes

2022-05-18 14:09 UTC, muliswilliam commented
LGTM

2022-05-18 16:11 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/update-send-placeholder-for-multichain/636f9270e1e21fbd2f6aa8eb5354e32eff142fe6/storybook/index.html)

2022-05-18 16:43 UTC, josheleonard approved these changes

2022-05-18 17:19 UTC, Douglashdaniel commented
Failed IOS build is not related to this PR

2022-05-18 17:19 UTC, merged