Put updated DNT strings into override
brave/brave-core pull request #13736
Opened 2022-06-10 16:54 UTC by bsclifton

Changes originally done in https://github.com/brave/brave-core/pull/13515

But it updates a file that is auto-generated. This is moving to overrides.

Fixes https://github.com/brave/brave-browser/issues/17177 

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used GitHub [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
* Run brave Browser
* Go to Settings > Privacy and security
* Click `Cookies and other site data`
* Select `Send a 'Do not Track' request...'
* Dialog text is updated

2022-06-10 17:25 UTC, emerick approved these changes
LGTM

2022-06-10 18:25 UTC, bsclifton commented
Visiting brave://settings/cookies looks like this didn't work; will check this out more
![image](https://user-images.githubusercontent.com/4733304/173127759-53f9abc1-6f11-4559-8d0b-713457a76d46.png)

2022-06-10 23:48 UTC, mkarolin requested changes
This file is auto-generated with each Chromium bump, so these changes would get lost. 
They need to go to one of the brave GRD files (brave_generated_resources.grd or maybe brave_settings_strings.grdp). Then, you can redefine the string IDS_ in `chromium_src/chrome/browser/ui/webui/settings/settings_localized_strings_provider.cc` to the ones that you use in brave GRD file.

2022-06-11 00:01 UTC, bsclifton commented
Updated - this way should work just fine since it's doing a dictionary replacement (and key matches upstream):
https://source.chromium.org/chromium/chromium/src/+/main:content/browser/webui/web_ui_data_source_impl.cc;l=177-181;drc=ead449e91b32cf231f53fb2f3999413ee06b791a

In DM with @mkarolin though - this could be a problem if upstream changes their key. Will look at how bad updating the key on the polymer side is

2022-06-14 09:41 UTC, bsclifton commented
cc: @petemill on this one 😄 What I did above is probably fine - but I was looking at a more "proper" way to grab the localization string (so we'd have a 100% match that we can override with our own). Only dug in because I'm curious because this could be more useful on other pages (avoiding a patch or chromium source override for the template html)

Here's the template file for `settings-do-not-track-toggle` (upstream file)
https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/resources/settings/privacy_page/do_not_track_toggle.html

For this example, I'm trying to grab `$i18nRaw{doNotTrackDialogMessage}` (at `div[slot='body']`)

I looked at using both `RegisterPolymerTemplateModifications` and `RegisterPolymerComponentBehaviors` to intercept the template (to try and read the key name being requested). For example:
```diff
diff --git a/browser/resources/settings/brave_overrides/cookies_page.js b/browser/resources/settings/brave_overrides/cookies_page.js
index d889f87e71..708c90af2f 100644
--- a/browser/resources/settings/brave_overrides/cookies_page.js
+++ b/browser/resources/settings/brave_overrides/cookies_page.js
@@ -19,5 +19,9 @@ RegisterPolymerTemplateModifications({
     } else {
       networkPredictionToggle.setAttribute('hidden', 'true')
     }
+  },
+  'settings-do-not-track-toggle': (templateContent) => {
+    const demo = templateContent.querySelector('template[is=dom-if][if="[[showDialog_]]"]')
+    console.log('BSC]]', demo)
   }
 })
```

and
```diff
diff --git a/browser/resources/settings/brave_overrides/cookies_page.js b/browser/resources/settings/brave_overrides/cookies_page.js
index d889f87e71..dff37c4a77 100644
--- a/browser/resources/settings/brave_overrides/cookies_page.js
+++ b/browser/resources/settings/brave_overrides/cookies_page.js
@@ -3,7 +3,7 @@
 // License, v. 2.0. If a copy of the MPL was not distributed with this file,
 // you can obtain one at http://mozilla.org/MPL/2.0/.

-import {RegisterPolymerTemplateModifications} from 'chrome://brave-resources/polymer_overriding.js'
+import {RegisterPolymerTemplateModifications, RegisterPolymerComponentBehaviors} from 'chrome://brave-resources/polymer_overriding.js'

 RegisterPolymerTemplateModifications({
   'settings-cookies-page': (templateContent) => {
@@ -21,3 +21,16 @@ RegisterPolymerTemplateModifications({
     }
   }
 })
+
+const BraveUpdateDoNotTrackTextBehavior = {
+  ready: function () {
+    const demo = this.$$('dom-if')
+    console.log('BSC]]', demo)
+  }
+}
+
+RegisterPolymerComponentBehaviors({
+  'settings-do-not-track-toggle': [
+    BraveUpdateDoNotTrackTextBehavior
+  ]
+})
```
In either case, the value is hidden in shadow dom

output from `RegisterPolymerTemplateModifications`
![image](https://user-images.githubusercontent.com/4733304/173543159-9512e260-fdb2-4851-b0e0-19f258dd9cf6.png)

output from `RegisterPolymerComponentBehaviors`
![image](https://user-images.githubusercontent.com/4733304/173544863-a2ae1d5c-9e89-498a-acd9-1c7e1afcd1e3.png)

There's a method which almost seems perfectly suited for this; `RegisterPolymerComponentProperties`

But in this case - I'm not sure how to override `doNotTrackDialogMessage` (passed into `$i18nRaw`; processed by webUI I think)
https://source.chromium.org/chromium/chromium/src/+/main:docs/webui_explainer.md;l=157?q=%22$i18nRaw%22

2022-06-20 03:12 UTC, bsclifton commented
Pushed a minimal version of this. Curious what you think @goodov @iefremov @bridiver 

Basically, it works because Chromium already has a string `doNotTrackDialogMessage`. As @mkarolin pointed out, if that ever changes, this will just stop working. I couldn't find a better way to do this. The only other real solution would be to patch 
https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/resources/settings/privacy_page/do_not_track_toggle.html

and change `doNotTrackDialogMessage` to `braveDoNotTrackDialogMessage` (and then I can add the string as `braveDoNotTrackDialogMessage`)

This isn't the most important change in the world - but there are multiple text only issues tagged in our backlog and no real good way for folks (especially first time contributors) to solve. Would be good to have a strategy that choose - I'm happy to update https://github.com/brave/brave-browser/wiki/Patching-Chromium

2022-06-22 22:49 UTC, bsclifton commented
Going to close this out - I think there are bigger fish to fry 😛 But if any reviewers see this and have some input, still genuinely interested

2022-06-22 22:49 UTC, closed without merging