Brave 23367
brave/brave-core pull request #13732
Opened 2022-06-10 13:57 UTC by cypt4

Resolves 

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2022-06-13 17:15 UTC, yrliou commented on components/brave_wallet/browser/filecoin_keyring.cc
> +                                        : mojom::kFilecoinMainnet)
As mentioned in DM, please add comment here to explain why this is fine for now.

2022-06-13 17:15 UTC, yrliou approved these changes
LGTM

2022-06-13 17:56 UTC, Douglashdaniel requested changes
Can we update this line
https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/components/desktop/network-filter-selector/index.tsx#L94

to something like this
```
{/* Disabled Filecoin Submenu until testnetworks are enabled */}
{isTestNetworksEnabled && network.coin !== BraveWallet.CoinType.FIL &&
```

That away it will prevent this `Submenu` for `Filecoin` until test networks are supported.

![Screen Shot 2022-06-13 at 12 55 52 PM](https://user-images.githubusercontent.com/40611140/173415074-f0f0792d-c0e3-4765-803b-73073bc73dcf.png)

2022-06-13 19:31 UTC, Douglashdaniel approved these changes
LGTM

2022-06-13 20:17 UTC, merged

2022-06-14 09:53 UTC, srirambv commented
Still need to verify the transactions on mainnet. Should be ready for uplift once its done.