Brave translate android
brave/brave-core pull request #14283
Opened 2022-07-21 18:30 UTC by deeppandya

Resolves https://github.com/brave/brave-browser/issues/23770

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2022-07-21 18:31 UTC, AlexeyBarabash commented on build/android/bytecode/java/org/brave/bytecode/BraveTranslateCompactInfoBarBaseClassAdapter.java
> +/* Copyright (c) 2021 The Brave Authors. All rights reserved.
2022

2022-07-25 18:52 UTC, samartnik requested changes

2022-07-25 18:52 UTC, samartnik commented on android/java/org/chromium/chrome/browser/infobar/BraveTranslateCompactInfoBarBase.java
> +// Copyright 2022 The Chromium Authors. All rights reserved.
Should be our header

2022-07-25 18:52 UTC, samartnik commented on android/java/org/chromium/chrome/browser/infobar/BraveTranslateCompactInfoBarBase.java
> +}
nit: last empty line

2022-07-25 18:52 UTC, samartnik commented on build/android/bytecode/java/org/brave/bytecode/BraveTranslateCompactInfoBarBaseClassAdapter.java
> +}
nit: last empty line

2022-07-25 18:52 UTC, samartnik commented on android/java/org/chromium/chrome/browser/infobar/BraveTranslateCompactInfoBarBase.java
> +        super(R.drawable.ic_translate, 0, null, null);
I suppose we only need to change drawable if it's `infobar_translate_compact`, otherwise drawable shouldn't be changed.

2022-07-26 10:57 UTC, samartnik approved these changes
lgtm

2022-07-26 11:02 UTC, AlexeyBarabash approved these changes
++

You may squash d2309b491c40e0bebc3aab92e87d7815bbe7411e and 8437a0d85b1692d98b399fe0c254aaffd45bb635 to get cleaner PR structure.

2022-07-26 18:40 UTC, tapanmodh approved these changes
LGTM

2022-07-26 18:45 UTC, bridiver approved these changes
util.js changes are ok

2022-07-27 07:46 UTC, merged

2022-07-31 07:47 UTC, srirambv commented
Verification passed on Oppo Reno 5 with Android 12 running 1.44.10 x64 nightly build
- Verified Translate option in menu and bottom bar is shown correctly and icons are shown correctly in their inverted colour scheme

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/182015613-31ad0f97-ebef-4d4a-9ae0-d248727c6f99.png) | ![image](https://user-images.githubusercontent.com/17010094/182015619-8774d71e-7616-4be4-ab6a-731949bb366c.png)