omnibox brave search promo banner android
brave/brave-core pull request #14350
Opened 2022-07-27 07:21 UTC by tapanmodh

Resolves https://github.com/brave/brave-browser/issues/23062

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested] https://github.com/brave/security/issues/878 one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
- When a user types in the url bar, we will place a Brave Search banner at the bottom of the omnibox.
- When a user selects “Try Brave Search”, they will be taken to the Brave Search SERP with their intended query.
- Pressing “Maybe later” on the banner will hide the banner for the current session. On the next session, the banner will appear again but “Maybe later” will be replaced with “Dismiss”. If a user selects Dismiss, the banner won’t be displayed again.
- We will continue to show this banner until the user has made Brave Search their default search engine or 15 days
- On the Brave Search SERP, if a user pressed “Set Brave Search as default” the Brave search engine should be set as default

2022-07-27 15:14 UTC, samartnik requested changes

2022-07-27 15:14 UTC, samartnik commented on browser/ui/android/omnibox/java/src/org/chromium/chrome/browser/omnibox/suggestions/BraveAutocompleteCoordinator.java
> +                adapter.registerType(BraveOmniboxSuggestionUiType.BRAVE_SEARCH_PROMO_BANNER,
Apart form this the rest seems to be the copy of the parent. Can we extend `SuggestionListViewHolder` and get there to the `adapter` and register type in `BraveSuggestionListViewHolder`?

2022-07-27 15:14 UTC, samartnik commented on browser/ui/android/omnibox/java/src/org/chromium/chrome/browser/omnibox/suggestions/BraveDropdownItemViewInfoListBuilder.java
> +        mCalculatedSuggestionsHeight = calculatedSuggestionsHeight;
Once again seems to the only change we need, the rest is the copy of the parent. I would rather create a function `getCalculatedSuggestionsHeight` that would only copy relevant part of code.

2022-08-04 13:03 UTC, samartnik requested changes

2022-08-04 13:03 UTC, samartnik commented on browser/ui/android/omnibox/java/src/org/chromium/chrome/browser/omnibox/suggestions/BraveDropdownItemViewInfoListBuilder.java
> +        if (ChromeFeatureList.isEnabled("BraveSearchOmniboxBanner")
We should define feature name as constant instead of hardcoding.

2022-08-04 13:10 UTC, tapanmodh commented on android/javatests/org/chromium/chrome/browser/BytecodeTest.java
> +                "createViewProvider", false, null));
sure, will do it

2022-08-04 20:58 UTC, samartnik approved these changes
lgtm

2022-08-05 15:32 UTC, SergeyZhukovsky approved these changes
++

2022-08-08 17:48 UTC, mkarolin commented on chromium_src/chrome/browser/DEPS
> +  "+brave/components/brave_search_conversion",
Place in alphabetical order, please.

2022-08-08 17:49 UTC, mkarolin commented on chromium_src/chrome/browser/flags/android/chrome_feature_list.cc
> +    &brave_search_conversion::features::kOmniboxBanner,      \
Alphabetical order here as well, please.

2022-08-08 17:49 UTC, mkarolin approved these changes
`chromium_src` & `DEPS` LGTM with a couple of formatting nits.

2022-08-08 17:56 UTC, tmancey approved these changes
LGTM

2022-08-08 18:55 UTC, deeppandya approved these changes
LGTM

2022-08-09 04:53 UTC, merged

2022-08-29 20:53 UTC, kjozwiak commented
The new design that was discussed via Slack was verified by QA via https://github.com/brave/brave-core/pull/14778#issuecomment-1230750226 👍

2022-08-30 02:18 UTC, kjozwiak commented
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.45.9 Chromium: 105.0.5195.68 (Official Build) canary (32-bit)
--- | ---
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Android 12; Build/SP1A.210812.016
```

### `Test Case #1` (Supported Regions - US/CA/DE/FR/UK/AT/ES/MX)

* installed `1.45.9 Chromium: 105.0.5195.68`
* ensured that the system language is set to either `US`, `CA`, `DE`, `FR`, `UK`, `AT`, `ES` or `MX`
* launched brave and changed the default SE from `Brave` to anything else within the list (Google, DDG, Startpage etc..)
* added `--enable-features=BraveSearchOmniboxBanner` into `Command Line String` via `QA Preferences`
* re-launched the browser tapped on the URL bar and ensured that the Brave search promo is displayed via the omnibox
* ensured that the Brave search promo appears when tapping/editing a URL and the promo hasn't been closed/dismissed
* ensured that the Brave search promo doesn't appear if `Private` is set to another SE but `Standard` is still selected as `Brave`
* ensured that tapping on `Maybe Later` closes the promo within the omnibox and doesn't appear again within the session
  * ensured that it doesn't appear via the omnibox via NTP when starting to enter a URL/search term
  * ensured that tapping on a URL in an existing tab doesn't display the promo
* ensured that tapping on `Try Brave Search` opens `https://search.brave.com/search?q=motorsport&action=makeDefault`
  * ensured that the search term is also appended as per `search?q=motorsport`
  * ensured that tapping on `Try Brave Search` adds `action=makeDefault` into the URL

**`Canada`**

**`Example`** | **`Example`** | **`Example`** |  **`Example`** | **`Example`** | **`Example`** | **`Example`** 
---------------|-----------------|----------------|----------------|-----------------|----------------|---------------
![Screenshot_20220829-204621_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187326129-fe4323d7-ca5d-4b89-85c5-a3781bb7f468.jpg) | ![Screenshot_20220829-204655_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187326136-f5e36aea-e08a-486b-ad6c-a5fead8031e9.jpg) | ![Screenshot_20220829-204709_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187326150-21470833-0321-43b3-aa1b-89cd370cc3cc.jpg) | ![Screenshot_20220829-204724_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187326171-d49b4037-e25a-442f-b0fb-4a34b1e73012.jpg) | ![Screenshot_20220829-204757_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187326195-d3810dad-e73e-409e-a4bb-577ee2691476.jpg) | ![Screenshot_20220829-204803_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187326291-2a7a6d8c-680d-4e23-8f45-d84c20b565f2.jpg) | ![Screenshot_20220829-205138_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187326345-227ea197-4d2c-4e1e-8f30-117f7d055751.jpg)

**`Mexico`**

**`Example`** | **`Example`** | **`Example`** |  **`Example`** | **`Example`** | **`Example`** | **`Example`** 
---------------|-----------------|----------------|----------------|-----------------|----------------|---------------
![Screenshot_20220829-211940_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187333745-12f143fd-f899-47ec-9b27-fb22dc0edcea.jpg) | ![Screenshot_20220829-212009_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187333749-b556d0a5-c902-4545-8326-0b6db01a8265.jpg) | ![Screenshot_20220829-212023_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187333752-875d49e6-d1fb-4e85-adb4-550f1263b242.jpg) | ![Screenshot_20220829-212107_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187333755-f8f2d255-5a46-4dda-ba8f-61b3f2fded5a.jpg) | ![Screenshot_20220829-214051_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187333758-71f915b9-5eb1-4f9d-a19b-12efac32e162.jpg) | ![Screenshot_20220829-214058_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187333763-58069858-6f19-4421-a8e9-5f447915ec1d.jpg) | ![Screenshot_20220829-214147_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187333770-106d10de-24b0-447b-ba3b-b2486363af3f.jpg)

### `Test Case #2` (Regions that don't have Brave Search as default SE/Still use SE onboarding)

* installed `1.45.9 Chromium: 105.0.5195.68`
* ensured that the system language is set to the correct locale (in this case, either `Japan` or `Poland`)
* launched brave and added `--enable-features=BraveSearchOmniboxBanner` into `Command Line String` via `QA Preferences`
* re-launched the browser tapped on the URL bar twice and ensured that the SE onboarding screen is displayed
* ensured that Google was selected as the default via the onboarding screen
* ensured that Google is default SE for both `Standard` & `Private` windows once the onboarding screen has been dismissed
* ensured that the Brave search promo isn't appearing via the omnibox when a text/search term is entered

**`Japan`**

**`Example`** | **`Example`** | **`Example`** |  **`Example`**
---------------|-----------------|----------------|----------------
![Screenshot_20220829-170533_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187321333-a6bd64e0-3ae1-4bae-8515-efecce6bff3d.jpg) | ![Screenshot_20220829-170545_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187321355-f251ecc6-7600-44c6-9458-1c7d47d902b9.jpg) | ![Screenshot_20220829-170345_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187321365-5eb60e6a-a857-47db-b347-f8a084cbca45.jpg) | ![Screenshot_20220829-170408_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187321369-8521bce8-348e-4767-a557-5a60c8371a16.jpg)

**`Poland`**

**`Example`** | **`Example`** | **`Example`** |  **`Example`**
---------------|-----------------|----------------|----------------
![Screenshot_20220829-171448_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187321549-805c46e5-13a2-4ca6-977b-4b957dd01d0d.jpg) | ![Screenshot_20220829-171502_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187321564-7d22dbfa-f6fb-4d92-b1b4-8f19fc13c24a.jpg) | ![Screenshot_20220829-202358_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187321591-68968339-1f04-4e44-84b8-8d8683aab4a8.jpg) | ![Screenshot_20220829-171510_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187321598-a1b56de2-6dc5-4caf-967f-ba9a4d8a944c.jpg)

2022-08-30 02:42 UTC, kjozwiak commented
Also found https://github.com/brave/brave-browser/issues/25059 while running through the above cases.