feat(wallet): add transaction review screen for ETHSwap
brave/brave-core pull request #14745
Opened 2022-08-22 20:57 UTC by onyb

Resolves https://github.com/brave/brave-browser/issues/24860

Slight design variations from the Figma spec were done after internal discussions with product/design.

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Demo:

https://user-images.githubusercontent.com/3684187/186016130-02361dec-8a20-40e2-87b9-86a39d20ccf5.mov

## Test plan

Create a swap transaction on Ethereum mainnet network for the following cases, and it should accurately display the maker/taker assets and amounts involved in the swap.
- `ETH  -> ERC20`
- `ERC20 -> ETH`
- `ERC20 -> ERC20`

Verify in the screenshot that the correct asset logos and the corresponding network are appropriately displayed.

2022-08-22 22:01 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/f/wallet/swap-review-screen/80cba349bf97fc8aab17ce0d92efed3251c29918/storybook/index.html)

2022-08-23 10:13 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/f/wallet/swap-review-screen/1a1330d385ba557d9ba152ee3dcfe5e9bcdb708e/storybook/index.html)

2022-08-23 15:03 UTC, Douglashdaniel requested changes

2022-08-23 15:03 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/extension/confirm-transaction-panel/swap.tsx
> +import * as React from 'react'
License!

2022-08-23 15:03 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/extension/confirm-transaction-panel/swap.tsx
> +  }, [networks])
Missing `transactionDetails` dependency!

2022-08-23 15:03 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/extension/confirm-transaction-panel/swap.tsx
> +  }, [networks])
Missing `transactionDetails` dependency!

2022-08-23 16:02 UTC, onyb commented on components/brave_wallet_ui/components/extension/confirm-transaction-panel/common/style.tsx
> +}
Good idea! Fixed it.

2022-08-23 16:10 UTC, Douglashdaniel approved these changes
LGTM!

2022-08-23 17:13 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/f/wallet/swap-review-screen/d8b3a5c6ee58e8e00f94a73a904b8ef7ff055f01/storybook/index.html)

2022-08-24 09:07 UTC, merged