Various balance fixes for FIL
brave/brave-core pull request #14912
Opened 2022-08-31 08:33 UTC by cypt4

Resolves https://github.com/brave/brave-browser/issues/24947
1) Changed calibration api url
2) Fixed a bug when balance was not loading for mainnet if wallet opened with selected testnet acc.
3) When open account info for filecoin only supported networks are showing for now(mainnet for f* and testnet\localhost for t*).

Resolves 

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2022-09-01 02:21 UTC, supermassive commented on components/brave_wallet_ui/common/async/lib.ts
> +  if (network.coin !== CoinType.FIL) {
BraveWallet.CoinType.FIL and no need in import above

2022-09-01 14:41 UTC, Douglashdaniel requested changes

2022-09-01 14:41 UTC, Douglashdaniel commented on components/brave_wallet_ui/common/async/lib.ts
> +export function getFilecoinKeyringIdFromNetwork (network: BraveWallet.NetworkInfo) {
Can we move this method to `brave_wallet_ui/utils/network-utils.ts` along with a unit test?

2022-09-05 15:45 UTC, Douglashdaniel requested changes

2022-09-05 15:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/views/accounts/account.tsx
> +import { CoinType } from 'gen/brave/components/brave_wallet/common/brave_wallet.mojom.m'
Since we already have the `BraveWallet` type imported in this file, let's remove this import and use `BraveWallet.CoinType.FIL` 😎

2022-09-05 15:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/utils/network-utils.test.ts
> +import { CoinType } from 'gen/brave/components/brave_wallet/common/brave_wallet.mojom.m'
Same here!

2022-09-07 19:25 UTC, Douglashdaniel approved these changes
++ Front-end

2022-09-08 10:30 UTC, supermassive approved these changes

2022-09-08 12:45 UTC, merged