Quick action widget
brave/brave-core pull request #15064
Opened 2022-09-12 04:08 UTC by deeppandya

Resolves 

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2022-09-29 21:55 UTC, deeppandya commented
Need to remove gain metadata files as it's not needed.

2022-09-29 22:11 UTC, samartnik requested changes

2022-09-29 22:11 UTC, samartnik commented on patches/chrome-android-java-src-org-chromium-chrome-browser-quickactionsearchwidget-QuickActionSearchWidgetProvider.java.patch
> ++            setWidgetEnabled(false, false);
I believe we can change method owner for `setWidgetEnabled` and replace values there.

2022-09-29 22:11 UTC, samartnik commented on third_party/gson/BUILD.gn
> +java_prebuilt("gson_java") {
Not sure how justified adding this lib for such a small class. It seems to me that adding own `toJson` and `fromJson` are more preferable. At least Chromium team goes this way.

2022-09-29 22:11 UTC, samartnik commented on patches/chrome-android-java-AndroidManifest.xml.patch
> ++            android:enabled="false"
Don't we disable it in a runtime in `setWidgetEnabled`?

2022-09-29 22:11 UTC, samartnik commented on android/java/org/chromium/chrome/browser/widget/quickactionsearchandbookmark/QuickActionSearchAndBookmarkWidgetProvider.java
> +/* Copyright (c) 2020 The Brave Authors. All rights reserved.
nit: 2022

2022-09-29 22:11 UTC, samartnik commented on android/java/org/chromium/chrome/browser/widget/quickactionsearchandbookmark/promo/SearchWidgetPromoPanel.java
> +  Copyright (c) 2021 The Brave Authors. All rights reserved.
nit: 2022

2022-09-29 22:11 UTC, samartnik commented on android/java/org/chromium/chrome/browser/widget/quickactionsearchandbookmark/utils/BraveSearchWidgetUtils.java
> +  Copyright (c) 2021 The Brave Authors. All rights reserved.
nit: 2022

2022-09-29 22:11 UTC, samartnik commented on android/java/org/chromium/chrome/browser/widget/quickactionsearchandbookmark/utils/BraveSearchWidgetUtils.java
> +}
nit: last empty line

2022-09-29 22:11 UTC, samartnik commented on android/java/res/layout/layout_search_widget_promo.xml
> +<!-- Copyright (c) 2020 The Brave Authors. All rights reserved.
nit: 2022

2022-09-29 22:11 UTC, samartnik commented on android/java/res/layout/quick_action_search_and_bookmark_widget_layout.xml
> +<!--* Copyright (c) 2020 The Brave Authors. All rights reserved.
nit: 2022

2022-09-29 22:11 UTC, samartnik commented on android/java/res/layout/layout_search_widget_promo.xml
> +</FrameLayout>
nit: last empty line

2022-10-28 16:32 UTC, samartnik requested changes

2022-10-28 16:32 UTC, samartnik commented on android/java/org/chromium/chrome/browser/widget/quickactionsearchandbookmark/BraveQuickActionSearchWidgetProvider.java
> +// Copyright 2022 The Chromium Authors. All rights reserved.
Please use our header with Mozilla v2 lincense

2022-10-28 16:32 UTC, samartnik commented on android/java/org/chromium/chrome/browser/widget/quickactionsearchandbookmark/QuickActionSearchAndBookmarkWidgetProvider.java
> +     *to fetch the data. Also, any modification to the data should be done through this class.
nit: space

2022-10-28 16:32 UTC, samartnik commented on android/java/org/chromium/chrome/browser/widget/quickactionsearchandbookmark/promo/SearchWidgetPromoPanel.java
> +  Copyright (c) 2021 The Brave Authors. All rights reserved.
It's still 2021 :)

2022-10-28 16:32 UTC, samartnik commented on android/java/res/layout/bookmark_widget.xml
> +<!-- Copyright 2015 The Chromium Authors. All rights reserved.
We should use our header

2022-10-28 16:32 UTC, samartnik commented on android/java/res/layout/bookmark_widget_item.xml
> +<!-- Copyright 2022 The Chromium Authors. All rights reserved.
Should be our header

2022-11-01 20:07 UTC, samartnik approved these changes
lgtm

2022-11-01 20:23 UTC, mkarolin approved these changes
`patches` ++

2022-11-02 22:59 UTC, merged

2025-04-25 02:06 UTC, AndyAnds265 commented
@deeppandya, any chance you could add a screenshot to this string?
        try_brave_search_widget