feat(wallet): Edit Visible Assets Network Selector
brave/brave-core pull request #15519
Opened 2022-10-18 22:31 UTC by Douglashdaniel

## Description 
- Adds the ability to filter the `Edit Visible Assets` by `network`
- Introduces `tokenRegistry` in our redux store that we can start to migrate to, to help with performance.

Resolves <https://github.com/brave/brave-browser/issues/23675>
Resolves <https://github.com/brave/brave-browser/issues/21770>

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

https://user-images.githubusercontent.com/40611140/196556853-83890347-f6de-40c0-bd90-b7037b4663f9.mov

2022-10-18 23:40 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/feat-edit-visible-asset-network-selector/287a7d946b1a6e18ce90088cf33fafa2aad7b2de/storybook/index.html)

2022-10-19 05:25 UTC, onyb reviewed
Is it useful to have an "All networks" option for Visible Assets modal? The default network in the dropdown should be the currently selected network.

2022-10-19 14:42 UTC, Douglashdaniel commented
> Is it useful to have an "All networks" option for Visible Assets modal? The default network in the dropdown should be the currently selected network.

@onyb This was discussed/decided internally, we are working on getting away from having a global `Selected Network` in the wallet.

2022-10-19 19:48 UTC, josheleonard requested changes
We should also request this list directly from core to remove the need to store it in redux.

2022-10-20 18:05 UTC, Douglashdaniel commented on components/brave_wallet_ui/common/actions/wallet_actions.ts
> +export const setTokenRegistery = createAction<SetTokenRegistryType>('setTokenRegistery')
This has been Removed!

2022-10-20 18:06 UTC, Douglashdaniel commented on components/brave_wallet_ui/common/async/handlers.ts
> +    const formatedList = list.tokens.map((token) => {
This has been removed!

2022-10-20 20:17 UTC, josheleonard requested changes

2022-10-20 20:48 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/feat-edit-visible-asset-network-selector/4abc5d9713651ee9d19696ee92dd067c6d193d5a/storybook/index.html)

2022-10-20 21:15 UTC, Douglashdaniel commented on components/brave_wallet_ui/common/hooks/useTokenRegistry.tsx
> +  const isMounted = useIsMounted()
Done!

2022-10-20 21:15 UTC, Douglashdaniel commented on components/brave_wallet_ui/common/hooks/useTokenRegistry.tsx
> +            setTokenRegistry(registry)
Done!

2022-10-20 21:15 UTC, Douglashdaniel commented on components/brave_wallet_ui/common/hooks/useTokenRegistry.tsx
> +  // Hook State
Moved!

2022-10-20 21:46 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/feat-edit-visible-asset-network-selector/7a2f9f2508c5420b29a1f309556c61ed5d259788/storybook/index.html)

2022-10-21 02:23 UTC, merged