Limit CopyLinkWithStrictCleaning by http(s) urls
brave/brave-core pull request #15650
Opened 2022-10-25 08:40 UTC by spylogsster

Resolves https://github.com/brave/brave-browser/issues/26236

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

- Check `Copy clean link` item with http(s) links and others

2022-10-25 09:17 UTC, goodov approved these changes

2022-10-25 18:24 UTC, fmarier commented on chromium_src/chrome/browser/renderer_context_menu/render_view_context_menu.cc
> +  if (!params_.link_url.is_empty() && params_.link_url.SchemeIsHTTPOrHTTPS()) {
I've added a new section on https://fmarier.github.io/brave-testing/copy-clean-link.html to test this.

2022-10-25 18:37 UTC, spylogsster commented on chromium_src/chrome/browser/renderer_context_menu/render_view_context_menu.cc
> +  if (!params_.link_url.is_empty() && params_.link_url.SchemeIsHTTPOrHTTPS()) {
this covers only renderer context menu

2022-10-25 18:46 UTC, spylogsster commented on chromium_src/chrome/browser/renderer_context_menu/render_view_context_menu.cc
> +  if (!params_.link_url.is_empty() && params_.link_url.SchemeIsHTTPOrHTTPS()) {
<img width="431" alt="image" src="https://user-images.githubusercontent.com/2965009/197856506-bae8847b-b5ca-46f9-88b2-9fc5b8692fc4.png">

2022-10-25 18:51 UTC, fmarier requested changes
> this covers only renderer context menu

If it's easy to do in the other context menus, it would be good to do it there too.

Also, I'd suggest putting an early return in `SanitizeURL()` if a URL with a non-HTTP / non-HTTPS scheme is encountered. In these cases, just returning the original URL.

2022-10-26 07:51 UTC, spylogsster commented
> > this covers only renderer context menu
> 
> If it's easy to do in the other context menus, it would be good to do it there too.
> 
> Also, I'd suggest putting an early return in `SanitizeURL()` if a URL with a non-HTTP / non-HTTPS scheme is encountered. In these cases, just returning the original URL.

done

2022-10-26 17:55 UTC, fmarier approved these changes
Thanks for the comprehensive change and the tests!

2022-10-26 17:56 UTC, merged