feat(wallet): ENS Off Chain Lookup in New Send Tab
brave/brave-core pull request #16215
Opened 2022-12-02 21:28 UTC by Douglashdaniel

## Description 
Implemented `ENS Off Chain Lookup` for the new `Send` tab

Resolves <https://github.com/brave/brave-browser/issues/27109>

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

### Testing Ethereum
1. Go to brave://settings/extensions and make sure `Allow ENS offchain lookup` is set to `Ask`
2. Go to brave://wallet/send, choose a token on the `Ethereum` network and paste in `offchainexample.eth`
3. You should see the `ENS Offchain` message
4. Make sure the `Learn more` link routes to https://github.com/brave/brave-browser/wiki/ENS-offchain-lookup
5. Click on the `Use ENS domain` button
6. The `Message` should disappear and resolve the address.

https://user-images.githubusercontent.com/40611140/205388786-3d0d5909-d061-49f9-9563-877a48510ca4.mov

2022-12-02 22:39 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/feat-wallet-ens-offchain-new-send-tab/acd66f8e9e0a333d2eda73e52a95cf70e7c802fc/storybook/index.html)

2022-12-05 21:30 UTC, josheleonard requested changes

2022-12-14 17:40 UTC, darkdh approved these changes

2022-12-14 21:00 UTC, Douglashdaniel commented on components/brave_wallet_ui/common/hooks/send.ts
> +    setShowEnsOffchainLookupOptions,
Is now wrapped in a `useCallback` hook!

2022-12-14 21:01 UTC, Douglashdaniel commented on components/brave_wallet_ui/page/screens/send/components/address-message/address-message.style.ts
> +export const LearnMoreButton = styled.a`
Updated!

2022-12-14 21:01 UTC, Douglashdaniel commented on components/brave_wallet_ui/page/screens/send/send/send.tsx
> +      (addressWarning !== undefined && addressWarning !== '')
Updated!

2022-12-14 21:01 UTC, Douglashdaniel commented on components/brave_wallet_ui/page/screens/send/send/send.tsx
> +      }
Moved to `send-ui-messages.ts` file!

2022-12-14 21:50 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/feat-wallet-ens-offchain-new-send-tab/55a19270eafdd4e62d677c9518d41eb2c838b0f6/storybook/index.html)

2022-12-14 22:10 UTC, josheleonard approved these changes
++

2022-12-14 23:46 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/feat-wallet-ens-offchain-new-send-tab/9df48856f30d52a2d97a5e41fd243dcf20bb95b8/storybook/index.html)

2022-12-15 01:36 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/feat-wallet-ens-offchain-new-send-tab/41dfe3e2ca101d08708a3aabe6ffcb3e12c43abb/storybook/index.html)

2022-12-15 16:33 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/feat-wallet-ens-offchain-new-send-tab/2c8194e97cd41d290880de3126e259dc8a755058/storybook/index.html)

2022-12-15 18:58 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/feat-wallet-ens-offchain-new-send-tab/f6fbafd2c9a28a22e4fd8c4c4051deee0058097d/storybook/index.html)

2022-12-15 20:39 UTC, merged