Fixed TrustedScriptURL assignment error in vpn panel
brave/brave-core pull request #16976
Opened 2023-02-02 04:17 UTC by simonhong

fix https://github.com/brave/brave-browser/issues/28181

Resolves 

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2023-02-02 04:34 UTC, simonhong commented on components/brave_vpn/resources/panel/components/flag/index.tsx
> +        <img src={staticUrlPolicy.createScriptURL()} />
This gives below error.
` TS2322: Type 'TrustedScriptURL' is not assignable to type 'string'.`

2023-02-02 11:02 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/vpn_panel_trusted_types/b499a983597c8fd3b063b58c7d3c61fdbac197ef/storybook/index.html)

2023-02-02 23:43 UTC, nullhook requested changes
I've been wanting to transfer the icons to the C++ side.

Thanks for doing this.

2023-02-02 23:43 UTC, nullhook commented on components/brave_vpn/resources/panel/components/flag/index.tsx
>      let canceled = false
We can get rid of `canceled` variable completely. This was useful for async operations.

2023-02-02 23:43 UTC, nullhook commented on components/brave_vpn/resources/panel/components/flag/index.tsx
>      if (COUNTRIES.includes(props?.countryCode ?? '') && !canceled) {
This can be simplified:

```javascript
if (COUNTRIES.includes(props?.countryCode)) {}
```

2023-02-02 23:43 UTC, nullhook commented on components/brave_vpn/resources/panel/components/flag/index.tsx
> +  let [url, setUrl] = React.useState('')
An empty string? We should keep `undefined` here.

2023-02-02 23:43 UTC, nullhook commented on components/brave_vpn/resources/panel/components/flag/index.tsx
> +  let [url, setUrl] = React.useState('')
Also, make this `const`

2023-02-02 23:43 UTC, nullhook commented on components/brave_vpn/resources/panel/components/flag/index.tsx
> +  if (url !== '') {
This can be refactored

```javascript
return !url ? null : (
  <IconBox>
    <img src={url} />
  </IconBox>
);
```

2023-02-02 23:43 UTC, nullhook commented on components/brave_vpn/resources/panel/components/flag/index.tsx
>  const COUNTRIES = ['GB', 'US', 'CH', 'ES', 'SG', 'NL', 'JP', 'DE', 'FR', 'CA', 'AU']
Let's order this alphabetically which matches the list in the grd file

```javascript
const COUNTRIES = [
  'AU', 'CA', 'CH', 'DE', 'ES', 'FR', 'GB', 'JP', 'NL', 'SG', 'US'
];
```

`

2023-02-02 23:45 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/vpn_panel_trusted_types/f24311fae3c7a39272a0b96d878fdecfe3fd2fae/storybook/index.html)

2023-02-03 00:18 UTC, simonhong commented
@nullhook Thanks for review! All addressed at https://github.com/brave/brave-core/pull/16976/commits/c294214a4afff26cde7e37019d6efc8ec48a3832 PTAL again.

2023-02-03 00:57 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/vpn_panel_trusted_types/c294214a4afff26cde7e37019d6efc8ec48a3832/storybook/index.html)

2023-02-03 03:18 UTC, nullhook approved these changes
lgtm

2023-02-03 04:23 UTC, merged

2023-02-03 04:56 UTC, petemill reviewed
nice work!

2023-02-04 06:18 UTC, stephendonner commented
## Verified `PASSED` using 

Brave | 1.50.7 Chromium: 110.0.5481.77 (Official Build) nightly (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

`Light` | `Dark`
--------|-------
<img width="1247" alt="Screen Shot 2023-02-03 at 10 16 48 PM" src="https://user-images.githubusercontent.com/387249/216752412-7a9be8dd-97be-44d5-8f9e-e181cc65318a.png"> | <img width="1247" alt="Screen Shot 2023-02-03 at 10 16 27 PM" src="https://user-images.githubusercontent.com/387249/216752421-35413962-f992-4676-bed6-ec634c3ff8b2.png">