feat(wallet) Add NFT Pinning
brave/brave-core pull request #16998
Opened 2023-02-02 15:00 UTC by muliswilliam

Resolves https://github.com/brave/brave-browser/issues/26828

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
TBA

2023-02-02 18:25 UTC, yrliou commented
@muliswilliam @cypt4 just a friendly note that nothing should be accessible/triggered without enabling the feature flag, and please open a security & privacy issue to prepare for enabling the feature flag linking to this PR and the core PR, thanks.

2023-02-06 23:45 UTC, Douglashdaniel requested changes

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/common/hooks/nft-pin.ts
> +  }, [isNftPinningFeatureEnabled, userVisibleTokensInfo])
Missing `isTokenPinningSupported` dependancy.

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/common/hooks/nft-pin.ts
> +// you can obtain one at https://mozilla.org/MPL/2.0/.
Update to `2023` and capitalize `You`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/inspect-nfts/components/info-tooltip/info-tooltip.style.ts
> +// you can obtain one at https://mozilla.org/MPL/2.0/.
Update to `2023` and capitalize `You`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/inspect-nfts/components/info-tooltip/info-tooltip.tsx
> +// you can obtain one at https://mozilla.org/MPL/2.0/.
Update to `2023` and capitalize `You`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/inspect-nfts/components/nft-list/nft-list.styles.ts
> +// you can obtain one at https://mozilla.org/MPL/2.0/.
Update to `2023` and capitalize `You`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/inspect-nfts/components/nft-list/nft-list.tsx
> +// you can obtain one at https://mozilla.org/MPL/2.0/.
Update to `2023` and capitalize `You`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/inspect-nfts/inspect-nfts.tsx
> +// you can obtain one at https://mozilla.org/MPL/2.0/.
Update to `2023` and capitalize `You`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/inspect-nfts/inspect-nfts.tsx
> +
Can we add a `// methods` comment?

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/inspect-nfts/inspects-nfts.styles.ts
> +// you can obtain one at https://mozilla.org/MPL/2.0/.
Update to `2023` and capitalize `You`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/inspect-nfts/inspects-nfts.styles.ts
> +  color: #AEB1C2;
Do we have a `theme` variable for this? if not should we add a `(prefers-color-scheme: dark)` here?

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/inspect-nfts/inspects-nfts.styles.ts
> +  background-color: rgba(233, 233, 244, 0.3);
Do we have a `theme` variable for this? if not should we add a `(prefers-color-scheme: dark)` here?

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/inspect-nfts/components/info-tooltip/info-tooltip.style.ts
> +  border-bottom: 8px solid #1E2029;
Do we have a `theme` variable for this? if not should we add a `(prefers-color-scheme: dark)` here?

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/inspect-nfts/components/info-tooltip/info-tooltip.style.ts
> +  background-color: #1E2029;
Do we have a `theme` variable for this? if not should we add a `(prefers-color-scheme: dark)` here?

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/local-ipfs-node/local-ipfs-node.styles.ts
> +// you can obtain one at https://mozilla.org/MPL/2.0/.
Update to `2023` and capitalize `You`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/local-ipfs-node/local-ipfs-node.tsx
> +// you can obtain one at https://mozilla.org/MPL/2.0/.
Update to `2023` and capitalize `You`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/local-ipfs-node/local-ipfs-node.tsx
> +
Can we add a `// methods` comment here?

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/nft-ipfs-banner/nft-ipfs-banner.style.ts
> +// you can obtain one at https://mozilla.org/MPL/2.0/.
Update to `2023` and capitalize `You`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/nft-ipfs-banner/nft-ipfs-banner.tsx
> +// you can obtain one at https://mozilla.org/MPL/2.0/.
Update to `2023` and capitalize `You`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/nft-ipfs-banner/nft-ipfs-banner.tsx
> +
Can we add a `// redux` comment here?

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/nft-ipfs-banner/nft-ipfs-banner.tsx
> +
Can we add a `// memos` comment here?

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/nft-ipfs-banner/nft-ipfs-banner.tsx
> +
Can we add a `// methods` comment here?

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/nft-pinning-status-animation/nft-pinning-status-animation.style.ts
> +// you can obtain one at https://mozilla.org/MPL/2.0/.
Capitalize `You`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/nft-pinning-status-animation/nft-pinning-status-animation.tsx
> +// you can obtain one at https://mozilla.org/MPL/2.0/.
Capitalize `You`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/nft-pinning-status/nft-pinning-status.style.ts
> +// you can obtain one at https://mozilla.org/MPL/2.0/.
Update to `2023` and capitalize `You`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/nft-pinning-status/nft-pinning-status.style.ts
> +      return 'rgba(213, 245, 218, 1)'
Do these need `dark-mode` theming?

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/nft-pinning-status/nft-pinning-status.style.ts
> +  background-color: #FEBF17;
Same here?

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/nft-pinning-status/nft-pinning-status.style.ts
> +  background-color: #E32444;
Same here?

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/nft-pinning-status/nft-pinning-status.style.ts
> +  background-color: #4DC661;
Same here?

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/nft-pinning-status/nft-pinning-status.tsx
> +// you can obtain one at https://mozilla.org/MPL/2.0/.
Update to `2023` and capitalize `You`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/nft-pinning-status/nft-pinning-status.tsx
> +  const [icon, setIcon] = React.useState<React.ReactNode>()
`// state`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/nft-pinning-status/nft-pinning-status.tsx
> +
`// effects`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/views/crypto/index.tsx
> +  }, [])
Missing `location.key` dependency.

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/views/nfts/components/nfts.styles.tsx
> +    background-color: #469EA2;
does this need `dark-mode` theming?

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/views/nfts/components/nfts.tsx
> +  }, [])
Missing `onToggleShowIpfsBanner` dependency.

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/views/nfts/nft-view.tsx
>    }, [userVisibleTokensInfo, selectedNetworkFilter])
`selectednetworkFilter.chaindId`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/views/portfolio/components/ipfs-node-status/ipfs-node-status.style.ts
> +// you can obtain one at https://mozilla.org/MPL/2.0/.
Update to 2023 and capitalize You

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/views/portfolio/components/ipfs-node-status/ipfs-node-status.tsx
> +// you can obtain one at https://mozilla.org/MPL/2.0/.
Update to 2023 and capitalize You

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/shared/nft-icon/nft-icon-with-network-icon.tsx
> +// you can obtain one at https://mozilla.org/MPL/2.0/.
Update to `2023` and capitalize `You`

2023-02-06 23:45 UTC, Douglashdaniel commented on components/brave_wallet_ui/nft/components/nft-details/nft-details-styles.ts
> +  border: 1px solid rgba(174, 177, 194, 0.55);
Does this need `dark-mode` theming?

2023-02-09 05:56 UTC, Douglashdaniel approved these changes
Looks good to me!
Nice work! 🔥

2023-02-09 18:07 UTC, cypt4 approved these changes
LGTM

2023-02-09 18:07 UTC, cypt4 commented on components/brave_wallet_ui/components/desktop/views/portfolio/components/token-lists/token-list.tsx
> +                             userAssetList,
Do we need this changes?

2023-02-09 20:15 UTC, stoletheminerals approved these changes
It's ok to be merged since it's behind a feature flag. The review is still in process, so we shouldn't enable the feature by default

2023-02-10 09:54 UTC, merged