feat(wallet): NFT Pinning design updates
brave/brave-core pull request #17557
Opened 2023-03-10 15:15 UTC by muliswilliam

Resolves https://github.com/brave/brave-browser/issues/28986

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2023-03-15 05:13 UTC, Douglashdaniel requested changes

2023-03-15 05:13 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/nft-ipfs-banner/nft-ipfs-banner.style.ts
>        : getSuccessBackground()};
```suggestion
--success-background: #E8F9EB;
--uploading-background: #F0F7FC;
@media (prefers-color-scheme: dark) {
    --success-background: #15371B;
    --uploading-background: #E8F9EB;
}
background: ${(p) =>
  p.status === 'start'
    ? `url(${BannerBackground}) right 80px center/contain no-repeat, #1A1C3B`
    : p.status === 'uploading'
    ? var(--uploading-background)
    : var(--success-background)};
```

2023-03-15 05:13 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/nft-ipfs-banner/nft-ipfs-banner.style.ts
>  }
Can remove these!

2023-03-15 05:13 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/nft-ipfs-banner/nft-ipfs-banner.style.ts
> +  color: ${(p) => (p.status === 'start' ? p.theme.palette.white : window.matchMedia('(prefers-color-scheme: dark)').matches ? '#ECEFF2' : '#1D1F25')};
```suggestion
--text-color: #1D1F25;
@media (prefers-color-scheme: dark) {
  --text-color: #ECEFF2;
}
color: ${(p) => p.status === 'start' ? p.theme.palette.white : var(--text-color)};
```

2023-03-15 07:04 UTC, muliswilliam commented on components/brave_wallet_ui/components/desktop/nft-ipfs-banner/nft-ipfs-banner.style.ts
>  }
Great regactor. Done here 37843dd9ab7d9e3180cec056c996588accc674aa

2023-03-15 14:53 UTC, Douglashdaniel approved these changes
++

2023-03-16 12:52 UTC, cypt4 approved these changes
LGTM

2023-03-16 12:52 UTC, cypt4 commented on components/resources/wallet_strings.grdp
> +
nit: unnecessary diff

2023-03-16 12:52 UTC, cypt4 commented on components/brave_wallet_ui/stories/locale.ts
>    braveWalletNftPinningBannerUploading: 'You\’re running IPFS node. File is being uploaded to IPFS.',
nit: this string doesn't reflect grdp content

2023-04-03 12:15 UTC, merged

2023-04-05 06:34 UTC, srirambv commented
Verification passed on

Brave | 1.52.17 Chromium: 112.0.5615.49 (Official Build) nightly (64-bit)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Windows 11 Version 22H2 (Build 22621.1485)

<details>
<summary><b>Verified <code>https://github.com/brave/brave-browser/issues/28986</code> - Passed</b></summary>
<br>

- Verified UI updates to NFT pinning

Banner Main

Light | Dark
-- | --
![brave_tuT7Bm5VMZ](https://user-images.githubusercontent.com/17010094/229998111-7d80b6ee-0f92-4709-ad2a-925bf5ebf07b.png) | ![brave_MdPuCWPAYz](https://user-images.githubusercontent.com/17010094/229999466-7ca18bf3-2048-4fe2-9574-eb331b127eee.png)



Banner Uploading

Light | Dark
-- | --
![brave_cyCKAfDNug](https://user-images.githubusercontent.com/17010094/229996825-a39462d6-acde-44ee-9e44-65ca454ff111.png) | ![brave_5Z1OLXJKyy](https://user-images.githubusercontent.com/17010094/229996892-2cf7f7b3-08d7-4511-a9dc-54a605c37e89.png)

Banner Success

Light | Dark
-- | --
![brave_qf4NWwjD5s](https://user-images.githubusercontent.com/17010094/229997440-acb1697f-2ceb-4387-8538-e1a65a6f410f.png) | ![brave_G8cqjvrWks](https://user-images.githubusercontent.com/17010094/229997382-70743d60-f7ea-4285-add4-612bd5952c72.png)

NFT-IPFS Interstitial page

Light | Dark 
-- | --
![brave_vdgdqJKbb3](https://user-images.githubusercontent.com/17010094/229999593-04b82954-59c4-4381-93df-40802ff7b2f9.png) | ![brave_9GdezdpiIy](https://user-images.githubusercontent.com/17010094/229999632-5f09684d-5dbd-4fc9-a3e7-370992292cf2.png)


NFT-IPFS Interstitial page (Available NFT pins)

Light | Dark 
-- | --
![brave_PcJrf46XWv](https://user-images.githubusercontent.com/17010094/229999702-18042cd1-2956-465d-906e-49b4c29711c8.png) | ![brave_9S64hbHT3L](https://user-images.githubusercontent.com/17010094/229999664-abfa6a1b-d5f5-4bf7-b955-d5bebadf69c2.png)

NFT Details page

Light | Dark 
-- | --
![brave_QnBnNMUTl9](https://user-images.githubusercontent.com/17010094/229997803-0de46bd1-e80b-45bf-8e98-a2db24a6817c.png) | ![brave_PwLjGxxoxG](https://user-images.githubusercontent.com/17010094/229997797-5638d993-5620-4add-a299-03b99cf2e941.png)

- Encountered [brave-browser#29514](https://github.com/brave/brave-browser/issues/29514)
</details>
<details>
<summary><b>Verified <code>https://github.com/brave/brave-browser/issues/29009</code> - Passed</b></summary>
<br>

- Verified NFT-IPFS Icon is always shown 
- Verified on hover changes the button colour
- Verified still able to click the button to show/hide the message
- Verified button visibility on both dark and light theme

https://user-images.githubusercontent.com/17010094/229984412-c427c9cc-70f2-417a-bead-aaef3fde0d4a.mp4

</details>