Wip ipns gateway
brave/brave-core pull request #17585
Opened 2023-03-13 18:19 UTC by cypt4

Resolves 

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2023-03-19 19:23 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/brave_28407/84bc0352a3850650db31ab0826b9c829df4ce44e/storybook/index.html)

2023-03-20 09:50 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/brave_28407/67b4f172b9736e72cc94b8c712d9b7aaa9b7a934/storybook/index.html)

2023-03-24 19:56 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/brave_28407/ea3f9578c3574acd6b3fdae1830e683e0f62212f/storybook/index.html)

2023-03-24 20:33 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/brave_28407/dbe89454c6181307bf082bbd367d66c67b4332ac/storybook/index.html)

2023-03-24 21:22 UTC, josheleonard requested changes

2023-03-24 21:22 UTC, josheleonard commented on components/brave_wallet_ui/common/async/lib.ts
> +  return true
```suggestion
  return results.some(result => result.startsWith(IPFS_PROTOCOL))
```

2023-03-30 19:17 UTC, yrliou approved these changes
core++

2023-03-30 19:55 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/brave_28407/a04507eca5ac59d32472c482b90f383dc85bf285/storybook/index.html)

2023-03-31 10:16 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/brave_28407/4280e4f74cba87a4bd4fc1650c2f1e84940fae48/storybook/index.html)

2023-03-31 13:22 UTC, josheleonard approved these changes
frontend ++

2023-03-31 15:51 UTC, merged

2023-04-05 09:37 UTC, srirambv commented
Verification passed on 

Brave | 1.52.17 Chromium: 112.0.5615.49 (Official Build) nightly (64-bit)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Windows 11 Version 22H2 (Build 22621.1485)


- Verified steps from [brave/brave-browser#28407](https://github.com/brave/brave-browser/issues/28407)
- Verified displayed NFT image's URL is using the custom gateway as the host
![image](https://user-images.githubusercontent.com/17010094/230042349-d3fc23b0-f013-4928-ab37-cf64fc71c5b7.png)