feat(wallet): Add onboarding for hardware wallets
brave/brave-core pull request #17637
Opened 2023-03-16 08:51 UTC by muliswilliam

Resolves https://github.com/brave/brave-browser/issues/29107

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
https://user-images.githubusercontent.com/48117473/225563903-19143d3a-72e7-444f-8ac5-ff1712ef8f99.mov

2023-03-16 09:35 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/feat-hardware-onboarding/de4ac649f31dd611012683fb62d6a59d5cd7f3a9/storybook/index.html)

2023-03-16 15:00 UTC, Douglashdaniel requested changes

2023-03-16 15:00 UTC, Douglashdaniel commented on components/brave_wallet_ui/components/desktop/popup-modals/add-account-modal/add-hardware-account-modal.tsx
>    }, [])
Missing `isOnboarding` dependency

2023-03-16 15:00 UTC, Douglashdaniel commented on components/brave_wallet_ui/page/screens/onboarding/create-password/onboarding-create-password.tsx
>    }, [isWalletCreated])
Missing `isHardwareOnboarding` dependency

2023-03-16 15:00 UTC, Douglashdaniel commented on components/brave_wallet_ui/page/screens/onboarding/welcome/onboarding-welcome.tsx
> +
Can removed `second line` here

2023-03-16 15:05 UTC, josheleonard commented on components/brave_wallet_ui/components/desktop/popup-modals/add-account-modal/add-hardware-account-modal.tsx
> +  isOnboarding?: boolean | undefined
How about a `onSelectAccountType` prop instead to prevent writing conditional logic within this component as to how selections should be handled?

2023-03-16 15:15 UTC, josheleonard commented on components/brave_wallet_ui/constants/types.ts
> +  isHardwareOnboarding: boolean
Can we you the router to determine this instead of adding new redux state?

2023-03-16 15:16 UTC, josheleonard commented on components/brave_wallet_ui/page/reducers/page_reducer.ts
> +      setIsHardwareOnboarding (state, { payload }: PayloadAction<boolean>) {
I think we can accomplish this without adding new redux state by adding routes for hardware-onboarding

2023-03-16 15:19 UTC, josheleonard commented on components/brave_wallet_ui/page/screens/onboarding/components/onboarding-steps-navigation/onboarding-steps-navigation.tsx
> +  const isHardwareOnboarding = useSelector(({ page }: { page: PageState }) => page.isHardwareOnboarding)
Let's just use reuse `StepsNavigation` or create a `OnboardingHardwareWalletStepsNavigation` component.

2023-03-16 15:20 UTC, josheleonard commented on components/brave_wallet_ui/page/screens/onboarding/connect-hardware/onboarding-connect-hardware-wallet.tsx
> +}
Missing EOF newline

2023-03-16 15:21 UTC, josheleonard commented on components/brave_wallet_ui/page/screens/onboarding/create-password/onboarding-create-password.tsx
> +      }
Lets replace all of this with an `onWalletCreated` callback prop

2023-03-16 15:26 UTC, josheleonard requested changes

2023-03-16 15:26 UTC, josheleonard commented on components/brave_wallet_ui/page/screens/onboarding/onboarding.routes.tsx
> +      <Route path={WalletRoutes.OnboardingConnectHardwareWalletStart || WalletRoutes.OnboardingConnectHardwareWallet} exact>
This will always look for `WalletRoutes.OnboardingConnectHardwareWalletStart` since it is a truthy value

2023-03-16 15:26 UTC, josheleonard commented on components/brave_wallet_ui/page/screens/onboarding/welcome/onboarding-welcome.tsx
> +        <SubDividerText>Or</SubDividerText>
Missing translation

2023-03-28 13:00 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/feat-hardware-onboarding/a7df5a5495d925ad89c82575b73c70cb4222ec50/storybook/index.html)

2023-03-28 17:51 UTC, josheleonard approved these changes
++

2023-03-29 10:59 UTC, cypt4 approved these changes
core lgtm

2023-03-29 13:20 UTC, merged