Hide NFT pinning banner if all NFTs are failed to pin
brave/brave-core pull request #17868
Opened 2023-04-02 18:31 UTC by cypt4

Resolves https://github.com/brave/brave-browser/issues/29172

Resolves 

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2023-04-02 19:17 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/brave_29172_1/1336a8b2d23f1fb4110087c1b8c4245fd1ca9802/storybook/index.html)

2023-04-03 08:49 UTC, muliswilliam commented on components/brave_wallet_ui/common/hooks/nft-pin.ts
>      if (pinnedNftsCount > 0 && inProgressNftCount === 0) {
`inProgressNftCount` is missing from dependency array.

2023-04-03 08:57 UTC, muliswilliam requested changes
All looks good, check the missing dependency comment

2023-04-03 11:09 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/brave_29172_1/0745e627cb6967edbbd62157f70e888463a69090/storybook/index.html)

2023-04-03 12:16 UTC, muliswilliam approved these changes

2023-04-03 19:24 UTC, cypt4 commented
/build android
/build ios
/buils linux
/build macos
/build noplatform
/build win

2023-04-03 19:28 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/brave_29172_1/8934ce2153769c052903c3ec20070de666dd1bfb/storybook/index.html)

2023-04-04 11:41 UTC, merged

2023-04-12 10:03 UTC, srirambv commented
Verification passed on 

Brave | 1.52.36 Chromium: 112.0.5615.49 (Official Build) nightly (64-bit)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Windows 11 Version 22H2 (Build 22621.1555)

- Verified steps from PR description
- Verified NFT pinning banner is hidden if the setting is "on" and there are no pinned\in-progress NFTs.
- Verified NFTs with non-ipfs image like `https://opensea.io/assets/ethereum/0x70a422c390e8c7682f36611283e8a12254346ee3/1051` are correctly displayed but not being pinned
- Verified NFT pinning status is correctly updated while staying on the NFT's detail page.

https://user-images.githubusercontent.com/17010094/231425235-da9ab452-1ee0-48bd-998a-93e91ef1cfa4.mp4