WIP Add enable_cache parameter to APIRequestHelper
brave/brave-core pull request #17958
Opened 2023-04-06 21:45 UTC by nvonpentz

Passing this parameter will not add the BYPASS_CACHE and DISABLE_CACHE load flags to the request which were previously set for all requests.

Resolves 

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2023-04-10 07:36 UTC, simonhong approved these changes

2023-04-10 17:01 UTC, yrliou commented on components/api_request_helper/api_request_helper_unittest.cc
> +          }
Can we have some test case that actually sets enable_cache to true?
As far as I can see, we only executes the enable_cache = false path in all tests here.

2023-04-10 18:22 UTC, cypt4 requested changes

2023-04-10 22:58 UTC, yrliou commented on components/api_request_helper/api_request_helper.h
> +      bool enable_cache,
We should have a comment with an issue opened in the header to clearly saying this.

2023-04-10 23:15 UTC, yrliou commented on components/api_request_helper/api_request_helper.h
> +  // This method will be deprecated soon,
// This method will be deprecated soon, please use the one underneath with APIRequestOption parameter.
  // https://github.com/brave/brave-browser/issues/29611

2023-04-11 17:35 UTC, yrliou commented on components/api_request_helper/api_request_helper.h
> -                  bool enable_cache,
What's the reason that we shouldn't add enable_cache option here?

2023-04-11 17:36 UTC, cypt4 approved these changes
LGTM

2023-04-11 19:29 UTC, merged