Playlist hls support
brave/brave-core pull request #18879
Opened 2023-06-13 09:12 UTC by deeppandya

Resolves https://github.com/brave/brave-browser/issues/31001

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2023-06-13 12:43 UTC, SergeyZhukovsky commented on android/java/org/chromium/chrome/browser/toolbar/top/BraveToolbarLayoutImpl.java
> +            }
should we have a return if the service is null?

2023-06-13 14:01 UTC, deeppandya commented on third_party/android_deps/BUILD.gn
> +      "libs/com_google_android_exoplayer_exoplayer_hls/exoplayer-hls-2.17.1.aar"
i had this review for all exoplayer deps here : https://github.com/brave/security/issues/1068

2023-06-13 14:08 UTC, deeppandya commented on third_party/android_deps/BUILD.gn
> +      "libs/com_google_android_exoplayer_exoplayer_hls/exoplayer-hls-2.17.1.aar"
also created new review for this specific deps : https://github.com/brave/security/issues/1308

2023-06-13 14:21 UTC, SergeyZhukovsky approved these changes
++

2023-06-13 16:33 UTC, mkarolin approved these changes
`strings`++

2023-06-14 15:57 UTC, sujitacharya2005 approved these changes
LGTM

2023-06-15 16:48 UTC, stoletheminerals requested changes

2023-06-15 16:48 UTC, stoletheminerals commented on android/java/AndroidManifest.xml
> +            android:name="com.brave.playlist.PlaylistDownloadService"
This Service is using exoplayer lib to download files **https://github.com/brave-experiments/playlist-kotlin/blob/da5a721c0ea0c99ca2d2ad0015af988a8afce647/src/main/java/com/brave/playlist/PlaylistDownloadUtils.kt#L20.** 

We should use Chromium's network stack instead:
https://github.com/brave/security/issues/1202#issuecomment-1450252466

2023-06-16 11:14 UTC, tapanmodh approved these changes
lgtm

2023-06-16 11:25 UTC, tapanmodh commented on third_party/android_deps/libs/com_google_android_exoplayer_exoplayer_hls/README.chromium
> +License File: /brave/common/licenses/Apache-2.0
new line please

2023-07-18 18:59 UTC, kjozwiak commented
Removed the `1.57.x` milestone as the above wasn't merged into `master` yet which is currently on `1.58.x`. Once this gets merged into `master`, it will be moved into the appropriate milestone.

2024-01-24 05:43 UTC, bsclifton commented
Closing - this feature was PRed with https://github.com/brave/brave-core/pull/21041 and merged 😄👍

2024-01-24 05:43 UTC, closed without merging