AIChat: UI Fixes
brave/brave-core pull request #20811
Opened 2023-11-02 09:05 UTC by nullhook

Resolves https://github.com/brave/brave-browser/issues/33288
Resolves https://github.com/brave/brave-browser/issues/33491
Resolves https://github.com/brave/brave-browser/issues/33492

Resolves https://github.com/brave/brave-browser/issues/33266

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2023-11-02 10:13 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/ai-chat-ui-fix/d2519c9ce995b62f717a7557120daacdcf8f8303/storybook/index.html)

2023-11-03 17:47 UTC, petemill requested changes
Everything apart from the fix for https://github.com/brave/brave-browser/issues/33266 is great. Perhaps spin that off to a different PR.

2023-11-03 17:47 UTC, petemill commented on components/ai_chat/resources/page/state/data-context-provider.tsx
> +        getPageHandlerInstance().pageHandler.focusWebUI()
I don't think this is quite the right place for this as 
when I change active Tab to a Tab that 1) had a focused input on it and 2) has a Leo sidepanel open on it, then that Tab does not have focus - it is stolen by Leo. Perhaps it's debatable but it changes existing functionality so I think it'll be seen as a bug. I think the issue for https://github.com/brave/brave-browser/issues/33266 is only for switching side panels.

2023-11-03 18:00 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/ai-chat-ui-fix/60dbd589b1e891655f0cdda358794fceb05e208c/storybook/index.html)

2023-11-04 04:29 UTC, nullhook commented
i have changed the description of this PR and removed commits related to focus behavior. Focus behavior will be resolve in another commit.

2023-11-04 05:11 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/ai-chat-ui-fix/bf333b6c8f702ab66e4c70855126ae6728e03726/storybook/index.html)

2023-11-14 02:03 UTC, petemill approved these changes

2023-11-14 03:32 UTC, merged