Update title bar text color of vertical tab
brave/brave-core pull request #20988
Opened 2023-11-15 02:54 UTC by simonhong

fix https://github.com/brave/brave-browser/issues/34154

Resolves 

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2023-11-16 01:35 UTC, simonhong commented
Hmm.. it's difficult to set our colors always as frame title color is set internally from cocoa whenever related states are changed such as application theme, activation state and etc..

2023-11-16 05:52 UTC, simonhong commented
`method_exchangeImplementations` really works nicely for browser window
but I found that it affects also non-themed dialog like below. Only themed window's title's color should be updated.
<img width="489" alt="Screenshot 2023-11-16 at 2 50 54 PM" src="https://github.com/brave/brave-core/assets/6786187/dc5dafa5-9c77-42dd-8529-c350eedc1f74">

2023-11-21 00:47 UTC, simonhong commented
Kindly ping @Brandon-T :) PTAL when you're available.

2023-11-21 05:17 UTC, Brandon-T requested changes

2023-11-21 05:17 UTC, Brandon-T commented on chromium_src/components/remote_cocoa/app_shim/native_widget_ns_window_bridge.mm
> +  NSInvocation* invocation = [NSInvocation
Don't use `NSInvocation` unless calling functions defined as blocks. Use messaging.
There is a much simpler and safer way to override Objective-C methods and to call methods without `NSInvocation`.

Replace this entire function with:
```ObjC
void NativeWidgetNSWindowBridge::UpdateWindowTitleColor(SkColor color) {
  NSView* frameView = window_.contentView.superview;
  if (![frameView isKindOfClass:[BrowserWindowFrame class]]) {
    return;
  }

  if (![frameView respondsToSelector:@selector(_currentTitleColor)]) {
    return;
  }

  g_brave_title_color = skia::SkColorToDeviceNSColor(color);

  // Cache original title color
  g_original_title_color = [(BrowserWindowFrame*)frameView originalTitleColor];

  // Reset title to apply new title color.
  NSString* title = window_.title;
  window_.title = @"";
  window_.title = title;
}
```

2023-11-21 05:17 UTC, Brandon-T commented on chromium_src/components/remote_cocoa/app_shim/native_widget_ns_window_bridge.mm
> +@implementation FakeBrowserWindowFrame
Don't swizzle, remove `FakeBrowserWindowFrame` :)

Override via Forward Declaration of `[NSThemeFrame _currentTitleColor]` and Category on `BrowserWindowFrame` instead.

```ObjC
@interface NSThemeFrame(BraveTheme)
- (NSColor*)_currentTitleColor;
@end

@interface BrowserWindowFrame : NativeWidgetMacNSWindowTitledFrame
@end

@implementation BrowserWindowFrame(BraveTheme)
- (NSColor*)_currentTitleColor {
  return g_brave_title_color;
}

- (NSColor*)originalTitleColor {
  return [super _currentTitleColor];
}
@end
```

2023-11-21 06:08 UTC, simonhong reviewed
@Brandon-T Thanks for your advice.
It's really better with category. All fixed! 👍🏼

2023-11-22 00:19 UTC, Brandon-T approved these changes

2023-11-22 09:35 UTC, goodov approved these changes

2023-11-22 09:40 UTC, merged