[WIP] PSST state + UI
brave/brave-core pull request #21216
Opened 2023-12-04 15:58 UTC by ShivanKaul

Resolves  https://github.com/brave/brave-browser/issues/45930

Implemented  first step for the PSST feature, i.e. according to the Figma: https://www.figma.com/design/6wQUTHBd4HI2Ty5loKEwkt/PSST?node-id=20-5259&t=26L6hmY9j9iErPKq-0, we have first 3 screens:
- Panel opens when clicking ”Review changes”
- In progress - Applying changes
- Completed - All ok

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2023-12-04 17:25 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/feature/psst-state/e9875902e8b1fc9b07313ce2551f0f5e418bf0e3/storybook/index.html)

2023-12-12 22:01 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/feature/psst-state/68a808b18be4f16deec1d6b15658a717849e6b4e/storybook/index.html)

2025-04-23 10:00 UTC, brave-builds commented
> [!WARNING]
> You have got a presubmit warning. Please address it if possible.

```
Banned functions were used.
    browser/ui/webui/psst/brave_psst_dialog_ui.cc:47:
      Most code should already be scoped to a Browser. Pass in a Browser* or retreive from an existing entity with a reference to the Browser.
```

<!-- presubmit-hash=4ebcb6224eb3bbe7b83fb51e9d1e6faff2d74f2f616d6608892eec970e1bf201 -->

2025-04-24 22:42 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/feature/psst-state/storybook.html)

2025-04-30 15:04 UTC, boocmp requested changes

2025-04-30 15:04 UTC, boocmp commented on components/psst/resources/BUILD.gn
> +    #    "//mojo/public/mojom/base",
Remove?

2025-05-04 04:58 UTC, boocmp requested changes

2025-05-04 04:58 UTC, boocmp commented on app/brave_generated_resources.grd
> +      <message name="IDS_PSST_CONSENT_DIALOG_HEADER" desc="A header for a dialog to adjust PSST">
I think this should be moved closer to other PSST string

2025-05-04 04:58 UTC, boocmp commented on browser/brave_tab_helpers.cc
Looks like you should leave this file unchanged

2025-05-04 04:58 UTC, boocmp commented on browser/extensions/BUILD.gn
> +    "//brave/components/psst/common:common",
Shouldn't deps extending depends on the build flag that controls the psst?

2025-05-04 04:58 UTC, boocmp commented on browser/psst/brave_psst_dialog.cc
> +  gfx::Size min_size(kDialogWidth, kDialogMinHeight);
nit: `const gfx::Size ....`

2025-05-04 04:58 UTC, boocmp commented on browser/psst/brave_psst_dialog.h
> +#include "content/public/browser/web_contents.h"
nit: Forward declaration instead of include.

2025-05-04 04:58 UTC, boocmp commented on browser/psst/psst_dialog_tab_helper_delegate_impl.cc
> +  PsstDialogDelegate::ShowPsstConsentDialog(show_dialog_data);
Looks wierd, may be it'd be better to pass the dialog data in `OpenPsstDialog` where delegate is obtained, may be it will allow to remove static `ShowPsstConsentDialog` at all ?

2025-05-04 04:58 UTC, boocmp commented on browser/psst/psst_tab_web_contents_observer.cc
> +  if (const bool should_process = std::exchange(should_process_, false);
Just `!std::exchange(should_process_, false)` ?

2025-05-04 04:58 UTC, boocmp commented on browser/resources/settings/brave_privacy_page/brave_personalization_options.html
> +<settings-toggle-button
indent

2025-05-04 04:58 UTC, boocmp commented on browser/sources.gni
> +  "//brave/components/psst/browser/core:mojom",
Should this be under the buildflag ?

2025-05-04 04:58 UTC, boocmp commented on browser/ui/tabs/public/tab_features.h
> +  std::unique_ptr<psst::PsstTabWebContentsObserver> psst_observer_;
It guess it should be under the buildflag

2025-05-04 04:58 UTC, boocmp commented on browser/ui/webui/psst/brave_psst_consent_helper_handler.cc
> +    ;
Remove

2025-05-04 04:58 UTC, boocmp commented on components/psst/browser/content/psst_scripts_result_handler.cc
> +    auto* params_json = params->GetIfDict();
Can it be null?

2025-05-04 04:58 UTC, boocmp commented on components/psst/browser/content/psst_scripts_result_handler.cc
> +  if (!applied || !delegate) {
Remove DCHECK above because you check it here

2025-05-04 04:58 UTC, boocmp commented on components/psst/browser/content/psst_scripts_result_handler.cc
> +  auto* params = script_result.GetIfDict();
Can it be null ?

2025-05-04 04:58 UTC, boocmp commented on components/psst/browser/content/psst_scripts_result_handler.cc
> +  DCHECK(delegate_);
I guess you can DCHECK these values only once in c-tor

2025-05-04 04:58 UTC, boocmp commented on components/psst/browser/core/psst_opeartion_context.cc
> +std::string PsstOperationContext::GetUserId() const {
`const std::string&` ?

2025-05-06 20:50 UTC, vadimstruts commented on browser/psst/psst_dialog_tab_helper_delegate_impl.cc
> +  PsstDialogDelegate::ShowPsstConsentDialog(show_dialog_data);
Changed it to be more clear and simple

2025-05-08 07:29 UTC, boocmp commented on components/psst/browser/content/psst_scripts_result_handler.cc
> +    return;
Q: Do you need to run the callback with an empty value here to reset the context?

2025-05-08 07:29 UTC, boocmp commented on components/psst/browser/core/psst_rule.cc
> +const char kName[] = "name";
Looks like it should be constexpr

2025-05-08 07:29 UTC, boocmp commented on components/psst/browser/core/psst_rule.cc
> +  // converter->RegisterCustomValueField<base::FilePath>(
Remove ?

2025-05-08 07:29 UTC, boocmp commented on components/psst/common/psst_prefs.cc
> +  return base::StringPrintf("%s.%s", name.c_str(), user_id.c_str());
base::JoinStrings

2025-05-08 07:29 UTC, boocmp commented on components/psst/common/psst_prefs.cc
> +    registry->RegisterBooleanPref(prefs::kPsstEnabled, true);
Q: Should this also be syncable?

2025-05-09 16:31 UTC, bridiver requested changes
This PR is very large and needs to be broken up into smaller pieces. There is a lot of stuff going on here and it's not clear to me why there are so many changes to the underlying psst code, but the PR description says "state + UI" so splitting up refactoring, new functionality and UI seems like a good place to start.

2025-05-12 19:06 UTC, bridiver commented on components/psst/browser/core/matched_rule.h
> +// Used to hold the loaded script contents for a matched PsstRule.
what does it mean for a rule to be "matched"?

2025-05-12 19:13 UTC, bridiver commented on components/psst/browser/core/psst_rule_registry.cc
> +              std::make_unique<MatchedRuleFactory>(rule_data_reader_.get(),
this is not safe, `PsstRuleRegistryImpl` could be destroyed and the pointer to rule_data_reader_ will no longer be valid during the call to `CreateMatchedRule`

2025-05-14 09:16 UTC, vadimstruts commented on components/psst/browser/core/matched_rule.h
> +// Used to hold the loaded script contents for a matched PsstRule.
We load all available PSST rules from psst.json
Then when user visits some website , we check available psst rules by URL.
If one of them matched with current website, we create matched rule.
Matched rule contains all information (psst rule info + psst data (JS scripts) ) we need for applying privacy settings for current website.

2025-05-14 15:46 UTC, vadimstruts commented on components/psst/browser/core/psst_rule_registry.cc
> +              std::make_unique<MatchedRuleFactory>(rule_data_reader_.get(),
changed here: https://github.com/brave/brave-core/pull/29044/files#diff-13fd563e6b89b2f93e2d9f24cedb9c748dc8d05ab8ea383a3fe651b47e4224f9R43-R51

2026-01-14 07:43 UTC, bsclifton commented
Closing as stale - I believe this has already been broken down into multiple PRs. 
Some have already been merged

cc: @vadimstruts @ShivanKaul

2026-01-14 07:43 UTC, closed without merging