chore: create transaction origin component
brave/brave-core pull request #21794
Opened 2024-01-29 15:12 UTC by josheleonard

Resolves https://github.com/brave/brave-browser/issues/35661

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
The displayed origin url and favicon should continue to display without regressions for Brave Swaps, Matcha, CoW swap, and ERC20 token approval transactions

2024-01-29 15:52 UTC, mkarolin approved these changes
`strings`++

2024-01-29 16:14 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/chore--create-transaction-origin-component/b36b0a75ed9b9190b971276ab107050f4caa0f86/storybook/index.html)

2024-01-29 22:11 UTC, diracdeltas requested changes
https://github.com/brave/brave-core/pull/21794/files#r1470287189

2024-01-30 02:00 UTC, supermassive commented on components/brave_wallet_ui/utils/string-utils.ts
> +  return originInfo.originSpec.startsWith('chrome://wallet')
That line is actually coming from `common/origin.tsx` so strictly speaking nothing new here.

Ultimately `BraveWallet.OriginInfo` should have `bool isWalletOrigin` which a) is reusable by all ui platforms and b) comes from wallet's c++ backend as the only source of truth for what is 'wallet' origin.

2024-01-30 02:01 UTC, supermassive approved these changes
wallet core lgtm

2024-01-30 02:11 UTC, diracdeltas commented on components/brave_wallet_ui/utils/string-utils.ts
> +  return originInfo.originSpec.startsWith('chrome://wallet')
I see it's not new but we should use a real origin check here. For instance chrome://wallet@newtab resolves to chrome://newtab.

2024-01-30 13:00 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/chore--create-transaction-origin-component/db16bb0ca2b3c30a724d176c2ae5629a6bd8eee6/storybook/index.html)

2024-01-30 13:53 UTC, josheleonard commented
@diracdeltas I have updated the origin check logic

2024-01-30 14:32 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/chore--create-transaction-origin-component/8290d47d01d00143a7a746ec8e668dd44d057c33/storybook/index.html)

2024-01-30 18:55 UTC, diracdeltas approved these changes

2024-01-31 00:21 UTC, Douglashdaniel approved these changes
++

2024-01-31 09:38 UTC, merged