Allow arm64 apks to run on arm64 emulator image
brave/brave-core pull request #21922
Opened 2024-02-06 10:02 UTC by petemill

https://bugs.chromium.org/p/chromium/issues/detail?id=1303857&no_tracker_redirect=1#c7

Allows `npm run build -- Debug --target_os=android --target_arch=arm64 --target_android_output_format=apk` to produce an apk that will successfully run on an arm64 emulator (e.g. android emulator on macos m1).

Resolves 

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2024-02-06 13:48 UTC, AlexeyBarabash commented
We must ensure that the apk generated with this PR can be installed on a top of the old apks we supply through GitHub. I will check it in a while.

Also this PR needs fixed signing
```
diff --git a/build/android/BUILD.gn b/build/android/BUILD.gn
index 6b4274b310f..f1d1bed345a 100644
--- a/build/android/BUILD.gn
+++ b/build/android/BUILD.gn
@@ -49,7 +49,7 @@ action("sign_app") {
     if (target_android_output_format == "aab") {
       target_sign_app_path = "$root_out_dir/apks/MonochromePublic64.aab"
     } else {
-      target_sign_app_path = "$root_out_dir/apks/MonochromePublic.apk"
+      target_sign_app_path = "$root_out_dir/apks/MonochromePublic64.apk"
     }
   } else {
```

2024-02-06 13:48 UTC, AlexeyBarabash requested changes
pls see comment

2024-02-06 13:51 UTC, SergeyZhukovsky commented
1. The apk won't be signed and we put it to GH for users.
2. Probably Jenkins won't find the old path and fail to produce release apks.
3. We already have a pure arm64 apk, it's called `Universal` https://github.com/brave/brave-browser/releases/download/v1.64.50/Bravearm64Universal.apk and it's only in Release configuration currently
4. We keep both Universal pure arm64 apk and old way apk that contains both 32 but and 64 bit libs as iirc users who were using old apk format won't able to update to the pure arm64 one. The only way is uninstall it.

we have a special instruction on how to make arm64 build apk for M1 https://github.com/brave/brave-browser/wiki/Android-app-installation-on-64-bit-emulators

2026-08-05 22:21 UTC, bsclifton commented
Closing as stale

2026-08-05 22:21 UTC, closed without merging