[ads] Improve locale language/region detection
brave/brave-core pull request #22515
Opened 2024-03-08 15:48 UTC by tmancey

Resolves https://github.com/brave/brave-browser/issues/36644

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

Confirm `"brave.country_code` in local state matches the region of the device on macOS (alternatively confirm that the NTT component update for sponsored images is correct for the OS region.

2024-03-08 15:56 UTC, kylehickinson requested changes

2024-03-08 15:56 UTC, kylehickinson commented on components/l10n/browser/default_locale_util_ios.mm
> +          .UTF8String;
Use dictionary literal and use the correct string conversion methods, e.g.

```objc++
NSLocale* locale = NSLocale.currentLocale;
NSString *localeIdentifier = [NSLocale localeIdentifierFromComponents:@{ 
  NSLocaleLanguageCode: locale.languageCode
  NSLocaleCountryCode: locale.countryCode
}];
return base::SysNSStringToUTF8(localeIdentifier);
```

2024-03-08 15:56 UTC, kylehickinson commented on components/l10n/browser/default_locale_util_mac.mm
> -  const NSString* const locale = [[NSLocale preferredLanguages] firstObject];
same as above

2024-03-08 16:07 UTC, tmancey commented on components/l10n/browser/default_locale_util_mac.mm
> -  const NSString* const locale = [[NSLocale preferredLanguages] firstObject];
Fixed, thanks

2024-03-08 16:35 UTC, kylehickinson approved these changes

2024-03-09 09:03 UTC, merged

2024-03-26 16:34 UTC, kylehickinson commented
If uplifted, please also uplift https://github.com/brave/brave-core/pull/22779