[iOS] Add AutoFill Credential Provider Extension
brave/brave-core pull request #22553
Opened 2024-03-12 16:49 UTC by kylehickinson

Resolves

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2024-03-12 16:56 UTC, kylehickinson commented on ios/brave-ios/App/iOS/Entitlements/Beta.entitlements
> +	</array>
These are no longer needed, will remove

2024-03-12 16:57 UTC, kylehickinson commented on ios/brave-ios/Sources/CredentialProviderUI/CredentialProviderStrings.swift
> +    )
Some duplicated strings because I want to avoid duplicating 4MB of strings into the extension bundle to get to 3-4 shared strings

2024-03-12 17:00 UTC, kylehickinson commented on ios/brave-ios/Sources/CredentialProviderUI/CredentialListView.swift
> +            .foregroundColor(Color(braveSystemName: .iconInteractive))
I should swap this for a `Label` for accessibility

2024-03-12 18:19 UTC, iccub commented on ios/brave-ios/Sources/Brave/Frontend/Settings/SettingsViewController.swift
> +    UIImageView.appearance(whenContainedInInstancesOf: [SettingsViewController.self]).tintColor =
Maybe a comment why is it needed?

2024-03-13 05:28 UTC, goodov approved these changes

2024-03-15 15:03 UTC, stoletheminerals requested changes

2024-03-15 16:16 UTC, kylehickinson commented on ios/brave-ios/Sources/CredentialProviderUI/CredentialDetailView.swift
> +// Copyright 2023 The Brave Authors. All rights reserved.
Unfortunately this doesn't seem possible at this time. I tried registering to a number of notifications to receive events of backgrounding but it seems that Apple does not send them for password autofill extensions:
- `UIScene.willDeactivateNotification`
- `UIApplication.willResignActiveNotification`
- `NSExtensionHostWillResignActive`/`NSExtensionHostDidEnterBackground`

I also tried using SwiftUI the `privacySensitive` modifier which is supposed to hide content when the app is backgrounded but this doesn't work inside the auto fill extension.

I also tried monitoring the `UIApplication.shared.applicationState` but this seems to report `background` always, as its most likely giving me the state of the actual Brave app and not the autofill extension.

Console.app basically show no log activity at background other than some event handling (most likely for the system gesture)

2024-03-15 16:19 UTC, stoletheminerals approved these changes

2024-03-15 16:35 UTC, merged