Use brave-core `AdBlockDefaultResourceProvider` in iOS
brave/brave-core pull request #22983
Opened 2024-04-09 16:15 UTC by cuba

Resolves

Move more ad-block code so it's based on desktop code

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2024-04-09 17:45 UTC, Brandon-T requested changes

2024-04-09 17:45 UTC, Brandon-T commented on ios/browser/api/brave_shields/adblock_service.mm
> +    _resourceProvider = new brave_shields::AdBlockDefaultResourceProvider(_cus);
Leaking memory here.

2024-04-09 17:45 UTC, Brandon-T commented on ios/browser/api/brave_shields/adblock_service.mm
> +  _resourceObserver = new brave_shields::AdBlockResourceObserver(
Leaking memory here.

2024-04-09 17:50 UTC, Brandon-T commented
This entire file is leaking memory: `ios/browser/api/brave_shields/adblock_service.mm`
You cannot call `new` without calling `delete` somewhere to clean up the memory.

Also `raw_ptr` means you're responsible for memory deallocation. If you don't want to be responsible for it, you need an ownership container like `std::unique_ptr` instead.

2024-04-09 18:10 UTC, cuba commented
Thanks for the tips @Brandon-T , ill address the issues on both PRs.

2024-04-12 18:14 UTC, Brandon-T approved these changes

2024-04-13 09:45 UTC, merged