[iOS] - Introduce SlashTools and Search Integration
brave/brave-core pull request #24273
Opened 2024-06-18 22:21 UTC by Brandon-T

## Summary
- Implement Slash Actions List View
- Export ability to submit conversation text with an action
- Use UITextView for input
- Add Slash Tools button
- Integrate slash tools into the label and input
- Limit the size of the SlashTools view
- Integrate search queries event
- Add UI for search integration
- Tweak Markdown Rendering to display new-line after bullet paragraphs

Resolves https://github.com/brave/brave-browser/issues/38962 
Resolves https://github.com/brave/brave-browser/issues/37297

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

https://github.com/brave/brave-core/assets/1530031/64bff591-b5ce-46a2-ac97-a255c926afb5

2024-06-19 13:54 UTC, kylehickinson requested changes

2024-06-19 13:54 UTC, kylehickinson commented on ios/brave-ios/Sources/AIChat/Components/AIChatLoaderView.swift
> +        progress = (progress + 1) % 360
Why not just derive progress based on the date directly (store the start date)? You're technically causing a double body evaluation for every tick currently

2024-06-19 13:54 UTC, kylehickinson commented on ios/brave-ios/Sources/AIChat/Components/Input/AIChatPaddedTextView.swift
> +    }
This method doesnt do anything?

2024-06-19 13:54 UTC, kylehickinson commented on ios/brave-ios/Sources/AIChat/Components/AIChatLoaderView.swift
> +  private let backgroundColor: Color
Delete and use `foregroundStyle`/`backgroundStyle` modifiers at call site instead then you can just do `Circle().stroke(.foreground)` or `Circle().stroke(.background)`.  You could also swap out foregroundStyle for `tint` modifiers and use `.stroke(.tint)` as well but its mostly semantics at that point

2024-06-19 13:54 UTC, kylehickinson commented on ios/brave-ios/Sources/AIChat/Components/Messages/AIChatResponseMessageView.swift
> +  func renderSearchQueries(queries: [String]) -> Text {
nit: naming, you're not rendering anything, you're building out a `Text` out of a list of queries.

2024-06-19 13:54 UTC, kylehickinson commented on ios/brave-ios/Sources/AIChat/Components/Messages/AIChatResponseMessageView.swift
> +    text = text + space
nit: `text` is already mutable, you may as well mutate in-place instead (`text.append(space)` or `text += space`) instead of re-assigning

2024-06-19 13:54 UTC, kylehickinson commented on ios/brave-ios/Sources/AIChat/Components/Messages/AIChatResponseMessageView.swift
> +      text = text + quote + link + quote
Same as above

2024-06-19 13:54 UTC, kylehickinson commented on ios/brave-ios/Sources/AIChat/Components/Messages/AIChatResponseMessageView.swift
> +        text = text + comma + space
Same as above

2024-06-19 13:54 UTC, kylehickinson commented on ios/brave-ios/Sources/AIChat/Components/SlashTools/AIChatSlashToolsLabel.swift
> +        .foregroundColor(Color(braveSystemName: .primary50))
nit: everything in this HStack uses the same font and color, remove these 2 modifiers from each view to the containing HStack

2024-06-19 13:54 UTC, kylehickinson commented on ios/brave-ios/Sources/AIChat/Components/SlashTools/AIChatSlashToolsLabel.swift
> +    }
`.background(Color(braveSystemName: .primary20), in: .containerRelative)`

2024-06-19 13:54 UTC, kylehickinson commented on ios/brave-ios/Sources/AIChat/Components/SlashTools/AIChatSlashToolsView.swift
> +        }
Don't update State during a body computation. Replace with:

```swift
.overlay {
  GeometryReader { proxy in 
    Color.clear
      .onAppear { 
        contentSize = proxy.size
      }
      .onChange(of: proxy.size) { size in 
        contentSize = size
      }
  }
}
```

2024-06-19 18:36 UTC, kylehickinson commented on ios/brave-ios/Sources/AIChat/Components/AIChatLoaderView.swift
> +    let startDate = Date()
Store it in `@State`

2024-06-19 19:36 UTC, kylehickinson approved these changes

2024-06-19 20:18 UTC, merged

2024-07-03 00:45 UTC, hffvld commented
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.69 (73)
BraveCore: 1.69.73 (127.0.6533.26)
```
---------------------------

**STEPS:**
1. Launch Brave `1.69 (73)`
2. Open `Leo` > *Verify that the `slash tools` button `/` is there*
3. Tap `/` > Choose `Explain`
4. Type a prompt  > Hit Enter > *Verify*
5. Tap `/` > Choose `Improve` this time
6. Type a prompt  > Hit Enter > *Verify*
7. Tap `/` > Choose `Change tone / Funny` this time
8. Type a prompt  > Hit Enter > *Verify*
9. Tap `/` > Choose `Social media / Short post` this time
10. Type a prompt  > Hit Enter > *Verify*
11. Enter some prompt > Tap `/` > *Verify*
12. Tap `/` > Choose any action > Tap in a prompt field
13. Tap `Backspace` on the keyboard > *Verify*
14. Tap the `Mic` button > Provide a `voice prompt` > *Verify*

**ACTUAL RESULTS:**
- Verified that the `Slash tools` are shown in the prompt field
- Verified that the `Slash tools` can be opened/closed by tapping the `/` button or typing and deleting `/` in the text field
- Verified that the `Slash tools` dropdown menu is scrollable and can be collapsed/expanded by tapping the `arrow`
- Verified that any `action` can be dismissed by tapping the `x` or `Backspace` button on the keyboard
- Verified that different `actions` are working and providing different answers based on `action` type
- Verified that `Voice prompt` is working when an `action` is applied

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-core/assets/128532965/246b2d29-fafb-4df1-bf0e-3d3149dbbc46) | ![2](https://github.com/brave/brave-core/assets/128532965/27f6c4f6-9de3-48a3-89e4-255d2f256252) | ![3](https://github.com/brave/brave-core/assets/128532965/0a454c93-78df-48da-8251-04aa417ed421) | ![4](https://github.com/brave/brave-core/assets/128532965/38e268e2-3eba-417c-82f4-6e77eb9a6650) |
| ![1](https://github.com/brave/brave-core/assets/128532965/c00794d5-5382-4e86-a515-f4c9f78c51f5) | ![2](https://github.com/brave/brave-core/assets/128532965/45c6fb8a-4d75-4ca6-b011-be87fef2129c) | ![3](https://github.com/brave/brave-core/assets/128532965/452c01f2-9bb8-4b4d-887e-ea15ac554689) | ![4](https://github.com/brave/brave-core/assets/128532965/57902ea1-32f3-485d-acb9-1b1882ee6b40) |
| ![1](https://github.com/brave/brave-core/assets/128532965/e16b5ffa-fd63-4f1c-99d2-6a40c49e62df) | ![2](https://github.com/brave/brave-core/assets/128532965/2f6ea250-099a-4dc6-a3cd-d27fb6f201d8) | ![3](https://github.com/brave/brave-core/assets/128532965/e6cefce2-7a88-4aa3-af0b-641d69ea9559) | ![4](https://github.com/brave/brave-core/assets/128532965/6a56b380-8f13-4d78-b12e-a871cf154a36) |
| ![1](https://github.com/brave/brave-core/assets/128532965/a4bfaf2c-e508-43d5-9f5d-2da0f6817e29) | ![2](https://github.com/brave/brave-core/assets/128532965/2957fc7e-8670-4178-ac16-8615e518b871) | ![3](https://github.com/brave/brave-core/assets/128532965/47671920-40de-40c9-9ff7-ef6589201191) | ![4](https://github.com/brave/brave-core/assets/128532965/429bd6c7-dc9c-4ccc-a7bc-8db6b4a81152) |

https://github.com/brave/brave-core/assets/128532965/e235419c-cd6f-43c6-ba28-2d91e5b3f96d