feat(wallet): add SafeSign to LiFi bridge transactions
brave/brave-core pull request #24608
Opened 2024-07-11 16:42 UTC by onyb

Resolves https://github.com/brave/brave-browser/issues/39701

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

See STR in linked issue. Note that this PR does not implement UI for SafeSign in bridge transactions, which will be implemented in a subsequent PR.

2024-07-11 17:26 UTC, josheleonard commented on components/brave_wallet_ui/utils/tx-utils.ts
> +// can asynchronously extract details from the blockchain.
Mind using `/** */` style comments here so the notes appear when the function is hovered-over in a text editor?

2024-07-11 17:28 UTC, josheleonard approved these changes
Frontend LGTM. Great work!

2024-07-12 06:33 UTC, supermassive approved these changes
wallet core lgtm

2024-07-12 11:55 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/f/wallet/bridge-safe-sign/3bb7acac7d6794edb0c9ac079288b848f87b654f/storybook/index.html)

2024-07-16 03:51 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/f/wallet/bridge-safe-sign/6b49fe517dff56ae4ddafe0ead26c1352e856d72/storybook/index.html)

2024-07-16 14:20 UTC, nuo-xu approved these changes
fixed the iOS side. @StephenHeaps PTAL on my changes.

2024-07-16 16:37 UTC, StephenHeaps requested changes

2024-07-16 16:37 UTC, StephenHeaps commented on ios/brave-ios/Sources/BraveWallet/Crypto/Stores/SwapTokenStore.swift
> +      // https://github.com/brave/brave-browser/issues/36436
Should remove this old url, just link to the new issue #39043

2024-07-16 16:37 UTC, StephenHeaps commented on ios/brave-ios/Sources/BraveWallet/Crypto/Stores/AccountActivityStore.swift
> +    allNetworks: [BraveWallet.NetworkInfo],
Should just remove `networksForCoin` if we're passing in all networks now.

2024-07-16 16:37 UTC, StephenHeaps commented on ios/brave-ios/Sources/BraveWallet/Crypto/Transactions/TransactionParser.swift
> +    currentNetwork: BraveWallet.NetworkInfo,
`currentNetwork` isn't needed anymore, can fetch it using the `chainId` & `coin` from the `TransactionInfo` model.

2024-07-16 16:37 UTC, StephenHeaps commented on ios/brave-ios/Sources/BraveWallet/Crypto/Transactions/TransactionParser.swift
> -    )
Why did this move to be defined in each `TransactionType`? Seems unnecessary code duplication, we're still using the same initialization in each type?

2024-07-16 16:37 UTC, StephenHeaps commented on ios/brave-ios/Sources/BraveWallet/Crypto/Transactions/TransactionParser.swift
> +  let fromNetwork: BraveWallet.NetworkInfo
nit unneeded comment
```suggestion
  /// From token network
  let fromNetwork: BraveWallet.NetworkInfo
```

2024-07-16 16:37 UTC, StephenHeaps commented on ios/brave-ios/Sources/BraveWallet/Crypto/Transactions/TransactionParser.swift
> +  let toNetwork: BraveWallet.NetworkInfo
nit: unneeded comment
```suggestion
  /// To token network (not yet being used. preparation for bridging)
  let toNetwork: BraveWallet.NetworkInfo
```

2024-07-16 16:40 UTC, StephenHeaps commented on ios/brave-ios/Sources/BraveWallet/Crypto/Stores/TransactionDetailsStore.swift
>        guard let network = networksForCoin.first(where: { $0.chainId == transaction.chainId }) else {
Just check `allNetworks` here now so we only loop through once

2024-07-16 22:32 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/f/wallet/bridge-safe-sign/83da6c0a3b1db3aba5fd5d4212052ed6f9776b44/storybook/index.html)

2024-07-16 22:48 UTC, StephenHeaps commented on ios/brave-ios/Sources/BraveWallet/Crypto/Transactions/TransactionParser.swift
> +      )
Shouldn't be needed here

2024-07-17 02:35 UTC, StephenHeaps approved these changes

2024-07-17 03:26 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/f/wallet/bridge-safe-sign/363f1a1595423ca873d6f1065723ef94209be8d4/storybook/index.html)

2024-07-18 17:29 UTC, merged

2024-07-19 09:55 UTC, srirambv commented
Verification passed on 

Brave | 1.70.5 Chromium: 127.0.6533.57 (Official Build) nightly (64-bit)
-- | --
Revision | face8d58ab81422480c8c05b9ba5d518e1a2d227
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified Safe Sign panel is shown for bridge transaction

https://github.com/user-attachments/assets/c48c5644-8be4-40fd-9742-dc7f89e6c6d1