Playlist Revamp Improvements
brave/brave-core pull request #24684
Opened 2024-07-16 20:01 UTC by kylehickinson

This further improves the new playlist based on feedback

- Adds 1.2x rate (bumps `leo-sf-symbols` to get the new icon)
- Adds UI when double-tapping video player to seek backwards/forwards
- Adds a button to go to the next item while fullscreen
- Fixes a severe hang due to an XPC lock when calling `AVPlayer.replaceCurrentItem(with:)` on the main thread 

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2024-07-17 14:02 UTC, iccub requested changes

2024-07-17 14:18 UTC, kylehickinson commented on ios/brave-ios/Sources/PlaylistUI/PlayerView.swift
> +            Label("Next Item", braveSystemImage: "leo.next.outline")
Nothing in playlist revamp is localized yet, will be done nearer to the end of UI finalization

2024-07-17 14:23 UTC, iccub approved these changes

2024-07-17 17:26 UTC, stoletheminerals approved these changes

2024-07-17 18:59 UTC, Brandon-T approved these changes

2024-07-18 19:58 UTC, petemill approved these changes
JS deps ok https://github.com/brave/leo-sf-symbols/compare/f66f5701f8330253c1c113228c08f129178941c2..8685eec0851afa96d23dd424cd152854476e585d

2024-07-18 20:34 UTC, merged