Update url for ABP Iceland
brave/brave-core pull request #24764
Opened 2024-07-19 23:15 UTC by ryanbr

Update URL to match the newly hosted list on https://github.com/brave/adblock-lists

2024-07-19 23:39 UTC, fmarier requested changes

2024-07-19 23:39 UTC, fmarier commented on components/third_party/adblock/lists/is_abp/README.chromium
> +URL: https://github.com/brave/adblock-lists
```suggestion
URL: https://github.com/brave/adblock-lists/blob/master/custom/is.txt
```

2024-07-20 03:45 UTC, fmarier approved these changes

2024-08-08 01:40 UTC, ryanbr commented
Not sure whats hold this up @fmarier

2024-08-08 05:10 UTC, fmarier commented
@ryanbr Looks like CI is stuck. Try squashing your two commits and then doing a `git push --force`, it will trigger a new CI run.

2024-08-08 05:31 UTC, closed without merging

2024-08-08 05:31 UTC, ryanbr commented
Dropping this its pulled in other commits for some reason