[iOS] Add 1.68 translations.
brave/brave-core pull request #24776
Opened 2024-07-22 15:22 UTC by iccub

Resolves https://github.com/brave/brave-browser/issues/39617

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2024-07-22 15:42 UTC, soner-yuksel commented on ios/brave-ios/Sources/AIChat/Resources/tr.lproj/BraveLeo.strings
> +"aichat.introMessageLlamaMessageDescription" = "Merhaba, ben Leo. Ben Brave tarafından geliştirilen, tamamen ana makinede bulunan bir YZ asistanıyım. Meta tarafından pek çok kullanım alanında iyi per
The abbreviation of AI in Turkish to YZ doesnt work. We should use full phrase.

"aichat.introMessageLlamaMessageDescription" = "Merhaba, ben Leo. Ben Brave tarafından geliştirilen, tamamen ana makinede bulunan bir Yapay Zeka asistanıyım. Meta tarafından pek çok kullanım alanında iyi performans vermesi ve uygulanabilir olması için geliştirilen bir model olan Llama 3 8B ile destekleniyorum.";

2024-07-22 15:43 UTC, soner-yuksel commented on ios/brave-ios/Sources/AIChat/Resources/tr.lproj/BraveLeo.strings
> +"aichat.leoNavigationTitle" = "Leo YZ";
"aichat.leoNavigationTitle" = "Leo Yapay Zeka";

2024-07-22 15:44 UTC, soner-yuksel commented on ios/brave-ios/Sources/AIChat/Resources/tr.lproj/BraveLeo.strings
> +"aichat.termsConditionsDescription" = "Brave Leo, web kullanımınızı geliştiren özel bir YZ asistanıdır. Leo'yu kullanmak, sınırlı erişimle ücretsizdir. Brave Leo Premium ise daha fazla model ve daha
"aichat.termsConditionsDescription" = "Brave Leo, web kullanımınızı geliştiren özel bir Yapay Zeka asistanıdır. Leo'yu kullanmak, sınırlı erişimle ücretsizdir. Brave Leo Premium ise daha fazla model ve daha yüksek limitler sunar, ayrıca abonelerin yeni özellikleri erkenden deneyimlemesine olanak tanır. Şu anda tüm kullanıcılar için varsayılan model Mixtral 8x7B'dir. Daha fazla bilgi için Brave **[Yardım Merkezi](%1$@)**'ne bakın.\n\nVarsayılan olarak, Leo'ya bir soru sorduğunuzda Leo görüntülediğiniz web sayfasının içeriğini veya sayfada, Brave Leo'nun yanıt vermesini istediğiniz için vurguladığınız metinleri gönderebilir ve kullanabilir. Bazı durumlarda, Leo Brave Arama'ya girdiğiniz sözcükler kullanılarak türetilen sorgular gönderir ve sorunuzu daha iyi yanıtlayabilmek için arama sonuçlarını kullanır. Yanıtların doğruluğu garanti edilmez ve hatalı, yanlış yönlendiren veya yanlış bilgiler içerebilir. Hassas ve gizli bilgiler göndermeyin ve sağlık, finans, kişisel güvenlik veya benzeri cevapları kullanırken dikkatli olun. Leo'nun seçeneklerini Ayarlar menüsünden istediğiniz zaman değiştirebilirsiniz. Ayarlar > Leo bölümüne gidin.\n\nLeo, IP adresi gibi, sizinle ilişkilendirilebilecek tanımlayıcı bilgileri toplamaz. Yapay Zeka modellerini eğitmek için hiçbir veri kullanılmaz ve Yapay Zeka modelleri (verileri silmeden önce 30 gün boyunca tutan Anthropic dışında) hiçbir kişisel veriyi tutmaz. Daha fazla bilgi için **[gizlilik politikasına](%2$@)** bakın.";

2024-07-22 16:16 UTC, nuo-xu requested changes

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveStrings/Resources/zh.lproj/BraveShared.strings
> +"closeAllOtherTabsPrompt" = "確定要關閉所有其他開啟的分頁嗎？";
```suggestion
"closeAllOtherTabsPrompt" = "确定要关闭所有其他开启的分页吗？";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveStrings/Resources/zh.lproj/BraveShared.strings
> +"closeAllOtherTabsTitle" = "關閉其他所有分頁";
```suggestion
"closeAllOtherTabsTitle" = "关闭其他所有分页";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveStrings/Resources/zh.lproj/BraveShared.strings
> +"DismissChangesButtonTitle" = "忽略變更";
```suggestion
"DismissChangesButtonTitle" = "忽略变更";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveStrings/Resources/zh.lproj/BraveShared.strings
> +"DismissChangesConfirmationMessage" = "確定要忽略這些變更嗎？任何修改內容將會遺失。";
```suggestion
"DismissChangesConfirmationMessage" = "确定要忽略这些变更吗？任何修改內容将会遗失。";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveStrings/Resources/zh.lproj/BraveShared.strings
> +"DismissChangesConfirmationTitle" = "是否忽略變更？";
```suggestion
"DismissChangesConfirmationTitle" = "是否忽略变更？";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveStrings/Resources/zh.lproj/BraveShared.strings
> +"SaveChangesButtonTitle" = "儲存變更";
```suggestion
"SaveChangesButtonTitle" = "储存变更";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveStrings/Resources/zh.lproj/BraveShared.strings
> +"SyncAddDeviceScanDescription" = "在另一部行動裝置上，瀏覽到「設定」面板中的「同步」，並點選「掃描同步代碼」按鈕。使用相機掃描下方的 QR 碼。\n\n請將此代碼視為密碼。如果他人取得此代碼，將能讀取及修改您同步的資料。";
```suggestion
"SyncAddDeviceScanDescription" = "在另一部行动装置上，浏览到「设定」面板中的「同步」，并点选「扫描同步代码」按钮。使用相机扫描下方的二维码。\n\n请将此代码视为密码。如果他人取得此代码，将能读取及修改您同步的资料。";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveStrings/Resources/zh.lproj/BraveShared.strings
> +"SyncAddDeviceWordsDescription" = "在您的裝置上，瀏覽到「設定」面板中的「同步」，並點選「%@」按鈕。輸入下方顯示的同步鏈代碼字組。\n\n請將此代碼視為密碼。如果他人取得此代碼，將能讀取及修改您同步的資料。";
```suggestion
"SyncAddDeviceWordsDescription" = "在您的裝置上，浏览到「设定」面板中的「同步」，并点选「%@」按钮。输入下方显示的同步链代码字组。\n\n请将此代码视为密码。如果他人取得此代码，将能读取及修改您同步的资料。";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveStrings/Resources/zh.lproj/BraveShared.strings
> +"SyncCodeExpirationTitleLabel" = "代碼已過期。請點選下方按鈕來產生新代碼。";
```suggestion
"SyncCodeExpirationTitleLabel" = "代码已过期。请点选下方按钮来生成新代码。";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveStrings/Resources/zh.lproj/BraveShared.strings
> +"SyncCodeTimeRemainingTitleLabel" = "這個暫時代碼於接下來 %@內有效。";
```suggestion
"SyncCodeTimeRemainingTitleLabel" = "这个零时代码于接下来 %@內有效。";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveStrings/Resources/zh.lproj/Localizable.strings
> +"paywall.alreadyPurchasedTitle" = "已在 brave.com 上購買嗎？";
```suggestion
"paywall.alreadyPurchasedTitle" = "已在 brave.com 上都买吗？";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveStrings/Resources/zh.lproj/Localizable.strings
> +"paywall.refreshCredentialsButtonTitle" = "重新整理您的憑證";
```suggestion
"paywall.refreshCredentialsButtonTitle" = "重新整理您的凭证";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveWallet/Resources/zh.lproj/BraveWallet.strings
> +"wallet.accountNameLengthError" = "帳戶名稱的長度不得超過 %lld 個字元";
```suggestion
"wallet.accountNameLengthError" = "账户名称的长度不得超过 %lld 個字元";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveWallet/Resources/zh.lproj/BraveWallet.strings
> +"wallet.bitcoinImportExtendedKeyWarning" = "僅支援 %@ 延伸金鑰。";
```suggestion
"wallet.bitcoinImportExtendedKeyWarning" = "仅支援 %@ 延伸金钥。";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveWallet/Resources/zh.lproj/BraveWallet.strings
> +"wallet.defaultAccountName" = "%1$@ 帳戶 %2$lld";
```suggestion
"wallet.defaultAccountName" = "%1$@ 账户 %2$lld";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveWallet/Resources/zh.lproj/BraveWallet.strings
> +"wallet.defaultTestnetAccountName" = "%1$@ 測試網帳戶 %2$lld";
```suggestion
"wallet.defaultTestnetAccountName" = "%1$@ 测试网账户 %2$lld";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveWallet/Resources/zh.lproj/BraveWallet.strings
> +"wallet.inputLabel" = "輸入";
```suggestion
"wallet.inputLabel" = "输入";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveWallet/Resources/zh.lproj/BraveWallet.strings
> +"wallet.outputLabel" = "輸出";
```suggestion
"wallet.outputLabel" = "输出";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveWallet/Resources/zh.lproj/BraveWallet.strings
> +"wallet.setDefaultNetwork" = "設為預設";
```suggestion
"wallet.setDefaultNetwork" = "设为预设";
```

2024-07-22 16:16 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveWallet/Resources/zh.lproj/BraveWallet.strings
> +"wallet.valueLabel" = "價值";
```suggestion
"wallet.valueLabel" = "价值";
```

2024-07-22 19:57 UTC, kjozwiak commented
I'll wait till the above concerns have been addressed before uplifting into `1.68.x`. @iccub please let me know once you've addressed the fixes/rebased the PR 👍

2024-07-24 14:17 UTC, nuo-xu commented on ios/brave-ios/Sources/AIChat/Resources/zh.lproj/BraveLeo.strings
> +"aichat.advancedSettingsAutocompleteDescription" = "開啟以顯示從網址列啟動 Leo 的捷徑";
```suggestion
"aichat.advancedSettingsAutocompleteDescription" = "开启以显示从网址列启动 Leo 的捷径";
```

2024-07-24 14:17 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveStrings/Resources/zh.lproj/Localizable.strings
> +"paywall.alreadyPurchasedTitle" = "已在 brave.com 上都买吗？";
```suggestion
"paywall.alreadyPurchasedTitle" = "已在 brave.com 上购买吗？";
```

2024-07-24 14:28 UTC, nuo-xu approved these changes

2024-07-25 18:51 UTC, kjozwiak approved these changes
Uplift into `1.68.x` approved 👍

2024-07-25 18:52 UTC, merged