feat(wallet): Update Explore Web3 UI to match new design
brave/brave-core pull request #24857
Opened 2024-07-25 21:22 UTC by muliswilliam

Resolves https://github.com/brave/brave-browser/issues/39850

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2024-07-25 22:29 UTC, josheleonard requested changes

2024-07-25 22:29 UTC, josheleonard commented on components/brave_wallet_ui/components/desktop/views/explore_web3/explore_web3.tsx
> +    React.useState<boolean>(false)
Is this state needed? Wont the modal always be open if the selected dapp is not `undefined`

2024-07-25 22:29 UTC, josheleonard commented on components/brave_wallet_ui/components/desktop/views/explore_web3/explore_web3.tsx
> +    setIsDappDetailsOpen(true)
Can we remove this and just check if a dapp is selected to open the modal?

2024-07-25 22:29 UTC, josheleonard commented on components/brave_wallet_ui/components/desktop/views/explore_web3/explore_web3.tsx
> +            setIsDappDetailsOpen(false)
Can we remove this?

2024-07-25 22:29 UTC, josheleonard commented on components/brave_wallet_ui/components/desktop/views/crypto/index.tsx
> +    React.useState<string>(WalletRoutes.Market)
Do we need this state? can we check the URL instead?

2024-07-25 22:29 UTC, josheleonard commented on components/brave_wallet_ui/components/desktop/views/crypto/index.tsx
> +  const exploreWeb3Header = (
Move to a new component if the `setState` can be avoided

2024-07-25 22:29 UTC, josheleonard commented on components/brave_wallet_ui/components/desktop/views/explore_web3/web3_dapp_details.tsx
> +      <Title slot='title'>Details</Title>
missing translation

2024-07-25 22:29 UTC, josheleonard commented on components/brave_wallet_ui/components/desktop/views/explore_web3/explore_web3.tsx
> +          isOpen={isDappDetailsOpen}
```suggestion
          isOpen={true}
```

2024-07-25 22:55 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/feat/update-explore-dapps/a13fb0362df31ae3698b12a89a477bf89f082954/storybook/index.html)

2024-07-29 20:07 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/feat/update-explore-dapps/c898dc8f2ec2fdc7642e5c57f8724aec448f59f8/storybook/index.html)

2024-07-29 20:31 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/feat/update-explore-dapps/a7862d3fdc93e1fe2e058f85b29a9b183b007be7/storybook/index.html)

2024-07-29 21:34 UTC, josheleonard commented on components/brave_wallet_ui/components/desktop/views/explore_web3/explore_web3.tsx
> +  }, [])
This callback method is not needed since it only calls `setSelectedDapp` with unmodified args. Please use `setSelectedDapp` directly

2024-07-29 21:34 UTC, josheleonard commented on components/brave_wallet_ui/components/desktop/views/explore_web3/explore_web3_header.tsx
> +import {
nit: add // style comment for import group 

2024-07-29 21:34 UTC, josheleonard commented on components/brave_wallet_ui/components/desktop/views/explore_web3/web3_dapp_details.tsx
> +import { BraveWallet } from '../../../../constants/types'
can you use an type import for this? Also move to a `// types` or `// constants` import group
```suggestion
import type { BraveWallet } from '../../../../constants/types'
```

2024-07-29 21:34 UTC, josheleonard commented on components/brave_wallet_ui/stories/locale.ts
> +  braveWalletDetails: 'Details'
Thanks for adding a new generic "details" locale, but can we remove the old locales that also use the string "Details"? i.e: `braveWalletAllowAddNetworkDetailsPanelTitle`

2024-07-29 22:21 UTC, josheleonard approved these changes
++

2024-07-29 22:32 UTC, mkarolin approved these changes
`strings`++

2024-07-29 23:01 UTC, yrliou approved these changes
core++

2024-07-29 23:10 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/feat/update-explore-dapps/bbee16ba2ea47b60b0b3a397fc12464193483cc8/storybook/index.html)

2024-07-30 07:56 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/feat/update-explore-dapps/2feb5816436187bf067939a6927d559a1fb381ae/storybook/index.html)

2024-07-30 09:05 UTC, merged