Import Data from Safari iOS
brave/brave-core pull request #26914
Opened 2024-12-06 16:26 UTC by Brandon-T

## Security Review
- 

## Summary
- Add Password Importer API to Brave-Core and a Swift wrapper around it
- Add History Importer API to Brave-Core and a Swift wrapper around it
- Refactor Bookmarks Import API in Swift to be async-await

Resolves https://github.com/brave/brave-browser/issues/42727

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2024-12-06 16:36 UTC, kylehickinson requested changes
Quick glance feedback (haven't looked at implementation details yet):
- Needs unit tests
- Everything under `ios/browser/api` should be Obj-C wrappers, please move all of the actual importer logic to separate directory/directories. Try to match Chromium's directory structure in this regard
- Is it possible to share this logic with desktop so that they can get Safari import via exported zip as well?

2024-12-09 03:42 UTC, kdenhartog commented on components/password_manager/core/browser/import/csv_safari_password.cc
> +  CSVFieldParser parser(row);
Seems that the [parser here](https://source.chromium.org/chromium/chromium/src/+/main:components/password_manager/core/browser/import/csv_field_parser.h?q=CSVFieldParser&ss=chromium) considers the grammar simple enough that it doesn't require using a memory safe language or separate process.

I believe this the solves for the rule of 2 issue here as well.

2024-12-09 20:54 UTC, mkarolin approved these changes
Not clear if we need a header in DEPS files, but for now ++

2025-01-22 23:05 UTC, thypon requested changes
requires test

2025-01-22 23:05 UTC, thypon commented on ios/brave-ios/Sources/Brave/Frontend/Sync/BraveCore/ZipImporter/ZipImporter.swift
> +        try await AsyncFileManager.default.removeItem(atPath: extractionPath.path)
this looks zipslip vulnerable. Has anyone tested? @stoletheminerals

2025-01-23 00:14 UTC, thypon approved these changes

2025-02-03 20:38 UTC, nuo-xu requested changes
initial review. still need a e2e testing. missing most of the localizations and some other comments.

2025-02-03 20:38 UTC, nuo-xu commented on ios/brave-ios/Sources/Brave/Frontend/Browser/BrowserViewController/BVC+WKNavigationDelegate.swift
> +    //    tab.nightMode = Preferences.General.nightModeEnabled.value
forgot to uncomment it?

2025-02-03 20:38 UTC, nuo-xu commented on ios/brave-ios/Sources/BraveUI/SwiftUI/BraveLoadingStyle.swift
> +  private var filledCircleColor = Color(UIColor(rgb: 0x7C91FF))
this class doesn't seem to be used anywhere.

2025-02-03 20:38 UTC, nuo-xu commented on ios/brave-ios/Sources/DataImporter/DataImporterStrings.swift
> +        "SyncImportFolderName",
duplicated key under `Strings.Sync`

2025-02-03 20:38 UTC, nuo-xu commented on ios/brave-ios/Sources/DataImporter/Images.xcassets/password_conflict_logo.imageset/Contents.json
> +}
this icon looks the same as `failure_import_logo` above

2025-02-03 20:38 UTC, nuo-xu commented on ios/brave-ios/Sources/DataImporter/Models/DataImportModel.swift
> +    case .unknown: "An Unknown Error Occurred during data importing."
i think these all need to be localized.

2025-02-03 20:38 UTC, nuo-xu commented on ios/brave-ios/Sources/DataImporter/Models/DataImportModel.swift
> +        // TODO: Localize "Personal"
TODO

2025-02-03 20:38 UTC, nuo-xu commented on ios/brave-ios/Sources/DataImporter/UI/BraveDataImporterLoadingView.swift
> +      Text("Importing Your Data...")
localization

2025-02-03 20:38 UTC, nuo-xu commented on ios/brave-ios/Sources/DataImporter/UI/BraveDataImporterLoadingView.swift
> +      Text("Please wait while we securely transfer your data.\nThis might take a few moments.")
localization

2025-02-03 20:38 UTC, nuo-xu commented on ios/brave-ios/Sources/DataImporter/UI/BraveDataImporterTutorialView.swift
> +//
😂 copyright

2025-02-03 20:39 UTC, Brandon-T commented
> initial review. still need a e2e testing. missing most of the localizations and some other comments. 

Localizations not done yet yeah.
It can't be unit tested due to Brave-Core lol

2025-02-03 20:45 UTC, Brandon-T commented on ios/brave-ios/Sources/DataImporter/Images.xcassets/password_conflict_logo.imageset/Contents.json
> +}
Ahh yeah. They're the same in the design. I guess I could delete this one.

2025-02-03 20:50 UTC, Brandon-T commented on ios/brave-ios/Sources/BraveUI/SwiftUI/BraveLoadingStyle.swift
> +  private var filledCircleColor = Color(UIColor(rgb: 0x7C91FF))
I only moved it. It's from AI-Chat's design. Not used currently.

2025-02-03 20:50 UTC, Brandon-T commented on ios/brave-ios/Sources/DataImporter/DataImporterStrings.swift
> +        "SyncImportFolderName",
It was moved but not duplicated.

2025-02-11 20:00 UTC, kylehickinson commented on ios/brave-ios/Sources/DataImporter/UI/BraveDataImporterView.swift
> +          .edgesIgnoringSafeArea(.all)
deprecated API, use `ignoresSafeArea`

2025-02-11 20:08 UTC, kylehickinson commented on ios/brave-ios/Sources/DataImporter/UI/BraveDataImporterView.swift
> +      } secondaryAction: {
This isnt hooked up?

2025-02-11 21:50 UTC, Brandon-T commented on ios/brave-ios/Sources/DataImporter/UI/BraveDataImporterLoadingView.swift
> +        )
This is from the formatter. It does this no matter what I do.

2025-02-11 21:55 UTC, Brandon-T commented on ios/brave-ios/Sources/DataImporter/UI/BraveDataImporterView.swift
> +      } secondaryAction: {
Not yet. We just decided on call earlier today to remove it.

2025-02-19 20:04 UTC, stoletheminerals approved these changes

2025-02-20 20:29 UTC, nuo-xu approved these changes

2025-02-20 22:40 UTC, kylehickinson requested changes
Couple more notes

2025-02-20 22:40 UTC, kylehickinson commented on ios/brave-ios/Sources/DataImporter/UI/DataImporterStateView.swift
> +      }
This shouldn't be part of the VStack, it should be in a `overlay(alignment: .topTrailing)`

2025-02-20 22:40 UTC, kylehickinson commented on ios/brave-ios/Sources/DataImporter/UI/DataImporterView.swift
> +  private var model = DataImportModel()
This should be a `@StateObject` if you're going to create it in the View

2025-02-20 22:40 UTC, kylehickinson commented on ios/brave-ios/Sources/DataImporter/UI/DataImporterView.swift
> +  private var showMainView = true
As per DM these should all be removed

2025-02-20 22:40 UTC, kylehickinson commented on ios/brave-ios/Sources/DataImporter/UI/DataImporterView.swift
> +  private func mainView() -> some View {
Doesn't need to be a func, can just be `private var mainView: some View`

2025-02-20 22:40 UTC, kylehickinson commented on ios/brave-ios/Sources/DataImporter/UI/DataImporterView.swift
> +          isPresented: $model.isLoadingProfiles,
These sheets are explicitly associated with the main view only it seems? Is that correct? If for instance the import state is any causing any of the other views to appear the sheets will be dismissed, should these go on the container view instead?

2025-02-20 22:40 UTC, kylehickinson commented on ios/brave-ios/Sources/DataImporter/UI/DataImporterView.swift
> +                })
As Per DM you can't leave one condition empty, need to return the view provided as the closure is a ViewBuilder

2025-02-20 22:40 UTC, kylehickinson commented on ios/browser/api/password/importer/DEPS
> +]
EOF newline missing

2025-02-20 22:40 UTC, kylehickinson commented on ios/brave-ios/Sources/DataImporter/UI/DataImporterView.swift
> +        DataImporterStateView(kind: .success, model: model) {
There's something weird here about creating an entire switch across import states all to display the same View (`DataImporterStateView`) with almost identical modifiers with the only thing changing is Buttons? You also seem to combine both making this reusable and a "View only" kind of component and also passing in the model which means you're now checking specific things related to the logic of the feature.

Either you should have one view and you only pass in the model and adjust inside directly based on `importState`, or you don't pass in the model and make sure you can pass in all necessary info from here.

You also probably want to find a way to do this without multiple if-else causing the creation of completely separate views for each state

2025-02-20 22:41 UTC, kylehickinson commented on ios/brave-ios/Sources/DataImporter/UI/DataImporterStateView.swift
> +      }
It also probably shouldn't be part of the `ScrollView`

2025-02-20 23:00 UTC, kylehickinson commented
<img width="874" alt="image" src="https://github.com/user-attachments/assets/c32c60cc-9d51-42a6-83cb-144ecf254047" />

This final page also doesnt match design

2025-02-21 00:35 UTC, Brandon-T commented on ios/brave-ios/Sources/DataImporter/UI/DataImporterView.swift
> +        DataImporterStateView(kind: .success, model: model) {
Switched them all to separate views.

2025-02-21 00:36 UTC, Brandon-T commented on ios/brave-ios/Sources/DataImporter/UI/DataImporterStateView.swift
> +      }
This view doesn't have a scroll-view.

2025-02-21 14:14 UTC, kylehickinson commented on ios/brave-ios/Sources/DataImporter/Models/DataImportModel.swift
> +        }
You're already in an async method, just do `try await Task.sleep(...)` directly in it

2025-02-21 14:15 UTC, kylehickinson commented on ios/brave-ios/Sources/DataImporter/Models/DataImportModel.swift
> +        }
Same as above

2025-02-26 16:54 UTC, kylehickinson commented on ios/brave-ios/Sources/DataImporter/DataImporterStrings.swift
> +      tableName: "DataImporter",
This is still not addressed

2025-02-26 16:56 UTC, kylehickinson commented on ios/brave-ios/Sources/DataImporter/UI/BraveDataImporterMultipleProfilesView.swift
> +          Image(braveSystemName: "leo.close")
This is not addressed

2025-02-26 18:16 UTC, Brandon-T commented on ios/brave-ios/Sources/DataImporter/UI/BraveDataImporterMultipleProfilesView.swift
> +          Image(braveSystemName: "leo.close")
It is. I think Github is busted here. I checked the same file and it's showing this:

<img width="323" alt="image" src="https://github.com/user-attachments/assets/d63387b4-4198-45ee-b2e7-646a0ec8b2b8" />

2025-02-26 18:55 UTC, Brandon-T commented on ios/brave-ios/Sources/DataImporter/UI/DataImporterMultipleProfilesView.swift
>        )
Fixed: https://github.com/brave/brave-core/pull/26914/commits/a42dc5e72ab75bc6560707dc5ab8a79df789ae56 and https://github.com/brave/brave-core/pull/26914/commits/e81d63eaed80ec7f1ca97f0e0adcf0d34c4bc73e

2025-02-26 18:56 UTC, Brandon-T commented on ios/brave-ios/Sources/DataImporter/UI/DataImporterPasswordConflictView.swift
>          }
Fixed: https://github.com/brave/brave-core/pull/26914/commits/a42dc5e72ab75bc6560707dc5ab8a79df789ae56 and https://github.com/brave/brave-core/pull/26914/commits/e81d63eaed80ec7f1ca97f0e0adcf0d34c4bc73e

2025-02-26 18:57 UTC, Brandon-T commented on ios/brave-ios/Sources/DataImporter/DataImporterStrings.swift
> +      tableName: "DataImporter",
Fixed: https://github.com/brave/brave-core/pull/26914/commits/6a14a093f794a9929bee1d439a36468aa72f1257

2025-02-28 05:41 UTC, merged

2025-02-28 08:36 UTC, brave-builds commented
Released in [v1.78.5](https://github.com/brave/brave-browser/releases/tag/v1.78.5)