[iOS] Prepare CWVWebView web embedder for use in iOS
brave/brave-core pull request #26957
Opened 2024-12-10 18:15 UTC by kylehickinson

This is the split-up contents of https://github.com/brave/brave-core/pull/24657. This PR in particular only adds the `CWVWebView` API and exposes it to the iOS app but does not actually contain the code that _uses_ `CWVWebView` in the iOS app.  There is a shell target added (`WebShell`) for simple tests, for more comprehensive tests involving multiple tabs, please use the [`ios-cwvwebview-impl` branch](https://github.com/brave/brave-core/tree/ios-cwvwebview-impl)

Resolves

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2024-12-13 21:00 UTC, Brandon-T approved these changes

2025-01-27 23:06 UTC, bridiver commented on chromium_src/ios/CPPLINT.cfg
> +filter=-readability/casting,-whitespace/parens,-whitespace/operators
why do we have an issue with this if upstream doesn't have it in their config?

2025-01-27 23:09 UTC, bridiver commented on chromium_src/ios/chrome/browser/https_upgrades/model/DEPS
> +  "+brave/ios/browser/application_context",
this can probably go in `chromium_src/ios/chrome/browser/DEPS`

2025-01-27 23:12 UTC, bridiver commented on patches/ios-web_view-public-cwv_navigation_delegate.h.patch
> ++- (BOOL)webView:(CWVWebView*)webView shouldBlockUniversalLinksForRequest:(NSURLRequest*)request;
```
#define webViewWebContentProcessDidTerminate webView:(CWVWebView*)webView didRequestHTTPAuthForProtectionSpace... rest of methods we add... webViewWebContentProcessDidTerminate
```

2025-01-27 23:17 UTC, kylehickinson commented on chromium_src/ios/CPPLINT.cfg
> +filter=-readability/casting,-whitespace/parens,-whitespace/operators
Im not sure, we have the same issue in our own `ios` folder https://github.com/brave/brave-core/blob/master/ios/CPPLINT.cfg

2025-01-27 23:37 UTC, bridiver commented on patches/ios-web_view-internal-cwv_web_view.mm.patch
> ++  BRAVE_NOP_SERVICE
can we override `AutofillAgent` to be a no-op?

2025-01-27 23:42 UTC, bridiver commented on patches/ios-web_view-internal-cwv_web_view.mm.patch
> ++  BRAVE_ATTACH_TAB_HELPERS
why are we attaching general tab helpers here? Shouldn't this happen automatically through `BrowserWebStateListDelegate` if we are adding them in upstream `AttachTabHelpers`?

2025-01-27 23:43 UTC, bridiver commented on patches/ios-web_view-internal-cwv_web_view.mm.patch
> ++  BRAVE_NOP_SERVICE
same as below

2025-01-27 23:48 UTC, bridiver commented on patches/ios-web_view-public-cwv_web_view.h.patch
> ++@property(nonatomic, readonly, nullable) NSURL* visibleURL;
why do we need this to be nullable?

2025-01-28 14:46 UTC, kylehickinson commented on patches/ios-web_view-internal-cwv_web_view.mm.patch
> ++  BRAVE_ATTACH_TAB_HELPERS
None of the `ios/web_view` parts go through `Browser`/`WebStateList`

2025-01-28 14:47 UTC, kylehickinson commented on patches/ios-web_view-public-cwv_web_view.h.patch
> ++@property(nonatomic, readonly, nullable) NSURL* visibleURL;
Answered in old PR https://github.com/brave/brave-core/pull/24657#discussion_r1752855600

2025-01-28 19:02 UTC, bridiver commented on chromium_src/ios/CPPLINT.cfg
> +filter=-readability/casting,-whitespace/parens,-whitespace/operators
what specifically is triggering it?

2025-01-28 19:42 UTC, kylehickinson commented on ios/brave-ios/App/WebShell/ContentView.swift
> +class WebViewModel: ObservableObject {
Sorry this was just thrown together to demonstrate the `CWVWebView` in a small shell app. This code specifically model glue for SwiftUI so the shell UI updates properly when observable properties change

2025-01-28 20:19 UTC, bridiver approved these changes
follow-ups as discussed

2025-01-28 20:20 UTC, bridiver requested changes
moving to request changes to undo the accidental approval :)

2025-01-29 20:54 UTC, bridiver commented on ios/brave-ios/App/WebShell/ContentView.swift
> +class WebViewModel: ObservableObject {
oic, this was the thing I was asking about to run

2025-01-30 16:23 UTC, kylehickinson commented on chromium_src/ios/CPPLINT.cfg
> +filter=-readability/casting,-whitespace/parens,-whitespace/operators
```src/brave/chromium_src/ios/web_view/internal/cwv_web_view_configuration_internal.h:34:  (cpplint) Using C-style cast.  Use reinterpret_cast<CWVWebView*>(...) instead  [readability/casting] [4]
src/brave/chromium_src/ios/web_view/internal/cwv_web_view_internal.h:15:  (cpplint) Using C-style cast.  Use reinterpret_cast<NSData*>(...) instead  [readability/casting] [4]
** Presubmit Messages: 1 **
```

The actual lines it references don't make sense. For instance the first one is just a standard Obj-C method:

```- (void)registerWebView:(CWVWebView*)webView;```

2025-01-31 17:28 UTC, bridiver commented on patches/ios-chrome-browser-https_upgrades-model-https_only_mode_upgrade_tab_helper.mm.patch
> ++      !navigation_is_post_ && !(navigation_transition_type_ & ui::PAGE_TRANSITION_FORWARD_BACK)) {
please use `BRAVE_*` here so comments can be added explaining what we're doing (and also add comments :) 
It also makes it easier to see that we made a change

2025-01-31 17:28 UTC, bridiver commented on chromium_src/ios/CPPLINT.cfg
> +filter=-readability/casting,-whitespace/parens,-whitespace/operators
cc @goodov if you have any ideas?

2025-01-31 17:32 UTC, bridiver commented on ios/web_view/sources.gni
> +# - Excludes the bundled resources since these are already bundled
what do you mean "they are already bundled"? Where does that happen?

2025-01-31 17:45 UTC, kylehickinson commented on ios/web_view/sources.gni
> +# - Excludes the bundled resources since these are already bundled
These are resources already copied in by our prior setup: 
https://source.chromium.org/chromium/chromium/src/+/main:ios/chrome/app/resources/BUILD.gn;l=87

2025-01-31 18:17 UTC, kylehickinson commented on patches/ios-chrome-browser-https_upgrades-model-https_only_mode_upgrade_tab_helper.mm.patch
> ++      !navigation_is_post_ && !(navigation_transition_type_ & ui::PAGE_TRANSITION_FORWARD_BACK)) {
fixed in https://github.com/brave/brave-core/pull/26957/commits/ec3db3f79a25a5a762215dadb6bd0fd7381427e6

2025-02-05 22:27 UTC, bridiver commented on chromium_src/ios/chrome/browser/https_upgrades/model/https_only_mode_upgrade_tab_helper.mm
> +  !base::FeatureList::IsEnabled(net::features::kBraveHttpsByDefault) && \
this feature check should be inside `CanUpgradeToHTTPS`

2025-02-05 22:27 UTC, bridiver commented on chromium_src/ios/chrome/browser/https_upgrades/model/https_only_mode_upgrade_tab_helper.mm
> +  !(prefs_ && prefs_->GetBoolean(prefs::kHttpsUpgradesEnabled)
there's no per-site control on this like desktop? Just global enable/disable?

2025-02-05 22:28 UTC, bridiver commented on patches/ios-web-web_state-ui-wk_web_view_configuration_provider.patch
> ++  BRAVE_RESET_WITH_WEB_VIEW_CONFIGURATION
I thought we were going to subclass for this?

2025-02-05 22:31 UTC, bridiver commented on patches/ios-chrome-browser-https_upgrades-model-https_only_mode_upgrade_tab_helper.mm.patch
> ++      !navigation_is_post_ BRAVE_EXCLUDE_BACKFORWARD_NAVS) {
chromium doesn't cover back/forward navigations? Since it was already upgraded on the original navigation, shouldn't it skip this? `Upgrade to HTTPS if the navigation wasn't upgraded before`

2025-02-05 22:32 UTC, bridiver commented on ios/web_view/internal/web_view_global_state_util_stub.mm
> +// Copyright (c) 2024 The Brave Authors. All rights reserved.
why does the filename have `_stub`?

2025-02-05 22:34 UTC, bridiver commented on ios/web_view/internal/cwv_web_view_extras.mm
> +// Converts base::Value expected to be a dictionary or list to NSDictionary or
this looks like copied code? What's going on here? We really need more explanation in the comments for these classes in general so people can understand what we're doing

2025-02-05 22:53 UTC, kylehickinson commented on patches/ios-chrome-browser-https_upgrades-model-https_only_mode_upgrade_tab_helper.mm.patch
> ++      !navigation_is_post_ BRAVE_EXCLUDE_BACKFORWARD_NAVS) {
They dont cover this in their tab helper properly, no.

2025-02-05 22:54 UTC, kylehickinson commented on patches/ios-web-web_state-ui-wk_web_view_configuration_provider.patch
> ++  BRAVE_RESET_WITH_WEB_VIEW_CONFIGURATION
No the goal was to use the observer for this but it turned out there's no way to add the observer early enough to catch the first configuration creation. I can see if its possible to somehow subclass this though

2025-02-05 22:55 UTC, kylehickinson commented on chromium_src/ios/chrome/browser/https_upgrades/model/https_only_mode_upgrade_tab_helper.mm
> +  !(prefs_ && prefs_->GetBoolean(prefs::kHttpsUpgradesEnabled)
No per-site control for HTTPS-upgrade on iOS

2025-02-05 22:56 UTC, kylehickinson commented on ios/web_view/internal/web_view_global_state_util_stub.mm
> +// Copyright (c) 2024 The Brave Authors. All rights reserved.
Just stubs out the `InitializeGlobalState` method so I added `_stub` but I can remove that

2025-02-05 22:57 UTC, kylehickinson commented on ios/web_view/internal/cwv_web_view_extras.mm
> +// Converts base::Value expected to be a dictionary or list to NSDictionary or
Yeah sorry this part is indeed copied, I may be able to fix that though if I can expose the C methods that are in `cwv_web_view.mm`: https://source.chromium.org/chromium/chromium/src/+/main:ios/web_view/internal/cwv_web_view.mm;l=99

This code is temporary though, until we can convert all of our JavaScript Swift code into Chromium's `JavaScriptFeature`

2025-02-05 23:06 UTC, kylehickinson commented on patches/ios-web_view-public-cwv_web_view.h.patch
> ++@property(nonatomic, readonly, nullable) NSURL* visibleURL;
This is now upstreamed so this patch will eventually go away

2025-02-11 20:46 UTC, kylehickinson commented on ios/web_view/internal/cwv_web_view_extras.mm
> +// Converts base::Value expected to be a dictionary or list to NSDictionary or
fixed in https://github.com/brave/brave-core/pull/26957/commits/9d5aa25a1c1833fc615f7699454686a18e7b8655

2025-02-11 20:48 UTC, kylehickinson commented on chromium_src/ios/chrome/browser/https_upgrades/model/https_only_mode_upgrade_tab_helper.mm
> +  !base::FeatureList::IsEnabled(net::features::kBraveHttpsByDefault) && \
The `kHttpsUpgrades` override doesn't call `CanUpgradeToHTTPS`

2025-02-12 14:24 UTC, kylehickinson commented on ios/web_view/internal/web_view_global_state_util_stub.mm
> +// Copyright (c) 2024 The Brave Authors. All rights reserved.
fixed in https://github.com/brave/brave-core/pull/26957/commits/b21aacfbfbc91e4701cabf59cff6ca37c078f4e6

2025-02-12 14:24 UTC, kylehickinson commented on patches/ios-web-web_state-ui-wk_web_view_configuration_provider.patch
> ++  BRAVE_RESET_WITH_WEB_VIEW_CONFIGURATION
fixed in https://github.com/brave/brave-core/pull/26957/commits/de45e48ba436e00fffcead74f84106b87874bc44

2025-02-12 16:20 UTC, bridiver commented on chromium_src/ios/chrome/browser/https_upgrades/model/https_only_mode_upgrade_tab_helper.mm
> +  !base::FeatureList::IsEnabled(net::features::kBraveHttpsByDefault) && \
isn't it checked here? https://github.com/brave/brave-core/pull/26957/files#diff-9e16f61dee4e3c4f430cf50c177ab89da6db40727a5ca2e8fb7f13b3c0788a44R19

2025-02-12 16:20 UTC, bridiver commented on patches/ios-chrome-browser-https_upgrades-model-https_only_mode_upgrade_tab_helper.mm.patch
> ++      !navigation_is_post_ BRAVE_EXCLUDE_BACKFORWARD_NAVS) {
is that an upstream bug?

2025-02-12 16:26 UTC, kylehickinson commented on patches/ios-chrome-browser-https_upgrades-model-https_only_mode_upgrade_tab_helper.mm.patch
> ++      !navigation_is_post_ BRAVE_EXCLUDE_BACKFORWARD_NAVS) {
I believe so, yes. I had a chat with them in the Chromium Slack a while back and they confirmed they still had flows which triggered DCHECKs for this specific usage (which is currently disabled by default)

2025-02-12 16:30 UTC, kylehickinson commented on chromium_src/ios/chrome/browser/https_upgrades/model/https_only_mode_upgrade_tab_helper.mm
> +  !base::FeatureList::IsEnabled(net::features::kBraveHttpsByDefault) && \
I guess Im a bit confused here:
- We're overriding this spot to add a check for our feature flag since Chromium's is off by default: https://source.chromium.org/chromium/chromium/src/+/main:ios/chrome/browser/https_upgrades/model/https_only_mode_upgrade_tab_helper.mm;l=275
- `IsLocalhost` override below is what calls `CanUpgradeToHTTPS` above, which is only called after the feature flag check added by the `kHttpsUpgrades` override (same line as linked above)

I could add the check again to `CanUpgradeToHTTPS` but its already happened by the first override

2025-02-25 20:29 UTC, bridiver commented on chromium_src/ios/chrome/browser/https_upgrades/model/https_only_mode_upgrade_tab_helper.mm
> +  !base::FeatureList::IsEnabled(net::features::kBraveHttpsByDefault) && \
To be clear I'm talking about `HttpsUpgradeExceptionsService::CanUpgradeToHttps`, but the point is that making the feature check outside of `CanUpgradeToHTTPS` is fragile. If the feature flag is false then `HttpsUpgradeExceptionsService::CanUpgradeToHttps` return return false.

2025-02-25 20:46 UTC, bridiver commented on chromium_src/ios/chrome/browser/https_upgrades/model/https_only_mode_upgrade_tab_helper.mm
> +  &&!(navigation_transition_type_ & ui::PAGE_TRANSITION_FORWARD_BACK)
`&&!` -> `&& !`

2025-02-25 20:47 UTC, bridiver commented on patches/ios-chrome-browser-https_upgrades-model-https_only_mode_upgrade_tab_helper.mm.patch
> ++      !navigation_is_post_ BRAVE_EXCLUDE_BACKFORWARD_NAVS) {
can we add a unit test that covers this? There is `HttpsOnlyModeUpgradeTabHelperTest` so should be easy to create our own?

2025-02-25 20:48 UTC, kylehickinson commented on chromium_src/ios/chrome/browser/https_upgrades/model/https_only_mode_upgrade_tab_helper.mm
> +  &&!(navigation_transition_type_ & ui::PAGE_TRANSITION_FORWARD_BACK)
formatter does this

2025-02-25 20:49 UTC, kylehickinson commented on patches/ios-chrome-browser-https_upgrades-model-https_only_mode_upgrade_tab_helper.mm.patch
> ++      !navigation_is_post_ BRAVE_EXCLUDE_BACKFORWARD_NAVS) {
We currently dont support running Chromium unit tests on iOS

2025-02-25 20:51 UTC, bridiver commented on ios/web_view/public/cwv_web_view_extras.h
> +@interface CWVWebView (Extras)
why is this here, this seems to be a copy of the upstream file?

2025-02-25 20:51 UTC, bridiver commented on ios/web_view/public/cwv_ssl_status_extras.h
> +OBJC_EXPORT
same as below

2025-02-25 20:52 UTC, bridiver commented on ios/web_view/internal/web_view_global_state_util.mm
> +  // We already provide global initialization with BraveCoreMain
should we move it here?

2025-02-25 20:54 UTC, kylehickinson commented on ios/web_view/public/cwv_web_view_extras.h
> +@interface CWVWebView (Extras)
These are not copies of any upstream files, they provide additional support that is available via WebState but not available via CWVWebView

2025-02-25 20:57 UTC, bridiver commented on ios/web_view/public/cwv_web_view_extras.h
> +@interface CWVWebView (Extras)
sorry, actually this seems to have the methods from CRWWebController so it's not clear why they're on the webview here.

2025-02-25 20:58 UTC, bridiver commented on ios/web_view/public/cwv_web_view_extras.h
> +@interface CWVWebView (Extras)
whatever the reason, this kind of thing should definitely have comments explaining

2025-02-25 21:14 UTC, bridiver commented on ios/browser/api/web_view/universal_link_block_util.mm
> +bool ShouldBlockUniversalLinks(web::WebState* webState, NSURLRequest* request) {
it's also not clear to me how/why we're handling this differently than upstream. Also why is this implemented in `universal_link_block_util.mm` and defined in `wk_navigation_action_policy_util.h`? `ShouldBlockJavaScript` is also defined in `wk_navigation_action_policy_util.h` and implemented in a different file. This also doesn't seem like it belongs in `ios/browser/api`? Isn't that just for things we expose to swift?

2025-02-25 22:00 UTC, kylehickinson commented on ios/browser/api/web_view/universal_link_block_util.mm
> +bool ShouldBlockUniversalLinks(web::WebState* webState, NSURLRequest* request) {
fixed in https://github.com/brave/brave-core/pull/26957/commits/0bcc0de8685bed80111d84d52c00f00735fdba83

2025-02-25 23:09 UTC, bridiver commented on ios/brave-ios/App/WebShell/ContentView.swift
> +class WebViewModel: ObservableObject {
can you add comments explaining?

2025-02-25 23:10 UTC, bridiver commented on chromium_src/ios/chrome/browser/https_upgrades/model/https_only_mode_upgrade_tab_helper.mm
> +  &&!(navigation_transition_type_ & ui::PAGE_TRANSITION_FORWARD_BACK)
really? That's odd. Ok

2025-02-25 23:12 UTC, bridiver commented on chromium_src/ios/web/public/browser_state.h
> +  PrefService* GetPrefs() {   \
what is this for?

2025-02-25 23:15 UTC, bridiver commented on chromium_src/ios/web/web_state/ui/crw_web_controller.mm
> +  _navigationHandler =                                             \
`if (false)` so we don't actually initialize CRWWKNavigationHandler and throw it away, although maybe this gets optimized out?

2025-02-25 23:18 UTC, kylehickinson commented on chromium_src/ios/web/public/browser_state.h
> +  PrefService* GetPrefs() {   \
This was because the WebViewBrowserState previously exposed via CWVWebViewConfiguration has a GetPrefs method so we needed to create a method on the public definition for it to build. I'll add comments

2025-02-25 23:18 UTC, bridiver commented on ios/web_view/sources.gni
> +# - Excludes the bundled resources since these are already bundled
please add that to the comments

2025-02-25 23:19 UTC, bridiver commented on patches/ios-chrome-browser-https_upgrades-model-https_only_mode_upgrade_tab_helper.mm.patch
> ++      !navigation_is_post_ BRAVE_EXCLUDE_BACKFORWARD_NAVS) {
not chromium unit tests, I'm saying to create our own unit test based on that one

2025-02-25 23:19 UTC, kylehickinson commented on chromium_src/ios/web/web_state/ui/crw_web_controller.mm
> +  _navigationHandler =                                             \
Even if it does get initialized it'll just dealloc at the end of scope and it doesn't do anything in the initializer. I could add the `if(false)` check though if we want to be future proofed

2025-02-25 23:21 UTC, bridiver commented on ios/browser/api/content_settings/default_host_content_settings.h
> +typedef NS_ENUM(NSUInteger, DefaultPageMode) {
this seems to be identical to the upstream file?

2025-02-25 23:21 UTC, bridiver commented on ios/browser/api/content_settings/default_host_content_settings.mm
> +@implementation DefaultHostContentSettings {
same as above

2025-02-25 23:21 UTC, kylehickinson commented on patches/ios-chrome-browser-https_upgrades-model-https_only_mode_upgrade_tab_helper.mm.patch
> ++      !navigation_is_post_ BRAVE_EXCLUDE_BACKFORWARD_NAVS) {
This would still be a chromium based test I mean, using the chromium test infrastructure to setup and test a tab helper

2025-02-25 23:22 UTC, bridiver commented on ios/browser/api/content_settings/BUILD.gn
> +source_set("content_settings") {
see below, why are we creating a duplicate target for this?

2025-02-25 23:22 UTC, kylehickinson commented on ios/browser/api/content_settings/default_host_content_settings.h
> +typedef NS_ENUM(NSUInteger, DefaultPageMode) {
I don't believe we can expose the upstream file since its not a public header so it'll have relative path includes and C++ types

2025-02-26 17:40 UTC, bridiver commented on chromium_src/ios/web/public/browser_state.h
> +  PrefService* GetPrefs() {   \
this should probably be `NOTREACHED()` then instead of returning nullptr?

2025-02-26 17:40 UTC, bridiver commented on chromium_src/ios/web/web_state/ui/crw_web_controller.mm
> +  _navigationHandler =                                             \
I understand it will be dealloced, but we shouldn't create it in the first place since we don't need it

2025-02-26 17:42 UTC, bridiver commented on chromium_src/ios/web_view/internal/cwv_web_view_configuration.mm
> +  NOTIMPLEMENTED();
should use `NOTREACED()` if we never intend this to be called

2025-02-26 17:44 UTC, bridiver commented on chromium_src/ios/web_view/internal/cwv_web_view_configuration_internal.h
> +// We completely replace the CWVWebViewConfiguration implementation so that
this comment is in kind of a strange place, it should right above the interface declaration, but it's not clear to me why we need to override the header file here, Replacing the implementation only requires overriding the cc file

2025-02-26 17:44 UTC, bridiver commented on chromium_src/ios/web_view/internal/cwv_web_view_internal.h
> +
nit: remove blank line

2025-02-26 17:46 UTC, kylehickinson commented on chromium_src/ios/web_view/internal/cwv_web_view_configuration_internal.h
> +// We completely replace the CWVWebViewConfiguration implementation so that
We need to override the header file because the header file is what's defining the types which we need replaced: https://source.chromium.org/chromium/chromium/src/+/main:ios/web_view/internal/cwv_web_view_configuration_internal.h;l=23;bpv=0;bpt=1

2025-02-26 17:47 UTC, kylehickinson commented on chromium_src/ios/web/web_state/ui/crw_web_controller.mm
> +  _navigationHandler =                                             \
The `if(false)` check was added in the last commit, forgot to mention it https://github.com/brave/brave-core/pull/26957/commits/6ce599224697cb68893f07642955023dec9cfb06

2025-02-26 17:48 UTC, kylehickinson commented on chromium_src/ios/web/public/browser_state.h
> +  PrefService* GetPrefs() {   \
I can add `NOTREACHED` to it yeah

2025-02-26 17:50 UTC, bridiver commented on chromium_src/ios/web_view/internal/cwv_web_view_configuration.mm
> +
nit: remove empty line

2025-02-26 17:55 UTC, bridiver commented on chromium_src/ios/web_view/internal/cwv_web_view.mm
> ++ (id)objectFromValue:(const base::Value*)value {
why does this need to be a method on CWVWebView? Can't we just use `NSObjectFromValue` directly?

2025-02-26 18:26 UTC, bridiver commented on chromium_src/ios/web_view/internal/cwv_web_view.mm
> ++ (id)objectFromValue:(const base::Value*)value {
I think we should keep the same name and not drop NS?

2025-02-26 18:28 UTC, bridiver commented on patches/ios-chrome-browser-https_upgrades-model-https_only_mode_upgrade_tab_helper.mm.patch
> ++      !navigation_is_post_ BRAVE_EXCLUDE_BACKFORWARD_NAVS) {
I see, do we have an issue open to get unit tests working?

2025-02-26 18:31 UTC, bridiver commented on ios/web_view/headers.gni
> +
empty line?

2025-02-26 18:32 UTC, bridiver commented on ios/browser/web/brave_web_main_parts.mm
> +// Copyright (c) 2019 The Brave Authors. All rights reserved.
we backdated it?

2025-02-26 18:34 UTC, bridiver commented on ios/browser/api/content_settings/default_host_content_settings.h
> +typedef NS_ENUM(NSUInteger, DefaultPageMode) {
I don't see any other headers in default_page_mode.h

2025-02-26 18:37 UTC, bridiver commented on chromium_src/ios/web_view/internal/cwv_web_view_configuration_internal.h
> +// We completely replace the CWVWebViewConfiguration implementation so that
we can't chromium_src override `ios_web_view` -> `web` and `WebViewBrowserState` -> `BrowserState`?

2025-02-26 19:00 UTC, kylehickinson commented on chromium_src/ios/web_view/internal/cwv_web_view_configuration_internal.h
> +// We completely replace the CWVWebViewConfiguration implementation so that
No because the `initWithBrowserState` method takes a `unique_ptr` which we don't want as we're passing in `ChromeBrowserState`

2025-02-26 19:01 UTC, kylehickinson commented on chromium_src/ios/web_view/internal/cwv_web_view.mm
> ++ (id)objectFromValue:(const base::Value*)value {
It'd be against typical Obj-C naming conventions, you don't include the class prefixes in the method naming

2025-02-26 19:02 UTC, kylehickinson commented on ios/web_view/headers.gni
> +
To separate the //brave specific extras and the headers coming from Chromium's //ios/web_view

2025-02-26 19:02 UTC, kylehickinson commented on ios/browser/web/brave_web_main_parts.mm
> +// Copyright (c) 2019 The Brave Authors. All rights reserved.
This file was moved into the web subdirectory to match chromium, but its been around since 2019

2025-02-26 19:05 UTC, kylehickinson commented on ios/browser/api/content_settings/default_host_content_settings.h
> +typedef NS_ENUM(NSUInteger, DefaultPageMode) {
Either way I don't want to use that directly, since this type–while duplicated–is explicitly for this Obj-C wrapper, and isn't actually used to interact with any of Chromium's APIs expecting that enum (simply using it for `CONTENT_SETTING_ALLOW`/`CONTENT_SETTING_BLOCK`

2025-02-26 20:40 UTC, bridiver commented on chromium_src/ios/web_view/internal/cwv_web_view.mm
> ++ (id)objectFromValue:(const base::Value*)value {
this is effectively private since it's internal, right? It can only be used within CWVWebView?

2025-02-26 20:40 UTC, bridiver commented on chromium_src/ios/web_view/internal/cwv_web_view_configuration_internal.h
> +// We completely replace the CWVWebViewConfiguration implementation so that
I see, ok

2025-02-26 20:50 UTC, bridiver commented on ios/web_view/internal/cwv_web_view_extras.mm
> +- (WKWebView*)underlyingWebView {
why aren't we just exposing the `CRWWebController` as an attribute and then we can also use that for `createPDF`, etc...

2025-02-26 21:28 UTC, bridiver commented on ios/web_view/internal/cwv_web_view_extras.mm
> +- (void)createPDF:(void (^)(NSData* _Nullable))completionHandler {
`createFullPagePdf` to match upstream method. It's much easier to find things when names match

2025-02-26 21:31 UTC, kylehickinson commented on ios/browser/web/brave_web_client.mm
> +  features.push_back(translate::TranslateJavaScriptFeature::GetInstance());
We actually are now but not through `JavaScriptFeature`, this is actually supposed to be removed though until we can properly support it as a `JavaScriptFeature`

2025-02-26 21:32 UTC, kylehickinson commented on ios/web_view/internal/cwv_web_view_extras.mm
> +- (WKWebView*)underlyingWebView {
As per DM:
- We don't want to expose `CRWWebController` as its essentially the `WKWebView` handler, which we want to avoid using and overtime will use it less (for when we eventually can support a `use_blink` build)
- We can't expose `CRWWebController` as-is, would have to wrap it anyways

2025-02-26 21:34 UTC, bridiver commented on ios/web_view/internal/cwv_web_view_extras.mm
> +- (WKWebView*)underlyingWebView {
discussed in DM, but maybe this should be `internalWebView` or something?

2025-02-26 21:58 UTC, kylehickinson commented on chromium_src/ios/web_view/internal/cwv_web_view.mm
> ++ (id)objectFromValue:(const base::Value*)value {
Correct

2025-02-26 21:58 UTC, bridiver approved these changes
lgtm after removing https upgrade code that needs fixes in desktop first

2025-02-27 17:01 UTC, merged

2025-02-28 00:04 UTC, brave-builds commented
Released in [v1.78.4](https://github.com/brave/brave-browser/releases/tag/v1.78.4)