[Webcompat report dialog] Hidden "Send" button if reported URL is too long
brave/brave-core pull request #27063
Opened 2024-12-18 21:30 UTC by vadimstruts

Resolves https://github.com/brave/brave-browser/issues/42902

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2024-12-18 22:38 UTC, brave-builds commented
A Storybook has been deployed to [preview UI for the latest push](https://build-artifacts.brave.com/brave-browser-build-pr/42902-webcompat-report-dialog-hidden-send-button-if-reported-url-is-too-long/storybook.html)

2025-01-02 22:32 UTC, DJAndries requested changes

2025-01-02 22:32 UTC, DJAndries commented on components/webcompat_reporter/ui/components/ShortenedUrl.tsx
> +            </NonInteractiveURL>)
ending parenthesis should be on a new line

2025-01-02 22:32 UTC, DJAndries commented on components/webcompat_reporter/ui/components/ShortenedUrl.tsx
> +        const partLength = Math.floor((maxLength - dots.length) / 2)
can't we set some CSS if the URL length hits the threshold?

i.e.
```
text-overflow: ellipsis;
white-space: nowrap;
```

2025-01-02 22:32 UTC, DJAndries commented on components/webcompat_reporter/ui/components/ShortenedUrl.tsx
> +        interactive: false
since the `interactive` prop is not used, should we get rid of the prop, and any logic that depends on it being true?

2025-01-02 22:32 UTC, DJAndries commented on browser/ui/webui/webcompat_reporter/webcompat_reporter_ui.cc
> +void WebcompatReporterUI::OnWidgetBoundsChanged(views::Widget* widget,
does this get called repeatedly (at a rapid rate) during the resize, or does it get called once when the resize is complete? if it's the former, perhaps we should debounce the logic. alternatively, we could just scrap the resize logic, keep a static height, and just show a scrollbar if the contents overflow.

2025-01-06 10:38 UTC, vadimstruts commented on components/webcompat_reporter/ui/components/ShortenedUrl.tsx
> +        const partLength = Math.floor((maxLength - dots.length) / 2)
My idea was to have dots in the middle of the shortened link ex: `https://example.com/dir/...../page.html`
without calculations like this: `const partLength = Math.floor((maxLength - dots.length) / 2)`
we can have dots just at the end of link: `https://example.com/dir/.....`

2025-01-06 11:11 UTC, vadimstruts commented on browser/ui/webui/webcompat_reporter/webcompat_reporter_ui.cc
> +void WebcompatReporterUI::OnWidgetBoundsChanged(views::Widget* widget,
It is first case (I should say that call frequency does not depend from how fast you resize the window because the every step coordinate deviation is increasing) 
>just show a scrollbar if the contents overflow.

It is all that I added, as you can see on the video, ( here you can see the main problem from the user: https://github.com/brave/brave-browser/issues/42902#issuecomment-2545999987)
But there is no support of the resize  for the dialogs based on ConstrainedWebDialogUI. The dialog content just doesn't know that size has been changed at all. It is why I had to handle it in that way. If I remove that logic, the main issue will not be fixed.

2025-01-06 11:13 UTC, vadimstruts commented on components/webcompat_reporter/ui/components/ShortenedUrl.tsx
> +        interactive: false
fixed

2025-01-06 17:22 UTC, DJAndries commented on browser/ui/webui/webcompat_reporter/webcompat_reporter_ui.cc
> +void WebcompatReporterUI::OnWidgetBoundsChanged(views::Widget* widget,
> But there is no support of the resize for the dialogs based on ConstrainedWebDialogUI. The dialog content just doesn't know that size has been changed at all. It is why I had to handle it in that way. If I remove that logic, the main issue will not be fixed.

understood, thanks

2025-01-06 21:42 UTC, DJAndries commented on components/webcompat_reporter/ui/components/ShortenedUrl.tsx
> +        const partLength = Math.floor((maxLength - dots.length) / 2)
why not just show the full URL, now that we have the ability to scroll within the dialog? the ellipsis in the middle of the URL seems strange to me. curious to hear thoughts about this from others cc @ShivanKaul

2025-01-06 22:06 UTC, ShivanKaul commented on components/webcompat_reporter/ui/components/ShortenedUrl.tsx
> +        const partLength = Math.floor((maxLength - dots.length) / 2)
Hmm, if we can just scroll within the dialog, that sounds better than having an ellipsis.

2025-01-07 01:21 UTC, antonok-edm approved these changes
+1 to including full URL instead of ellipsis, or at least the max length could be increased quite a bit.

Otherwise LGTM

2025-01-07 12:05 UTC, vadimstruts commented on components/webcompat_reporter/ui/components/ShortenedUrl.tsx
> +        const partLength = Math.floor((maxLength - dots.length) / 2)
removed the ellipsis

2025-01-07 23:37 UTC, DJAndries approved these changes

2025-01-10 12:53 UTC, merged

2025-01-10 16:07 UTC, brave-builds commented
Released in [v1.76.6](https://github.com/brave/brave-browser/releases/tag/v1.76.6)