Warning text if the user has currently selected Block all cookies
brave/brave-core pull request #27090
Opened 2024-12-24 02:17 UTC by vadimstruts

Resolves https://github.com/brave/brave-browser/issues/42295

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2024-12-30 23:33 UTC, Brandon-T approved these changes

2025-01-02 22:44 UTC, DJAndries commented on components/webcompat_reporter/browser/fields.h
> +inline constexpr char kBlockScriptsField[] = "block_scripts";
I will add these fields on the server-side. Please remember to update https://github.com/brave/brave-browser/wiki/Web-compatibility-reports

2025-01-03 05:56 UTC, DJAndries requested changes

2025-01-03 05:56 UTC, DJAndries commented on components/webcompat_reporter/browser/webcompat_report_uploader.cc
> +                            report_info->block_scripts.value());
please use a bool instead

2025-01-03 20:03 UTC, deeppandya approved these changes
LGTM

2025-01-05 13:36 UTC, vadimstruts commented on components/webcompat_reporter/browser/webcompat_report_uploader.cc
> +                            report_info->block_scripts.value());
fixed

2025-01-06 16:27 UTC, DJAndries approved these changes
looks great, thanks

2025-01-06 16:29 UTC, DJAndries commented on browser/webcompat_reporter/webcompat_reporter_service_delegate.cc
> +WebcompatReporterServiceDelegateImpl::GetScriptBlockingFlag() const {
should we return a bool here?

2025-01-06 18:40 UTC, vadimstruts commented on browser/webcompat_reporter/webcompat_reporter_service_delegate.cc
> +WebcompatReporterServiceDelegateImpl::GetScriptBlockingFlag() const {
It is related to the `struct ReportInfo` defined here: [webcompat_reporter.mojom](https://github.com/brave/brave-core/pull/27090/files#diff-08e730be6b9896febb3f99829390ddaebaf9d4160ecbff59d62dfd1e616b08c2R28)
As you can see all properties are optional, because we can fill each of them on back-end or on the front-end, or skip at all (in that case the property will not be included into the report). 
And we can not use something like `bool? block_scripts;` because it does not allowed in mojo, so I used `string`.
The `WebcompatReporterServiceDelegateImpl::GetScriptBlockingFlag()` returns `std::optional<std::string>` to skip converting `bool ->string` later.
When the `WebcompatReporterServiceDelegateImpl::GetScriptBlockingFlag()` doesn't have any value to return, It just returns the `std::nullopt` to not include that field into the report at all.

2025-01-07 14:31 UTC, mkarolin commented on app/brave_settings_strings.grdp
> +  </message>
The `To force-enable, Learn more` part doesn't look right to me. Also, because this warning is shown with the setting itself, I don't think repeating `Block all cookies` is necessary. I would suggest perhaps:

```
This option is deprecated. <link>Learn how to force-enable</link>
```
cc: @rmcfadden3 WDYT?

2025-01-07 14:32 UTC, mkarolin commented on browser/ui/android/strings/android_brave_strings.grd
> +      </message>
Same as the desktop.

2025-01-07 22:32 UTC, rmcfadden3 commented on app/brave_settings_strings.grdp
> +  </message>
@mkarolin how about `The "Block all Cookies" option has been deprecated. To learn how to force-enable this option, visit [our help page](https://support.brave.com/).`

Note that I just used the general support.brave.com link as a placeholder on the href. We should obviously embed the exact URL once we have it.

If the goal is to send someone to Flags or something, rather than help center, LMK and I can tweak the copy accordingly.

2025-01-07 22:48 UTC, mkarolin commented on app/brave_settings_strings.grdp
> +  </message>
Thanks @rmcfadden3! Sounds good to me.

2025-01-08 16:38 UTC, vadimstruts commented on browser/ui/android/strings/android_brave_strings.grd
> +      </message>
I updated strings & screenshots above

2025-01-08 16:49 UTC, mkarolin commented on app/brave_settings_strings.grdp
> +  </message>
It is not great for localization when a sentence is split up between strings. It is better to use placeholders like you have in the Android file, but it should be all in one string (both here and in the Android file).

2025-01-08 19:42 UTC, mkarolin commented on browser/ui/android/strings/android_brave_strings.grd
> +      </message>
Sorry, @vadimstruts but can you merge these into one <message> as well?

2025-01-08 23:05 UTC, vadimstruts commented on browser/ui/android/strings/android_brave_strings.grd
> +      </message>
Yeah, thanks, I missed it. Done

2025-01-08 23:29 UTC, mkarolin approved these changes
`strings`++ Thanks!

2025-01-10 12:49 UTC, merged

2025-01-10 16:07 UTC, brave-builds commented
Released in [v1.76.6](https://github.com/brave/brave-browser/releases/tag/v1.76.6)