Prevent UI elements from overlapping in History page
brave/brave-core pull request #5703
Opened 2020-06-01 21:12 UTC by victorhmp

Removed unnecessary `z-index` property from `page-search_label` CSS class used by the `br-toolbar-search-field` ui element.

This prevents the `br_toolbar_search_field` label from being visible to users when they've selected history items and an overlay is visible. Which looked buggy, since the icon would overlap the options inside of the overlay, but also created a possible UX issue, since users might think that they could search while having history items selected, but if they try to, it would result in unexpected behavior.

The issue is best described as a comment I made over at https://github.com/brave/brave-browser/issues/8882#issuecomment-636346630.

Resolves https://github.com/brave/brave-browser/issues/8882

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:

1. Go to brave://history;
2. Select any item in your history and you should see an overlay in the top of the page with the options to `Delete` or `Cancel` your selection;
3. Notice that the search icon is not being shown, as it is in the current Stable version;
4. Navigate to other sections such as `Settings` and `Downloads` to check if everything is looking OK in the menu-bar.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

2020-07-07 22:06 UTC, petemill commented
Thanks so much for digging in to the issue and finding a fix. Sorry for the extended delay. This is on my list and I'll review ASAP.

2020-12-03 17:51 UTC, bsclifton commented
yikes - sorry for keeping you hanging here for so long. I created https://github.com/brave/brave-core/pull/7329 so that we can let CI run. I'll check this out now 👍

2020-12-04 06:29 UTC, bsclifton commented
@victorhmp I tested out right now and while it does solve the problem w/ History page it makes the magnifying glass unclickable on Downloads and Bookmarks pages. So the Z index is needed there. Is there a different solution we can try?

2020-12-04 06:30 UTC, bsclifton requested changes
See comments above

2023-11-10 06:24 UTC, closed without merging