[WIP] Asan for brave-core
brave/brave-core pull request #6526
Opened 2020-08-28 05:45 UTC by jumde

Resolves 

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

2020-09-21 21:44 UTC, bridiver commented on build/commands/lib/config.js
> +    is_debug: this.isDebug() && !this.buildAsan(),
I don't think this is necessary, this is enforced by gn

2020-09-21 21:45 UTC, bridiver commented on build/commands/lib/config.js
> +    is_asan: this.buildAsan(),
```
if (this.isAsan) {
   args.is_asan = ...
```

2020-09-21 21:45 UTC, bridiver commented on build/commands/lib/config.js
> +  if (options.asan) {
please keep the option names consistent with chromium `asan` -> `is_asan`

2020-09-24 13:22 UTC, iefremov approved these changes

2020-09-24 17:31 UTC, bsclifton approved these changes
LGTM! 😄

2020-09-25 19:20 UTC, bridiver commented on build/commands/scripts/commands.js
> +  .option('--run_disabled', 'run disabled tests')
`run_disabled_tests` for consistency

2020-09-25 19:20 UTC, bridiver approved these changes

2020-09-29 09:44 UTC, tmancey commented on components/brave_ads/test/BUILD.gn
> +      # https://github.com/brave/brave-browser/issues/11891
Fixed

2020-09-29 09:47 UTC, tmancey commented on components/brave_ads/test/BUILD.gn
> +      # https://github.com/brave/brave-browser/issues/11892
Resolved as part of 11891

2020-09-29 09:48 UTC, tmancey requested changes
Fixed issues related to ads, can you please rebase once merged so we can remove the checks? Thanks

2020-09-30 00:55 UTC, tmancey approved these changes
LGTM++

2020-09-30 05:06 UTC, NejcZdovc approved these changes

2020-10-01 19:32 UTC, merged