Explicitly cancel blocked requests
brave/brave-core pull request #6632
Opened 2020-09-12 04:12 UTC by spinda

Resolves brave/brave-browser#10063

Fixes, for example, video playback on https://abcnews.go.com/Politics/video/tennessee-celebrates-100-years-womens-vote-72455124, where returning an empty stub response for https://abcnewsplayer-a.akamaihd.net/player/2.106.5/akamai/amp/nielsen/Nielsen.min.js  causes another script to misbehave.

## Submitter Checklist:

- [x ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

2020-09-12 04:27 UTC, antonok-edm reviewed
@spinda You'll probably need to update some of the browsertests - there's at least one that uses an `$explicitcancel` rule in `components/brave_shields/browser/ad_block_service_browsertest.cc`

2020-09-14 09:08 UTC, iefremov commented on browser/net/url_context.h
> +  inline bool ShouldMockRequest() const {
no need to explicitly specify `inline`

2020-09-14 14:46 UTC, iefremov commented
also any new tests are welcome, especially browsertests :) The change looks good

2020-09-18 06:30 UTC, spinda commented
I ended up removing the `explicitcancel` test and updating the other tests so that they all expect resources to be blocked where they previously expected blank responses.

2020-10-13 06:16 UTC, bsclifton commented
cc: @iefremov for re-review 😄

2020-10-13 17:05 UTC, iefremov approved these changes

2020-10-15 06:36 UTC, bsclifton commented
@spinda could you give this a rebase? Sorry that it's taken a while to work through this PR ☹️

2020-10-29 05:51 UTC, spinda commented
Oops,

2020-10-30 19:40 UTC, pes10k requested changes
@spinda it looks like this needs to be rebased again?

2020-11-02 18:35 UTC, spinda commented
@pes10k Rebased again!

2020-11-02 18:58 UTC, pes10k approved these changes

2020-11-02 18:58 UTC, pes10k commented
Great! Thanks @spinda !  Once its been reviewed by @iefremov i think we're good to merge!

2020-11-02 19:02 UTC, merged

2020-11-02 19:02 UTC, pes10k commented
Merged!  Thanks again @spinda !