Fix debug build bug android
brave/brave-core pull request #6934
Opened 2020-10-22 22:47 UTC by deeppandya

Resolves https://github.com/brave/brave-browser/issues/12218

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [x] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`, `npm run gn_check`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.
- [ ] Added appropriate QA labels (`QA/Yes` or `QA/No`) to the associated issue
- [ ] Added appropriate release note labels (`release-notes/include` or `release-notes/exclude`) to the associated issue
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

2020-10-23 19:09 UTC, SergeyZhukovsky commented on patches/chrome-android-java-src-org-chromium-chrome-browser-suggestions-tile-TileGridLayout.java.patch
> ++if(false){
leave the empty string that was there, in that case we would have only 1 addition, right now it is 1 addition and 1 deletion

2020-10-23 19:09 UTC, SergeyZhukovsky commented on patches/chrome-android-java-src-org-chromium-chrome-browser-suggestions-tile-TileGridLayout.java.patch
> ++}
the same as above

2020-10-28 17:55 UTC, samartnik requested changes

2020-10-28 17:55 UTC, samartnik commented on patches/chrome-android-java-src-org-chromium-chrome-browser-suggestions-tile-TileGridLayout.java.patch
> +         assert horizontalSpacing <= mMaxHorizontalSpacing;
`mMaxHorizontalSpacing` is `Integer.MAX_VALUE`, how this assert can be triggered?

2020-10-28 17:55 UTC, samartnik commented on patches/chrome-android-java-src-org-chromium-chrome-browser-suggestions-tile-TileGridLayout.java.patch
> +         assert horizontalSpacing >= mMinHorizontalSpacing;
Shouldn't we change `tile_grid_layout_min_horizontal_spacing` instead?

2020-10-30 21:56 UTC, deeppandya commented
Closing this PR as creating new one

2020-10-30 21:56 UTC, closed without merging