Fix incognito icon in cookie settings
brave/brave-core pull request #7074
Opened 2020-11-06 09:28 UTC by mherrmann

Fixes: https://github.com/brave/brave-browser/issues/11738

@mihaiplesa can you suggest additional reviewers?

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`, `npm run gn_check`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.
- [ ] Added appropriate QA labels (`QA/Yes` or `QA/No`) to the associated issue
- [ ] Added appropriate release note labels (`release-notes/include` or `release-notes/exclude`) to the associated issue
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

2020-11-06 11:11 UTC, mherrmann commented
The [Linux build failure](https://ci.brave.com/job/pr-brave-browser-mherrmann-fix-incognito-icon-in-settings-linux/1/execution/node/249/log/) seems to be unrelated to this PR. I tried the generated .deb and am getting the expected UI change:

![image](https://user-images.githubusercontent.com/1076393/98359898-316e6b00-2029-11eb-8417-6cba03f53cf7.png)

2020-11-06 11:15 UTC, mihaiplesa commented
That icon looks familiar, wonder if we already had it added and we can just reference it.

<img width="167" alt="Screen Shot 2020-11-06 at 11 14 18 AM" src="https://user-images.githubusercontent.com/907672/98360233-5bbc2a80-2021-11eb-99c8-43cef8b4a89c.png">

2020-11-06 11:17 UTC, mherrmann commented
I did a preliminary search for the existing icon while researching the fix. Will try again.

2020-11-06 11:39 UTC, mherrmann commented
It's available as incognito.icon and incognito_profile.icon in [vector_icons/chrome/app/vector_icons](https://github.com/brave/brave-core/tree/master/vector_icons/chrome/app/vector_icons). 

In Brave: 
![image](https://user-images.githubusercontent.com/1076393/98362102-f53d0980-202c-11eb-933a-62301c7137af.png)

.icon file previews with https://github.com/sadrulhc/vector-icons:

![image](https://user-images.githubusercontent.com/1076393/98362147-08e87000-202d-11eb-8ec6-11edc794946b.png)

![image](https://user-images.githubusercontent.com/1076393/98362169-1140ab00-202d-11eb-965f-ebb05036a2fe.png)

I am not sure whether we can use these .icon files in brave://settings. Do you know who we could ask @mihaiplesa?

2020-11-06 14:47 UTC, mkarolin commented on patches/chrome-browser-resources-settings-site_settings-site_list_entry.html.patch
> +-            icon-class="settings20:incognito"
@petemill can this be done with //brave/browser/resources/settings/brave_overrides/icons.js override instead of patching?

2020-11-06 17:00 UTC, petemill requested changes
Thanks for this, left some feedback that would result in not needing to patch.

2020-11-09 11:01 UTC, mherrmann commented
Thank you very much for your kind review and suggestions @petemill @mkarolin. I implemented your recommended changes and still get the same screenshots:

![image](https://user-images.githubusercontent.com/1076393/98533314-16973300-2283-11eb-8828-1df21076e8f0.png)

![image](https://user-images.githubusercontent.com/1076393/98533322-1ac35080-2283-11eb-9e8c-0f4cdd14e3cb.png)

I also verified that it uses the shorter SVG suggested by @petemill.

![image](https://user-images.githubusercontent.com/1076393/98533389-36c6f200-2283-11eb-88e2-e03c4a299485.png)

This is my first PR to brave-core. How should I proceed? For example, should I squash my commits, or rebase them onto the current `master`?

2020-11-09 19:42 UTC, petemill approved these changes
Looks perfect. Yes, please squash before merge if you are able.

You don't have to rebase on master as there are no conflicts and CI has passed enough steps apart from what seems like a transient error that IMO we can ignore.

Good to merge if your squash results in no code change.

2020-11-10 05:57 UTC, merged

2020-11-10 05:58 UTC, mherrmann commented
Squashed and merged. Thank you @petemill @mkarolin @mihaiplesa !

2020-11-10 05:59 UTC, bsclifton commented
🕶️