Have speedreader fallback on chrome distill
brave/brave-core pull request #7137
Opened 2020-11-12 23:54 UTC by keur

If the user activates speedreader and the page is not in the speedreader
whitelist, quietly fallback on Chrome's distiller.

Resolves https://github.com/brave/brave-browser/issues/11994

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [x] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`, `npm run gn_check`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.
- [ ] Added appropriate QA labels (`QA/Yes` or `QA/No`) to the associated issue
- [ ] Added appropriate release note labels (`release-notes/include` or `release-notes/exclude`) to the associated issue
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

2020-11-17 08:55 UTC, iefremov commented on components/speedreader/BUILD.gn
> +    "//components/dom_distiller/content/browser",
we need it in `browser/BUILD.gn`, not here

2020-11-17 09:38 UTC, iefremov commented
Do I understand correctly that we want users to enable Distiller on `brave://flags` to make it tick?

2020-11-17 09:41 UTC, iefremov commented
From the user perspective, for now there is no way to undo distillation and get back to the normal page: neither toggling the speedreader button, nor reloading don't bring me back

2020-11-17 09:43 UTC, iefremov commented
Also we will have UI discrepancy: pages optimized with our speedreader have normal "lock" icon in the omnibox, while chrome-distilled ones would have "Reader Mode". Is it intended @rebron ?

2020-11-17 10:13 UTC, iefremov commented
There is also a trouble with back-forward navigation: with our speedreader hitting "Back" works as expected, while trying to go back on chrome-distilled page brings you back and then immeditealy re-runs the distiller, so you end up on a distilled version once again

2020-11-17 10:17 UTC, iefremov commented on browser/speedreader/speedreader_service_factory.cc
> +  DependsOn(dom_distiller::DomDistillerServiceFactory::GetInstance());
not sure if this is really needed

2020-11-17 10:18 UTC, iefremov commented on browser/speedreader/speedreader_tab_helper.cc
> +#include "chrome/browser/dom_distiller/dom_distiller_service_factory.h"
not needed

2020-11-17 10:21 UTC, iefremov commented on browser/ui/views/toolbar/speedreader_button.cc
> +      const bool active = tab_helper->IsReaderEnabled();
mb it should be `IsDistilled`

2020-11-17 10:22 UTC, iefremov commented on browser/speedreader/speedreader_tab_helper.cc
> +  return IsDistilledPage(url);
`GetURL()` is deprecated
`return IsDistilledPage(web_contents()->GetLastCommitedURL())`

2020-11-17 10:23 UTC, iefremov commented on browser/speedreader/speedreader_tab_helper.cc
> +  auto url = web_contents()->GetURL();
`GetURL()` is deprecated

2020-11-17 10:26 UTC, iefremov commented
Going back to a chrome-distilled page results in an infinite throbbler

2020-11-17 10:27 UTC, iefremov requested changes
I think we need a bit more detailed product vision for this (cc @rebron)

2021-05-19 14:32 UTC, iefremov commented
@keur do you think it's worth finalizing or maybe we could abandon?

2021-05-19 15:22 UTC, keur commented
Abandon

2021-05-19 15:22 UTC, closed without merging