Feature/custom notification ab test
brave/brave-core pull request #7377
Opened 2020-12-08 09:12 UTC by yachtcaptain23

Resolves 

## Submitter Checklist:

- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed).
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2020-12-09 22:03 UTC, fmarier requested changes

2020-12-09 22:03 UTC, fmarier commented on script/brave_license_helper.py
> +#        raise error
Did you forget to remove this?

2021-01-04 16:29 UTC, tmancey commented on android/BUILD.gn
> +    "//brave/chromium_src/chrome/browser/notifications/notification_handler.h",
@yachtcaptain23 Do you remember why this was added back as this was not part of the original ad notifications?

2021-01-04 16:49 UTC, tmancey commented
@yachtcaptain23 Do we not need to add `//brave/browser/notifications` back to `browser/BUILD.gn` or does the `brave_ads` implementation work for both?

2021-01-04 16:57 UTC, tmancey commented
@yachtcaptain23 Should `@JNINamespace("brave_ads")` be reverted to `@JNINamespace("chrome::android")`?

2021-01-04 17:05 UTC, tmancey commented
@yachtcaptain23 browser/notifications/brave_notification_platform_bridge_helper_android.cc and browser/notifications/brave_notification_platform_bridge_helper_android.h have not been reverted?

2021-01-04 17:16 UTC, tmancey commented
@yachtcaptain23 was it intentional that components/brave_ads/browser/ads_notification_handler.cc have not been reverted?

2021-01-04 17:23 UTC, tmancey commented on components/brave_ads/browser/ads_service_impl.cc
>  #include "chrome/browser/android/service_tab_launcher.h"
Is `#include "brave/browser/notifications/brave_notification_platform_bridge_helper_android.h"` not needed here, as it was included before custom ad notifications were added?

2021-01-04 17:27 UTC, tmancey commented on components/brave_ads/browser/ads_service_impl.cc
>    StartNotificationTimeoutTimer(ad_notification.uuid);
`StartNotificationTimeoutTimer was not called for Android for native notifications, is this logic correct?

2021-01-04 17:29 UTC, tmancey commented on components/brave_ads/browser/ads_service_impl.cc
> +    display_service_->Close(NotificationHandler::Type::BRAVE_ADS, uuid);
```#if defined(OS_ANDROID)	  std::unique_ptr<PlatformBridge>
  const std::string brave_ads_url_prefix = kBraveAdsUrlPrefix;	    platform_bridge = std::make_unique<PlatformBridge>(profile_);
  const GURL service_worker_scope =	  platform_bridge->Close(profile_, uuid);
      GURL(brave_ads_url_prefix.substr(0, brave_ads_url_prefix.size() - 1));	
  BraveNotificationPlatformBridgeHelperAndroid::MaybeRegenerateNotification(	
      uuid, service_worker_scope);	
#endif``` has not been re-added, is this no longer required?

2021-01-04 17:37 UTC, tmancey commented on components/brave_ads/browser/ads_service_impl.cc
> +  SetAdsServiceForNotificationHandler();
@yachtcaptain23 This was only initialized for native notifications, this should be guarded against dev or canary builds

2021-01-04 17:39 UTC, tmancey commented on components/brave_ads/browser/ads_service_impl.cc
> +  SetAdsServiceForNotificationHandler();
@yachtcaptain23 Ads service should only be set for native ad notifications

2021-01-04 17:48 UTC, tmancey commented on components/brave_ads/browser/ads_service_impl.cc
> +  SetAdsServiceForNotificationHandler();
Fixed. @yachtcaptain23 Could you please check the fix. Thanks

2021-01-04 18:10 UTC, tmancey commented
@yachtcaptain23 Closing this PR in favour of https://github.com/brave/brave-core/pull/7516/files, I have moved all comments to this new PR so that once the questions are answered we can merge before the train migration

2021-01-04 18:10 UTC, closed without merging