Added IPNS keys settings option
brave/brave-core pull request #8660
Opened 2021-04-28 14:50 UTC by spylogsster

Second part of https://github.com/brave/brave-browser/issues/15422

- Added an option to IPFS settings that link to subpage for keys management
- Added subpage that allows to create and remove keys
- Added extension APIs to add/remove/fetch keys from node

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

- go to brave://ipfs and use option to add/remove keys

2021-04-28 16:34 UTC, bbondy commented on app/brave_generated_resources.grd
> +        Enter name for new key
Enter a name for the new key

2021-04-28 16:34 UTC, bbondy commented on app/brave_generated_resources.grd
> +        This name can not be used
This name cannot be used

2021-04-28 16:35 UTC, bbondy commented on app/brave_generated_resources.grd
> +      <message name="IDS_SETTINGS_IPNS_KEYS_EDITOR_LINK_DESC" desc="The descriptoin for the link to open keys management block in IPFS settings">
s/descriptoin/description

2021-04-28 16:38 UTC, bbondy commented on common/extensions/api/_ipfs_api_features.json
> +    "dependencies": ["permission:ipfs"]
I don't think we want to expose anything new unless we have a security review for it and need to for the chrome.ipfs API

2021-04-28 16:44 UTC, bbondy requested changes
Things that still need addressing:

- API Permissions fixing

- When testing it I noticed that when I reload brave://settings/ipfs and I click on:
`Setup your IPNS keys` it does a refresh on the page and doesn't work until I click it a second time.

- When I was testing it I clicked to add a key but got this in the console `Unchecked runtime.lastError: IPFS node is not launched`.  No error message was displayed though in the page.  I didn't have a node installed yet on my local node.  We should only show this section when local node is selected in preferences and a node is installed. 
-  After it is installed but I restart the browser so the node isn't running, I get `Unchecked runtime.lastError: Unable to create key`.  In this case I think it should start the already installed node.

2021-04-29 12:50 UTC, spylogsster commented
> Things that still need addressing:
> 
> * API Permissions fixing
> * When testing it I noticed that when I reload brave://settings/ipfs and I click on:
>   `Setup your IPNS keys` it does a refresh on the page and doesn't work until I click it a second time.
> * When I was testing it I clicked to add a key but got this in the console `Unchecked runtime.lastError: IPFS node is not launched`.  No error message was displayed though in the page.  I didn't have a node installed yet on my local node.  We should only show this section when local node is selected in preferences and a node is installed.
> * After it is installed but I restart the browser so the node isn't running, I get `Unchecked runtime.lastError: Unable to create key`.  In this case I think it should start the already installed node.

done

2021-04-29 19:18 UTC, lidel commented
Writing down  things from today's sync:
- Add Import and Export  buttons to load/save keypair files via `ipfs key import|export`
- Add ability to rotate `self` key via `ipfs key rotate`
    - `ipfs key rotate -o self.old.FOO`  may improve UX a bit (FOO could be lat 4 characters of old key)
    - `self` key rotation could be also added to `brave:ipfs` page as a privacy feature to "Rotate Peer Identity (PeerID)`

2021-05-03 20:09 UTC, bbondy approved these changes

2021-05-05 05:28 UTC, merged