Page graph
brave/brave-core pull request #9186
Opened 2021-06-19 02:00 UTC by mihaiplesa

Resolves 

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2022-06-01 21:25 UTC, rillian approved these changes
r=me for rust deps and ffi.

2022-06-01 21:25 UTC, rillian commented on BUILD.gn
> +        #"$root_out_dir/$brave_exe",
Could this line just be removed instead of commented out?

2022-06-01 21:25 UTC, rillian commented on app/linux/BUILD.gn
> +    #brave_binary,
And if you want it commented out because it's temporary, documenting what needs to happen to re-enable is nice, even if it's just an issue link.

2022-06-01 21:25 UTC, rillian commented on build/rust/Cargo.lock
> + "itertools 0.10.1",
Current release is `0.10.3`. There changelog doesn't mention any security issues, so not critical, although 0.10.2 is missing.

2022-06-01 21:25 UTC, rillian commented on components/speedreader/rust/ffi/Cargo.lock
> +version = "1.0.64"
We're generally using `1.0.79` in libbrave_rust.

2022-10-13 20:51 UTC, fmarier requested changes
The changes in script/brave_license_helper.py look like they were not meant to be included in the PR.

2023-03-14 18:27 UTC, closed without merging