Add brave vpn button to toolbar
brave/brave-core pull request #9604
Opened 2021-08-02 04:39 UTC by simonhong

Resolves 

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2021-08-02 16:17 UTC, keur commented on browser/ui/views/toolbar/brave_vpn_button.cc
> +  return;
nit: no-op

2021-08-02 16:17 UTC, keur commented on browser/ui/views/toolbar/brave_vpn_button.cc
> +BraveVPNButton::~BraveVPNButton() = default;
nit: can put this in header

2021-08-02 16:17 UTC, keur commented on browser/ui/views/toolbar/brave_vpn_button.cc
> +  NOTIMPLEMENTED();
missing include for `base/notreached.h`?

2021-08-02 16:17 UTC, keur commented on browser/ui/views/toolbar/brave_vpn_button.cc
> +constexpr int kHighlightRadius = 47;
is this the thickness in pixels of highlight? comment here would be nice

2021-08-02 16:17 UTC, keur commented on components/brave_vpn/brave_vpn_utils.h
> +}
nit: missing terminating namespace comment

2021-08-02 18:40 UTC, karenkliu requested changes
Hi! Sorry - I just added the dark theme colors. Please take a look and tweak the VPN button style for dark theme: https://www.figma.com/file/qtMYwoj3JWJO5xzwLt6j2f/?node-id=0%3A1

![image](https://user-images.githubusercontent.com/2388823/127908411-16da3448-9baa-4151-8f07-920dd028c52c.png)

2021-08-03 02:09 UTC, simonhong reviewed
@karenkliu dark theme updated. PTAL again.

2021-08-03 02:17 UTC, keur approved these changes
LGTM

2021-08-03 23:27 UTC, karenkliu requested changes
Hi @simonhong , when VPN is disconnected it should actually look like this:

<img width="84" alt="Screen Shot 2021-08-03 at 7 12 47 PM" src="https://user-images.githubusercontent.com/2388823/128097803-0fed68c7-b8f4-4e64-842d-ef81a5418abd.png">

I decided not to have the "Disconnected" text to avoid taking up too much space in the toolbar!

2021-08-04 00:19 UTC, karenkliu approved these changes
Looks great! 🚀

2021-08-04 05:32 UTC, simonhong commented
Merged because previous CI run got all green and just rebased on master with trivial conflict.

2021-08-04 05:32 UTC, merged