Fixed show search tabs string
brave/brave-core pull request #9637
Opened 2021-08-03 18:37 UTC by nullhook

Resolves https://github.com/brave/brave-browser/issues/17310

Screenshot:
![image](https://user-images.githubusercontent.com/8665427/128068393-d32eb4b7-0060-4cf5-ad55-9da7d89c60f9.png)

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

2021-08-03 19:19 UTC, karenkliu commented
Unassigning myself and assigning @rmcfadden3 since this is purely a text thing.

Btw, the toggle should be default on.

2021-08-03 21:08 UTC, rmcfadden3 commented
Copy looks good.

2021-08-04 01:15 UTC, simonhong commented on browser/ui/views/frame/brave_browser_view.cc
> +  BraveBrowserView::OnPreferenceChanged(kTabsSearchShow);
How about creating `UpdateSearchTabButtonState()` and move `OnPreferenceChanged`'s impl to it?
Then, calling `UpdateSearchTabButtonState()` from here and from `OnPreferenceChanged()` ?

2021-08-04 01:44 UTC, simonhong commented
and How about adding browser test case that check whether button has proper visibility after startup and whether visibility is matched after changing prefs?

2021-08-04 05:08 UTC, simonhong approved these changes
++ 👍🏼

2021-08-04 05:08 UTC, simonhong commented on browser/ui/views/frame/brave_browser_view.cc
> +  BraveBrowserView::UpdateSearchTabsButtonState();
nit: Don't need to call with class name.

2021-08-04 05:08 UTC, simonhong commented on browser/ui/views/frame/brave_browser_view.cc
> +    BraveBrowserView::UpdateSearchTabsButtonState();
ditto.

2021-08-04 05:28 UTC, petemill requested changes
minor string change

2021-08-04 05:28 UTC, petemill commented on app/brave_generated_resources.grd
> +        Show Search tabs button
"Show tab search button"

2021-08-04 06:47 UTC, simonhong approved these changes
++

2021-08-04 06:58 UTC, petemill approved these changes
beautiful test!

2021-08-04 09:27 UTC, merged